### ISSUE TITLE
Deleted my pinecone index - main.py not checking if index exists before starting?

### ISSUE THREAD

**Issue by Rikiar73574** [Significant-Gravitas/Auto-GPT#1161]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

- start autogpt with  `MEMORY_BACKEND=pinecone`
- delete pinecone index
- restart autogpt and receive the following error:
`Traceback (most recent call last):
  File "D:\AI\Auto-GPT\Auto-GPT\scripts\main.py", line 335, in <module>
    memory = get_memory(cfg, init=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Auto-GPT\Auto-GPT\scripts\memory\__init__.py", line 30, in get_memory
    memory.clear()
  File "D:\AI\Auto-GPT\Auto-GPT\scripts\memory\pinecone.py", line 36, in clear
    self.index.delete(deleteAll=True)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\index.py", line 329, in delete
    return self._vector_api.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api\vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 222, in request
    raise ForbiddenException(http_resp=r)
pinecone.core.client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Thu, 13 Apr 2023 18:12:17 GMT', 'server': 'envoy'})`

### Current behavior 😯

- not starting
- having either to manually recreate index or modifying code

### Expected behavior 🤔

- just create a new index

### Your prompt 📝

not relevant

**Comment by Camille92** [comment]
Same error here
