### ISSUE TITLE
"NameError: name 'cfg' is not defined" in memory/base.py

### ISSUE THREAD

**Issue by YoniGlazer** [Significant-Gravitas/Auto-GPT#1169]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 442, in <module>
    main()
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 346, in main
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\base.py", line 9, in get_ada_embedding
    if cfg.use_azure:
       ^^^
NameError: name 'cfg' is not defined

### Current behavior 😯

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 442, in <module>
    main()
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 346, in main
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\base.py", line 9, in get_ada_embedding
    if cfg.use_azure:
       ^^^
NameError: name 'cfg' is not defined

### Expected behavior 🤔

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 442, in <module>
    main()
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 346, in main
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\base.py", line 9, in get_ada_embedding
    if cfg.use_azure:
       ^^^
NameError: name 'cfg' is not defined

### Your prompt 📝

```yaml
# Paste your prompt here
```
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 442, in <module>
    main()
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 346, in main
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\memory\base.py", line 9, in get_ada_embedding
    if cfg.use_azure:
       ^^^
NameError: name 'cfg' is not defined

**Comment by paynegh** [comment]
Same issue here, adding `cfg = Config()` in the memory folder does not work as well since it already exists.

**Comment by paynegh** [comment]
Found the solution! This is happening because the OpenAI API you are using is not the paid version. After subscribing to the paid one, it works great

**Comment by YoniGlazer** [comment]
No but it is the paid version. I am paying for it

**Comment by Pwuts** [comment]
@YoniGlazer are you still experiencing this issue with the latest version?

**Comment by YoniGlazer** [comment]
Is the chatGpt interface different from the openai website?

I’m asking because I am being billed the $20/month but on openai I do not
see that i am paying?

**Comment by Pwuts** [comment]
ChatGPT Plus subscription is separate from OpenAI API billing. You need to specifically set up billing in your OpenAI account to get API access. This is also in the README.

Closing as resolved. If you need more help, ask in #tech-support in the discord server.
