### ISSUE TITLE
Error in infinite loop : /scripts/json_parser.py", line 51

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#1182]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python3 scripts/main.py --continuous --gpt3only

### Current behavior 😯

infinite loop with following message

```
Error:        
 Traceback (most recent call last): File "/home/katya/poligon/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/home/katya/poligon/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found
NEXT ACTION:  COMMAND = Error: ARGUMENTS = substring not found
SYSTEM:  Command Error: threw the following error: substring not found

```

### Expected behavior 🤔

some self-fix behavior or execution stop

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by PodevynLoris** [comment]
Getting the same error

**Comment by p-i-** [comment]
Community effort to sort out this JSON fail once and for all at https://github.com/Torantulino/Auto-GPT/issues/1407

We have 17 open PRs for fixing this, and the merge-team are stacked.

**Comment by Pwuts** [comment]
Closing as one of many duplicates; superseded by #1407
