### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### ISSUE THREAD

**Issue by MrAcle-cyber** [Significant-Gravitas/Auto-GPT#1278]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/main.py", line 461, in <module>
    main()
  File "scripts/main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\Mr Acle\Auto-GPT\scripts\chat.py", line 77, in chat_with_ai
    next_message_to_add_index, current_tokens_used, insertion_index, current_context = generate_context(
  File "C:\Users\Mr Acle\Auto-GPT\scripts\chat.py", line 40, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "C:\Users\Mr Acle\Auto-GPT\scripts\token_counter.py", line 17, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken\load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tiktoken\load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### Expected behavior 🤔

It may be a proxy issue,help me pls

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by qwe2950531** [comment]
大哥你跟我一样啊  插个眼

**Comment by SiyuanLi-SYSUSOB** [comment]
same problem! 
I use clash for vpn, global proxy.
I spend 2 hours on this problem but failed.

Continue (y/n): y
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\..AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AAAPythonProjects\Auto-GPT\scripts\main.py", line 461, in <module>
    main()
  File "D:\AAAPythonProjects\Auto-GPT\scripts\main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "D:\AAAPythonProjects\Auto-GPT\scripts\chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "D:\AAAPythonProjects\Auto-GPT\scripts\llm_utils.py", line 28, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by huangjingshuai** [comment]
me too

**Comment by Monkey-Bo** [comment]
The same problem ，when I use the VPN to run the system from China

**Comment by linrty** [comment]
windows在系统的我环境变量里面添加你的代理端口，比如clash，添加http_proxy和https_proxy变量，设置成http://127.0.0.1:7890

**Comment by qwe2950531** [comment]
> windows在系统的我环境变量里面添加你的代理端口，比如clash，添加http_proxy和https_proxy变量，设置成http://127.0.0.1:7890

加了 没用

**Comment by linrty** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到。

**Comment by aiyoheidei** [comment]
1. Run Terminal as Administrator
2. set http_proxy=127.0.0.1:7890
3. set https_proxy=127.0.0.1:7890

**Comment by zy0525** [comment]
降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

**Comment by zym16621** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

这个真可以，赞~~

**Comment by litchimango** [comment]
在scripts/main.py的开头加入：
import os
os.environ["http_proxy"] = "你的代理协议://地址:端口"
os.environ["https_proxy"] = "你的代理协议://地址:端口"即可
如clash：
import os
os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
具体的代理协议/地址/端口在自己的代理软件上查看

**Comment by zym16621** [comment]
谢谢！




--

                                                                                                                   致
礼
                                                                                                               周业茂




在 2023-04-15 11:54:29，"litchimango" ***@***.***> 写道：

在scripts/main.py的开头加入：
import os
os.environ["http_proxy"] = "你的代理协议://地址:端口"
os.environ["https_proxy"] = "你的代理协议://地址:端口"即可
如clash：
import os
os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
具体的代理协议/地址/端口在自己的代理软件上查看

**Comment by tutuxxx** [comment]
> 在scripts/main.py的开头加入： import os os.environ["http_proxy"] = "你的代理协议://地址:端口" os.environ["https_proxy"] = "你的代理协议://地址:端口"即可 如clash： import os os.environ["http_proxy"] = "http://127.0.0.1:7890" os.environ["https_proxy"] = "http://127.0.0.1:7890" 具体的代理协议/地址/端口在自己的代理软件上查看

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by litchimango** [comment]
> 
可能是urllib3版本问题，使用pip install urllib3==1.25.11对urllib3进行降级

**Comment by litchimango** [comment]
> > 在scripts/main.py的开头加入： import os os.environ["http_proxy"] = "你的代理协议://地址:端口" os.environ["https_proxy"] = "你的代理协议://地址:端口"即可 如clash： import os os.environ["http_proxy"] = "http://127.0.0.1:7890" os.environ["https_proxy"] = "http://127.0.0.1:7890" 具体的代理协议/地址/端口在自己的代理软件上查看
> 
> 按这个配置后出下面报错，代理是ss，全局模式 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

可能是urllib3版本问题，使用pip install urllib3==1.25.11对urllib3进行降级

**Comment by tutuxxx** [comment]
> > > 在scripts/main.py的开头加入： import os os.environ["http_proxy"] = "你的代理协议://地址:端口" os.environ["https_proxy"] = "你的代理协议://地址:端口"即可 如clash： import os os.environ["http_proxy"] = "http://127.0.0.1:7890" os.environ["https_proxy"] = "http://127.0.0.1:7890" 具体的代理协议/地址/端口在自己的代理软件上查看
> > 
> > 
> > 按这个配置后出下面报错，代理是ss，全局模式 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
> 
> 可能是urllib3版本问题，使用pip install urllib3==1.25.11对urllib3进行降级

也不行，我是这样加的
import os

os.environ["http_proxy"] = "http://127.0.0.1:1087"
os.environ["https_proxy"] = "http://127.0.0.1:1087"

<img width="477" alt="image" src="https://user-images.githubusercontent.com/14323022/232185361-39e14490-185e-4e70-97ca-abcaf6480eab.png">

**Comment by zhaoxiaozhou** [comment]
solve the problm by downgrade pip install urllib3==1.25.11

**Comment by sundayYa** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

is ok,thanks

**Comment by Monkey-Bo** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

我降完版本也可以了，感谢

**Comment by wblksheep** [comment]
Like this: when urllib3 throws an error, traceback to the source code of Autogpt instead of searching for the library's location, and add the following lines at the beginning:
import os
os.environ["http_proxy"] = "http://your_proxy_ip:your_proxy_port"
os.environ["https_proxy"] = "https://your_proxy_ip:your_proxy_port"
If you are using Clash, it might look like this:
import os
os.environ["http_proxy"] = "http://127.0.0.1:7890/"
os.environ["https_proxy"] = "https://127.0.0.1:7890/"

**Comment by Zhubaiali** [comment]
> Like this: when urllib3 throws an error, traceback to the source code of Autogpt instead of searching for the library's location, and add the following lines at the beginning:像这样：当urllib3报错时，不去寻找库所在的位置，而是回溯到Autogpt的源码，在开头添加如下几行： import os 进口我们 os.environ["http_proxy"] = "http://your_proxy_ip:your_proxy_port" os.environ["https_proxy"] = "https://your_proxy_ip:your_proxy_port" If you are using Clash, it might look like this:如果您使用的是 Clash，它可能看起来像这样： import os 导入操作系统 os.environ["http_proxy"] = "http://127.0.0.1:7890/" os.environ["https_proxy"] = "https://127.0.0.1:7890/"

在哪个地方添加？主目录下的main.py吗？还是不行。
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "M:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "M:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "M:\Anaconda\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "M:\Anaconda\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "M:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "M:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "M:\Anaconda\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "M:\Anaconda\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "M:\Anaconda\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\Anaconda\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "M:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "M:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "M:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "M:\Anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\Anaconda\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "M:\Anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "M:\Anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "M:\Anaconda\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "M:\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\AI\Auto-GPT\autogpt\__main__.py", line 53, in <module>
    main()
  File "C:\AI\Auto-GPT\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "C:\AI\Auto-GPT\autogpt\agent\agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\AI\Auto-GPT\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\AI\Auto-GPT\autogpt\llm_utils.py", line 91, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "M:\Anaconda\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "M:\Anaconda\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "M:\Anaconda\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "M:\Anaconda\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
(base) PS C:\AI\Auto-GPT>

**Comment by ntindle** [comment]
Proxys are not well supported right now. Feel free to open a PR to add better proxy support

**Comment by youngest-on-top** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了
降完真的可以，非常感谢大佬！

**Comment by hellotohere** [comment]
> scripts/main.py的开头加入：

这个真的可以 点赞

**Comment by linrty** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到。

**Comment by hellotohere** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

这个真不错 非常可以 点赞

**Comment by 2020lwh567** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

大佬太强了！感谢大佬拯救苍生于水火之中~

**Comment by stenty** [comment]
> 降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

确实有效，折腾半天不如降个版本。。感谢

**Comment by yshuang666** [comment]
I have same problem in  PyCharm!  I use Clash vpn。
I resolve this problem by turning on the TUN Mode in the Clash for Windows. I not set proxy in  PyCharm。

**Comment by Shuoheyiwen** [comment]
感谢大佬

**Comment by Suz1e** [comment]
pip install urllib3==1.25.11 降了版本还是会报错，大家伙还有其他解决方案吗？？

 /匹配 TOP_REAPER 时间： 2024-07-27T20:17:24+08:00 群组： 207F74F68E20979A3E52BB
F42B1C4E70
stdout: 请求失败，错误信息：HTTPSConnectionPool(host='api.pubg.com', port=443):
Max retries exceeded with url: /shards/steam/players?filter%5BplayerNames%5D=TOP
_REAPER (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protoco
l (_ssl.c:1129)')))

stderr:

[1;33m[INFO]   (robot私信.py:230)on_group_at_message_create    [0m{'id': 'ROBO
T1.0_4moc1FtbvXtWtfbAQnGtM9f3zpECltj1K3q.YDzvYoadGCIcCTMLim3eTvtBy-72FTr1b9Lm2Ov
thAAhbB8DCg!!', 'timestamp': '2024-07-27T20:17:57+08:00'}
