### ISSUE TITLE
Unable to find a solution to this problem elsewhere. Any ideas?

### ISSUE THREAD

**Issue by ishaoshupai** [Significant-Gravitas/Auto-GPT#1382]
Unable to find a solution to this problem elsewhere. Any ideas?

Have regenerated Open API a number of times still to no avail.

_Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Auto-GPT-master\Auto-GPT\scripts\main.py", line 343, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\Auto-GPT-master\Auto-GPT\scripts\chat.py", line 72, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
  File "C:\Users\Auto-GPT-master\Auto-GPT\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
  File "C:\Users\Auto-GPT-master\Auto-GPT\scripts\memory\base.py", line 13, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\T\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line        
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: your-ope*******-key. You can find your API key at https://platform.openai.com/account/api-keys._

_Originally posted by @tonygem2022 in https://github.com/Torantulino/Auto-GPT/discussions/1057_

**Comment by Momof3disneyfans** [comment]
I'm having the same issue

**Comment by JF10R** [comment]
> `openai.error.AuthenticationError: Incorrect API key provided: your-ope****-key. You can find your API key at https://platform.openai.com/account/api-keys.`


You need to specify your OpenAI API key in the `.env` file. Please following the installation instructions of the ReadMe [here](https://github.com/Torantulino/Auto-GPT#-installation).

**Comment by ishaoshupai** [comment]
Using memory of type: LocalCache
Traceback (most recent call last):
  File "D:\Auto-GPT-master\scripts\main.py", line 465, in <module>
    main()
  File "D:\Auto-GPT-master\scripts\main.py", line 328, in main
    agent.start_interaction_loop()
  File "D:\Auto-GPT-master\scripts\main.py", line 369, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT-master\scripts\chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT-master\scripts\llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

this my issue, can anybody help?

**Comment by wchevalier** [comment]
I am getting the same error and openai is showing as the key has a last used date after creating a new key and adding the new key to my .env file.

**Comment by Momof3disneyfans** [comment]
I've had to go back to an older version until this is corrected

**Comment by Qoyyuum** [comment]
@ishaoshupai you need to check your OpenAI account whether it has any valid tokens left, otherwise please top up your tokens by paying for it. See this link for reference: https://platform.openai.com/account/billing/overview

**Comment by askivo** [comment]
I'm having the same issue; there is no old key in my environment, I have a paid account, I added the key properly, the .env file is saved properly, but still this.

What else can I troubleshoot?

**Comment by fewmatty** [comment]
I am also having this issue today, I have created a new key and made sure it is in the .env file as it should be, really stuck here.

**Comment by fewmatty** [comment]
@askivo it worked for me when I just fed it the key manually, you do have to do this every time tho until there is a fix

like this:  [export OPENAI_API_KEY='OPENAI KEY HERE']
