### ISSUE TITLE
The version of Python needs to be higher than 3.8

### ISSUE THREAD

**Issue by heouchen** [Significant-Gravitas/Auto-GPT#1583]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python version：3.8.8 
python -m autogpt

### Current behavior 😯

(base) D:\auto-gpt>python -m autogpt
Traceback (most recent call last):
  File "E:\software\anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\software\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\auto-gpt\autogpt\__main__.py", line 3, in <module>
    from autogpt.agent.agent import Agent
  File "D:\auto-gpt\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "D:\auto-gpt\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "D:\auto-gpt\autogpt\app.py", line 4, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "D:\auto-gpt\autogpt\agent\agent_manager.py", line 7, in <module>
    class AgentManager(metaclass=Singleton):
  File "D:\auto-gpt\autogpt\agent\agent_manager.py", line 17, in AgentManager
    def create_agent(self, task: str, prompt: str, model: str) -> tuple[int, str]:
TypeError: 'type' object is not subscriptable

### Expected behavior 🤔

work

### Your prompt 📝

```yaml
# Paste your prompt here
```
updata the readme

**Comment by nachobuey** [comment]
same problem here

**Comment by heouchen** [comment]
use python 3.10.10

**Comment by Lks7** [comment]
use python 3.9
