### ISSUE TITLE
Pinecone 504 Gateway Timeout error

### ISSUE THREAD

**Issue by blanchardjeremy** [Significant-Gravitas/Auto-GPT#1616]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

* On stable (HASH: 60b2b61b52c26) as of Apr 15 in the morning. v0.2.0
* Configure Pinecone as memory source
* Run `python -m autogpt`

### Current behavior 😯

* Everything was working yesterday before I pulled the latest `stable` update (so I know my pinecone config is correct).
* When I run the command above, I get a long lag. Like 15 seconds. 

Error log
```
Traceback (most recent call last):
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/__main__.py", line 9, in <module>
    from autogpt import commands as cmd
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/commands.py", line 9, in <module>
    from autogpt.browse import scrape_links, scrape_text, summarize_text
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/browse.py", line 11, in <module>
    memory = get_memory(cfg)
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/memory/__init__.py", line 34, in get_memory
    memory = PineconeMemory(cfg)
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/config.py", line 22, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/jeremy/dev/autogpt/Auto-GPT/autogpt/memory/pinecone.py", line 36, in __init__
    if table_name not in pinecone.list_indexes():
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 207, in __call_api
    raise e
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/Users/jeremy/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 228, in request
    raise ServiceException(http_resp=r)
pinecone.core.client.exceptions.ServiceException: (504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain', 'content-length': '24', 'date': 'Sat, 15 Apr 2023 15:41:20 GMT', 'server': 'envoy'})
HTTP response body: upstream request timeout
```

### Expected behavior 🤔

* Pinecone connects and the program runs. :)

### Your prompt 📝

N/A

**Comment by blanchardjeremy** [comment]
Oh nevermind. Pinecone must have been down. Tried again a few minutes later and it worked. Closing.
