### ISSUE TITLE
Failed to get response after 5 retries

### ISSUE THREAD

**Issue by kaili-yang** [Significant-Gravitas/Auto-GPT#1677]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

- Mac OS BIg Sur v11.0.1
- Apple M1 chip, 16G memory
- Python version 3.9.1

- It's stable branch.
- pip install successfully(no error, no warning, all pkg installed succcesfully)
- `faild to run` python -m autogpt

### Current behavior 😯

```
(base)  user@user-MBP  ~/Documents/Auto-GPT   master  python -m autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: user-GPT
Kaili-GPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Kaili-GPT is: A softwre enginner
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Use React to develop a website
Goal 2: there's a form on the website
Goal 3: the UI interface should includes transit animation
Goal 4: there're input, raio, checkbox and a button in the form
Goal 5: the form component shoule be 2-way binding data
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/yangkaili/opt/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/yangkaili/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yangkaili/Documents/Auto-GPT/autogpt/__main__.py", line 572, in <module>
    main()
  File "/Users/yangkaili/Documents/Auto-GPT/autogpt/__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "/Users/yangkaili/Documents/Auto-GPT/autogpt/__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "/Users/yangkaili/Documents/Auto-GPT/autogpt/chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/Users/yangkaili/Documents/Auto-GPT/autogpt/llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries
```

### Expected behavior 🤔

It should be running successfully and return the correct results.

### Your prompt 📝

```yaml
AI Name: Kaili-GPT
Kaili-GPT is: A softwre enginner
Goal 1: Use React to develop a website
Goal 2: there's a form on the website
Goal 3: the UI interface should includes transit animation
Goal 4: there're input, raio, checkbox and a button in the form
Goal 5: the form component shoule be 2-way binding data
```

**Comment by davidgodinez** [comment]
Having the same issue

**Comment by GeekLabsUK** [comment]
same issue

**Comment by HadiEsna** [comment]
same issue here

**Comment by umar-tung** [comment]
do you have paid billing setup for the openAI API? You have to have that setup for it to work.

**Comment by TheAisBack** [comment]
I had this issue as well. You have to have your credit card on file. This will fix the problem.

**Comment by polo13999** [comment]
the same here

**Comment by EKami** [comment]
Same here

**Comment by midhunt** [comment]
I still have the same issue even after adding CC details.

**Comment by EKami** [comment]
It's working on my side after adding a credit card

**Comment by servel333** [comment]
Add a payment method here.

https://platform.openai.com/account/billing/payment-methods

**Comment by jpgaillm** [comment]
Same problem here. im using --gpt3only, so i dont know if i would need a credit card

**Comment by Qoyyuum** [comment]
@jpgaillm you need a credit card and setup a paid OpenAI account before using.
