### ISSUE TITLE
Traceback (most recent call last) Error

### ISSUE THREAD

**Issue by ronrevog** [Significant-Gravitas/Auto-GPT#1686]
when i try to run i get this error:
any ideas? thanks!

pymilvus not installed. Skipping import.
Traceback (most recent call last):
  File "C:\Users\paperspace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\paperspace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Auto-GPT\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Auto-GPT\autogpt\app.py", line 25, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "C:\Auto-GPT\autogpt\commands\git_operations.py", line 2, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

**Comment by devrimdemiroz** [comment]
Commenting out `git_operations.py` worked for me as I did not connect(need) my github account.

```
# from config import Config

# cfg = Config()
```

**Comment by Slowly-Grokking** [comment]
this is fixed in the current version.
https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/commands/git_operations.py

just needs "from **autogpt.**config import Config"

**Comment by ronrevog** [comment]
updated the file with both methods above im still getting this:

C:\Auto-GPT>python -m autogpt --speak --gpt3only
pymilvus not installed. Skipping import.
Traceback (most recent call last):
  File "C:\Users\paperspace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\paperspace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Auto-GPT\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Auto-GPT\autogpt\app.py", line 25, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "C:\Auto-GPT\autogpt\commands\git_operations.py", line 2, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

**Comment by Slowly-Grokking** [comment]
> from config import Config
> ModuleNotFoundError: No module named 'config'

grab the newest git_operations.py 
"from config import Config" is "from autogpt.config import Config" now

**Comment by ronrevog** [comment]
that worked thank you so much!!

no if only my gpt4 api waitlist would come through, its been 4 weeks =? ive reapplied like 6 times and im a paying user.
