### ISSUE TITLE
I have never been sure what the problem is and I hope to receive your guidance.

### ISSUE THREAD

**Issue by shenqingwangyixuan** [Significant-Gravitas/Auto-GPT#1693]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Debug Mode:  ENABLED
Welcome back!  Would you like me to return to being WYX?
Continue with the last settings?
Name:  WYX
Role:  一个聊天机器人
Goals: ['记住我的名字：达芬奇', '你叫什么名字', '谁开发了你', '我将如何更好的使用你']
Continue (y/n): y                                                
Using memory of type: LocalCache
  Token limit: 4000
  Memory Stats: (0, (0, 1536))
  Token limit: 4000
  Send Token Count: 908
  Tokens remaining for response: 3092
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Sun Apr 16 03:52:08 2023
  
  System: This reminds you of these events from your past:

  
  User: Determine which next command to use, and respond using the format specified above:
  
  ----------- END OF CONTEXT ----------------
Creating chat completion with model gpt-3.5-turbo, temperature 1.0, max_tokens 3092
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/zhang/Auto-GPT/autogpt/__main__.py", line 572, in <module>
    main()
  File "/Users/zhang/Auto-GPT/autogpt/__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "/Users/zhang/Auto-GPT/autogpt/__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "/Users/zhang/Auto-GPT/autogpt/chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/Users/zhang/Auto-GPT/autogpt/llm_utils.py", line 32, in create_chat_completion
    deployment_id=cfg.get_azure_deployment_id_for_model(model),
  File "/Users/zhang/Auto-GPT/autogpt/config.py", line 111, in get_azure_deployment_id_for_model
    return self.azure_model_to_deployment_id_map["fast_llm_model_deployment_id"]
TypeError: list indices must be integers or slices, not str
zhang@localhost Auto-GPT % 

### Your prompt 📝

```

**Comment by Explorergt92** [comment]
Same issue as #1483 ?
