### ISSUE TITLE
i have no glue what to do with that..pls help it correct.

### ISSUE THREAD

**Issue by CeberusOne** [Significant-Gravitas/Auto-GPT#1737]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I have done all the steps needed to install auto-gbt but then i got problems that the cmd says it cant find OpenAi API Key alltho i write it in the env file and even with new generated Keys ...it says auto-gbt.json file not found ...and couldnt find OpenAi API Key. Im solving this Problem after renaming the env file with visual studios also to env filetype and not template or textfile.

My Working System is Windows11 , i created a new Folder and Download the newest Version by Zip ,extracted it and follow the next Steps....i have also done all the requirements , so install Git, Visual Code and so on

### Current behavior 😯

So after that my auto-gbt finaly starts but until i choose the name and describe the goal this happens: 

Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Mike\OpenAI\Auto-GPT>python -m autogpt
Welcome back!  Would you like me to return to being me?
Continue with the last settings?
Name:  me
Role:  Halomaster
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11003] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002547FC5BB50>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002547FC5BB50>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Mike\OpenAI\Auto-GPT\autogpt\token_counter.py", line 24, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\load.py", line 24, in read_file
    return requests.get(blobpath).content
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menke\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002547FC5BB50>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed'))

C:\Mike\OpenAI\Auto-GPT>

### Expected behavior 🤔

Well, i would be Happy Auto-GPT works like it should be.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by isaaclepes** [comment]
Are you using the stable branch?
https://github.com/Significant-Gravitas/Auto-GPT/tree/stable

**Comment by CeberusOne** [comment]
> Are you using the stable branch? https://github.com/Significant-Gravitas/Auto-GPT/tree/stable

Yes im using the latest stable branch.

**Comment by CeberusOne** [comment]
Im using also the newest Python Version , but in next step i will try using a older Version of Python, maybe this will Help....i mean i have absolute no experience with Scripting or Coding so far , but what i can logical think about and the writings is , that there are many entrys looks like have to do with the Python Libary ....so either the libary of the Auto -Gpt is messed Up or  the Python Libary itself. Am i right?

**Comment by Imccccc** [comment]
check your network, 'openaipublic.blob.core.windows.net' is belong to openai/microsoft

**Comment by CeberusOne** [comment]
> check your network, 'openaipublic.blob.core.windows.net' is belong to openai/microsoft

Okay where do i find this? And what espacialy i have to check for?

**Comment by Imccccc** [comment]
> 

Network issue is hard to debug, maybe you should call ISP

**Comment by CeberusOne** [comment]
> > 
> 
> Network issue is hard to debug, maybe you should call ISP

Oh thats why i dont get a connection out of the cmd prompt if i try to fetch information from GitHub or they cant read to pincone , makes sense. 

But the cuiriosity is i have still Connection over Web Browser 🤔

Well thx for the Help, i will Check this.

**Comment by JohnnyFi-GPT** [comment]
Have you put your API's in quotes?

**Comment by CeberusOne** [comment]
> Have you put your API's in quotes? 

No i didnt...should i ? I dont guess so. 🤔

No i think the Main Problem is my Network like the previous said....i allrdy Search for that and its mostly bound to Azure alltho the odd thing is... i didnt even use Azure nor i set a Key or Something like that.

**Comment by JohnnyFi-GPT** [comment]
> > Have you put your API's in quotes?
> 
> No i didnt...should i ? I dont guess so. 🤔
> 
> No i think the Main Problem is my Network like the previous said....i allrdy Search for that and its mostly bound to Azure alltho the odd thing is... i didnt even use Azure nor i set a Key or Something like that.

Yes!! All API's need to be in quotes.

**Comment by JohnnyFi-GPT** [comment]
actually you need to have API Keys, Pinecone Env, and Elevenlabs voice ID all in quotes.

**Comment by CeberusOne** [comment]
> Yes!! All API's need to be in quotes.

Since when? ...in Point 5. From the Installation Guide it says clearly...(WITHOUT...any Quotes or Spaces) !

**Comment by CeberusOne** [comment]
> actually you need to have API Keys, Pinecone Env, and Elevenlabs voice ID all in quotes.  

No you dont, just the OpenAi Key ...other Keys are only Optional.

**Comment by Imccccc** [comment]
The issue cause by Tiktoken, the library need download dictionary when first load. It is not related to any API keys.
If you are not in China, it is a network issue.

**Comment by Pwuts** [comment]
Closing as this doesn't seem to be an issue with Auto-GPT itself. Please start a [discussion](https://github.com/Significant-Gravitas/Auto-GPT/discussions) or ask in the [discord](https://discord.gg/autogpt) if you need more help.
