### ISSUE TITLE
Running docker image directly from command line fails

### ISSUE THREAD

**Issue by danmohad** [Significant-Gravitas/Auto-GPT#1760]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

M1 Mac 13.2.1, Docker 4.18.0

The `stable` branch is behind in terms of docker support (see #1445) so it's irrelevant here.

On the current `master` branch, from a `zsh` shell:
```
docker build -t autogpt .
docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt
```

### Current behavior 😯

The `docker run` command fails with the following output.
```
pymilvus not installed. Skipping import.
Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/appuser/autogpt/__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/home/appuser/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/appuser/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/appuser/autogpt/app.py", line 26, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "/home/appuser/autogpt/commands/git_operations.py", line 2, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```
So `gitpython` is missing, and there is a warning for `pymilvus` missing. If `gitpython` is added to `requirements-docker.txt`, we get a `ModuleNotFoundError` for `tweepy`.

### Expected behavior 🤔

Auto-GPT should run

**Comment by joshsabol46** [comment]
TY, fixed my error as well!

```
ModuleNotFoundError: No module named 'tweepy'
```
