### ISSUE TITLE
what's the matter

### ISSUE THREAD

**Issue by 12121aaaa** [Significant-Gravitas/Auto-GPT#1816]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Ai draw\AotuGPT\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\__main__.py", line 53, in <module>
    main()
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\agent\agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\token_counter.py", line 25, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### Current behavior 😯

It's like this every time, it shows this, and it can't continue

### Expected behavior 🤔

what should I do

### Your prompt 📝

```yaml
# Paste your prompt here
```
what should I do

**Comment by Qoyyuum** [comment]
Can you explain exactly what you did? How do you setup and what commands you executed?

**Comment by 12121aaaa** [comment]
python -m autogpt --gpt3only
Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
GPT3.5 Only Mode:  ENABLED
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: project analyst
project analyst here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
project analyst is: Analyze Industry Projects
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Analyzing Google Financial Reports
Goal 2: Save to txt text
Goal 3: close when done
Goal 4:
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Ai draw\AotuGPT\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Ai draw\AotuGPT\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ai draw\AotuGPT\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Ai draw\AotuGPT\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\__main__.py", line 53, in <module>
    main()
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\agent\agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "D:\Ai draw\AotuGPT\Auto-GPT\autogpt\token_counter.py", line 25, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "D:\Ai draw\AotuGPT\lib\site-packages\tiktoken\load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Ai draw\AotuGPT\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

see again

**Comment by 12121aaaa** [comment]
> 你能具体解释一下你做了什么吗？您如何设置以及执行了哪些命令？

python -m autogpt --gpt3only
Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
GPT3.5 Only Mode: ENABLED
Welcome to Auto-GPT! Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI: For example, 'Entrepreneur-GPT'
AI Name: project analyst
project analyst here! I am at your service.
Describe your AI's role: For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
project analyst is: Analyze Industry Projects
Enter up to 5 goals for your AI: For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Analyzing Google Financial Reports
Goal 2: Save to txt text
Goal 3: close when done
Goal 4:

**Comment by Qoyyuum** [comment]
So it looks like a problem to Open AI API endpoint. Try again with a VPN? @12121aaaa

**Comment by Pwuts** [comment]
Closing as this doesn't seem to be a network issue and not an issue with Auto-GPT itself. Please start a [discussion](https://github.com/Significant-Gravitas/Auto-GPT/discussions) or ask in the [discord](https://discord.gg/autogpt) if you need more help.
