### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by xai26285** [Significant-Gravitas/Auto-GPT#1818]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "E:\autogpt\my_folder\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\autogpt\my_folder\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "E:\autogpt\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "E:\autogpt\Auto-GPT\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "E:\autogpt\Auto-GPT\autogpt\token_counter.py", line 24, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\load.py", line 115, in <dictcomp>
    return {
ValueError: not enough values to unpack (expected 2, got 1)

### Current behavior 😯

pip install --upgrade tiktoken

### Expected behavior 🤔

应该怎么做，才能运行

### Your prompt 📝

```yaml
# Paste your prompt here
```Traceback (most recent call last):
  File "E:\autogpt\my_folder\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\autogpt\my_folder\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "E:\autogpt\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "E:\autogpt\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "E:\autogpt\Auto-GPT\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "E:\autogpt\Auto-GPT\autogpt\token_counter.py", line 24, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
  File "E:\autogpt\my_folder\lib\site-packages\tiktoken\load.py", line 115, in <dictcomp>
    return {
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by XUHuAIRuOGU0231** [comment]
I also encountered the same problem, but my friend was able to use it normally, and I don't know where I went wrong

**Comment by hemangjoshi37a** [comment]
It seems like there is a ValueError: not enough values to unpack (expected 2, got 1) error in the Auto-GPT repository. The error occurs due to a missing value in the function call. To solve this issue, you can try upgrading tiktoken by running the command "pip install --upgrade tiktoken". If the issue still persists, you can try reinstalling tiktoken using "pip uninstall tiktoken" and then "pip install tiktoken". Let me know if this solves your issue.

**Comment by xai26285** [comment]
> 似乎有一个值错误：自动 GPT 存储库中没有足够的值来解压缩（预期为 2，得到 1）错误。此错误是由于函数调用中缺少值而发生的。要解决此问题，您可以尝试通过运行命令“pip install --upgrade tiktoken”来升级tiktoken。如果问题仍然存在，您可以尝试使用“pip uninstall tiktoken”和“pip install tiktoken”重新安装tiktoken。让我知道这是否解决了您的问题。
我的tiktoken已经更新了，按照你的方法已经使用了，但是还是显示同样的问题

**Comment by XUHuAIRuOGU0231** [comment]
> Auto-GPT 存储库中似乎存在 ValueError: not enough values to unpack (expected 2, got 1) 错误。该错误是由于函数调用中缺少值而发生的。要解决此问题，您可以尝试通过运行命令“pip install --upgrade tiktoken”来升级tiktoken。如果问题仍然存在，您可以尝试使用“pip uninstall tiktoken”然后“pip install tiktoken”重新安装 tiktoken。如果这能解决您的问题，请告诉我。

Your method has been used, but it is still the same error

**Comment by AhrenFullStop** [comment]
Additionally this solution wont work if you are running this in a docker container.

**Comment by RKP64** [comment]
C:\Users\91952\Auto-GPT-0.2.1> python -m autogpt
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Using memory of type:  PineconeMemory
Using Browser:  chrome
Traceback (most recent call last):
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\__main__.py", line 53, in <module>
    main()
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\agent\agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "C:\Users\91952\Auto-GPT-0.2.1\autogpt\token_counter.py", line 25, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
  File "C:\Users\91952\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\load.py", line 115, in <dictcomp>
    return {
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by RKP64** [comment]
i had the same issue since many days can anybody help to resolve this

**Comment by XUHuAIRuOGU0231** [comment]
There are no professionals to solve this problem, but I heard that it seems necessary to use a paid account for openai api. If you can upgrade your paid account, you can try it.If you solve this problem in this way, please reply to me and let me know that it is effective.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/18/2023 01:32 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Significant-Gravitas/Auto-GPT] ValueError: not enough values to unpack (expected 2, got 1) (Issue #1818) |

i had the same issue since many days can anybody help to resolve this

**Comment by bitfirefly** [comment]
> > Auto-GPT 存储库中似乎存在 ValueError: not enough values to unpack (expected 2, got 1) 错误。该错误是由于函数调用中缺少值而发生的。要解决此问题，您可以尝试通过运行命令“pip install --upgrade tiktoken”来升级tiktoken。如果问题仍然存在，您可以尝试使用“pip uninstall tiktoken”然后“pip install tiktoken”重新安装 tiktoken。如果这能解决您的问题，请告诉我。
> 
> Your method has been used, but it is still the same error

same

**Comment by bitfirefly** [comment]
my problem solved, i forgot to install git

**Comment by chairwa** [comment]
the same issue

**Comment by aChenspring** [comment]
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "D:\gpt\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 461, in <module>
    main()
  File "D:\gpt\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "D:\gpt\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 77, in chat_with_ai
    next_message_to_add_index, current_tokens_used, insertion_index, current_context = generate_context(
                                                                                       ^^^^^^^^^^^^^^^^^
  File "D:\gpt\Auto-GPT-master\Auto-GPT-master\scripts\chat.py", line 40, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gpt\Auto-GPT-master\Auto-GPT-master\scripts\token_counter.py", line 17, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
           ^
  File "D:\Program Files\Python311\Lib\site-packages\tiktoken\load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by aChenspring** [comment]
C:\Users\itcast\AppData\Local\Temp\data-gym-cache 这个位置下的文件 下载不完整 导致的 兄弟们

**Comment by XUHuAIRuOGU0231** [comment]
可以请教一下具体的解决方法吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月21日 13:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Significant-Gravitas/Auto-GPT] ValueError: not enough values to unpack (expected 2, got 1) (Issue #1818) |

C:\Users\itcast\AppData\Local\Temp\data-gym-cache 这个位置下的文件 下载不完整 导致的 兄弟们

**Comment by aChenspring** [comment]
就是https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken 这个位置下载新的文件 替换你原有的C:\Users\itcast\AppData\Local\Temp\data-gym-cache下不完整的文件

**Comment by XUHuAIRuOGU0231** [comment]
非常感谢，刚刚我删除了你提到的这个文件夹，重新用git命令下载了文件，现在这个问题已经消失了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月21日 13:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Significant-Gravitas/Auto-GPT] ValueError: not enough values to unpack (expected 2, got 1) (Issue #1818) |

就是https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken 这个位置下载新的文件 替换你原有的C:\Users\itcast\AppData\Local\Temp\data-gym-cache下不完整的文件

**Comment by yangpeng0607** [comment]
非常感谢，等了几天终于解决问题了，删除~\AppData\Local\Temp\data-gym-cache文件夹，重新运行就好了

> 就是https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken 这个位置下载新的文件 替换你原有的C:\Users\itcast\AppData\Local\Temp\data-gym-cache下不完整的文件

**Comment by ntindle** [comment]
Outside repo problem?

**Comment by Ayan-Bandyopadhyay** [comment]
I'm still running into this issue even on the latest version of tiktoken (0.3.3)

**Comment by mouzhi** [comment]
提供MAC下解决该问题的步骤：

**Comment by Jadensha** [comment]
> data-gym-cache

删除这个文件夹，确实好了

**Comment by hemangjoshi37a** [comment]
Hello everyone,

Thank you for your detailed descriptions of the issue you're facing with Auto-GPT. Based on the shared experiences, the `ValueError: not enough values to unpack (expected 2, got 1)` seems to be related to the BPE encoding files used by the `tiktoken` package. Here are some steps to potentially resolve this issue:

1. **Ensure All Dependencies are Installed**: Make sure you have all necessary dependencies installed, including `git`. The absence of `git` or other dependencies might cause problems during the installation or updating of packages.

2. **Update `tiktoken`**: Although many of you have already done this, ensure that `tiktoken` is updated to the latest version using:
   ```
   pip install --upgrade tiktoken
   ```

3. **Clear the `data-gym-cache` Directory**: It seems that an incomplete download or corrupt file in the `data-gym-cache` directory could be causing the error. Follow these steps:
   - Locate and delete the `data-gym-cache` directory. The location may vary based on your system. For example, on Windows, it might be under `C:\Users\[YourUsername]\AppData\Local\Temp\data-gym-cache`.
   - After deleting the directory, try running Auto-GPT again. It should attempt to redownload the necessary files.

4. **Manual Download of BPE File**: If the above steps don't work, you might need to manually download the correct BPE encoding file. Go to `https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken` and download the file. Replace the corresponding file in your `data-gym-cache` directory with this downloaded file.

5. **Running in a Different Environment**: If you're still facing issues, consider running Auto-GPT in a different environment, such as a Docker container or a different operating system like Ubuntu, as some users have reported success with these methods.

Please try these steps and let us know if the issue persists. Your feedback is valuable in resolving this problem.
