### ISSUE TITLE
No Module named 'Git' on Mac

### ISSUE THREAD

**Issue by PatVan77** [Significant-Gravitas/Auto-GPT#1858]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

start Autogpt from MAC Terminal (stable pull update from Github to this version

### Current behavior 😯

When starting Autogpt on MAc console it seems to default to GIT for window

HEAD Parse (ad7cefa10c0647feee85114d58559fcf83ba6743)

Code behaviour:

(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt
Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/patrickvanstokhem/Auto-GPT/autogpt/__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/patrickvanstokhem/Auto-GPT/autogpt/app.py", line 26, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "/Users/patrickvanstokhem/Auto-GPT/autogpt/commands/git_operations.py", line 2, in <module>
    import git
ModuleNotFoundError: No module named 'git'
(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt
 Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/app.py", line 26, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/commands/git_operations.py", line 2, in <module>
    import git
ModuleNotFoundError: No module named 'git'
(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt
Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/app.py", line 26, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/commands/git_operations.py", line 2, in <module>
    import git
ModuleNotFoundError: No module named 'git'

### Expected behavior 🤔

start AutoGPT

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by PatVan77** [comment]
Seems to be inconsistent. will work in VScode instance but not in Mac terminal. looking into it further

**Comment by Jun10ng** [comment]
Bcz a new PR about git ops was merged into master/v.0.2.0, it import a new package`gitpython`.

you need run `pip install -r requirements.txt` again

**Comment by JavaShipped** [comment]
I am using windows and was getting the 'no module named 'Git'' error. ran pip install requirements again and got this error at the end 

`ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\nodeenv.exe' -> 'C:\\Python311\\Scripts\\nodeenv.exe.deleteme'`
