### ISSUE TITLE
create_chat_completion raise RuntimeError

### ISSUE THREAD

**Issue by freshman-wang** [Significant-Gravitas/Auto-GPT#1873]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. create_chat_completion raise RuntimeError("Failed to get response after 5 retries") RuntimeError: Failed to get response after 5 retries

### Your prompt 📝

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\gpt\Auto-GPT-0.2.0\Auto-GPT-0.2.0\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\gpt\Auto-GPT-0.2.0\Auto-GPT-0.2.0\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\gpt\Auto-GPT-0.2.0\Auto-GPT-0.2.0\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\gpt\Auto-GPT-0.2.0\Auto-GPT-0.2.0\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\gpt\Auto-GPT-0.2.0\Auto-GPT-0.2.0\autogpt\llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

**Comment by EdBen97** [comment]
I had the same problem earlier. I fixed it by paying for the OpenAI API service and creating a new API key after the payment. This service only charges you based on the demand and is relatively cheap as long as you don't run the Auto-GPT bot on auto mode.

OpenAI API pricing model: https://openai.com/pricing

**Comment by freshman-wang** [comment]
thinks,but why the OpenAI API  default use 3.5

**Comment by Qoyyuum** [comment]
@freshman-wang because that's what they can provide. If you want GPT 4, you have to get on the waitlist. Since this issue is fixed with a paid openai account, I'll close the issue.
