### ISSUE TITLE
Auto-GPT freezes after browse_website (MacOS)

### ISSUE THREAD

**Issue by samuelfaj** [Significant-Gravitas/Auto-GPT#1878]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Name:  gpt
Role:  build a site exactly like https://getbootstrap.com/
Goals: ['web design']

### Current behavior 😯

After a browse_website command it opens my Google Chrome and freezes after Summarize chunks.

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.pcmag.com/picks/the-best-website-builders', 'question': 'What are the top-rated tools on the website builders at pcmag.com?'}
[WDM] - Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████| 8.04M/8.04M [00:07<00:00, 1.14MB/s]
Text length: 43187 characters
Summarizing chunk 1 / 6
Summarizing chunk 2 / 6
Summarizing chunk 3 / 6
Summarizing chunk 4 / 6
Summarizing chunk 5 / 6
Summarizing chunk 6 / 6
Summarized 6 chunks.

(FREEZES)

After I press Ctrl + C it begins to work again after display:

```sh
^CException ignored in: <function Service.__del__ at 0x122c2c4c0>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 190, in __del__
    self.stop()
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 151, in stop
    self.send_remote_shutdown_command()
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 130, in send_remote_shutdown_command
    request.urlopen(f"{self.service_url}/shutdown")
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
KeyboardInterrupt: 
```

### Expected behavior 🤔

It's shoulds keep working.

### Your prompt 📝

```yaml
Name:  gpt
Role:  build a site exactly like https://getbootstrap.com/
Goals: ['web design']
```

**Comment by samuelfaj** [comment]
Update: It doesn't freezes forever. But take a long time... 

I believe it falls in some timeout.
