### ISSUE TITLE
openai.error.InvalidRequestError: The API deployment for this resource does not exist.

### ISSUE THREAD

**Issue by Moss-qc** [Significant-Gravitas/Auto-GPT#1906]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

using azure instance, after command google:

PS C:\ChatGPT\Auto-GPT> python -m autogpt --gpt3only
......
NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'most profitable stocks to invest in'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ChatGPT\Auto-GPT\autogpt\__main__.py", line 53, in <module>
    main()
  File "C:\ChatGPT\Auto-GPT\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "C:\ChatGPT\Auto-GPT\autogpt\agent\agent.py", line 170, in start_interaction_loop
    self.memory.add(memory_to_add)
  File "C:\ChatGPT\Auto-GPT\autogpt\memory\local.py", line 74, in add
    embedding = create_embedding_with_ada(text)
  File "C:\ChatGPT\Auto-GPT\autogpt\llm_utils.py", line 129, in create_embedding_with_ada
    return openai.Embedding.create(
  File "C:\Users\qc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\qc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\qc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\qc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\qc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

1. I can use azure key for other apps.
2. Auto-gpt's working well if I used OpenAI key. 

### Current behavior 😯

stop

### Expected behavior 🤔

continue

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Moss-qc** [comment]
embedding_model_deployment_id: "textembeddingada002"
fixed

**Comment by OmiWakode** [comment]
@Moss-qc  how did you fix this? can you please elaborate?

**Comment by timotk** [comment]
@OmiWakode

When running on Azure, you may need to deploy the model from within Azure AI Studio's Deployments. Select "Create Deployment" and go with `text-embedding-ada-002`

This and more is described in the setup docs: https://docs.agpt.co/setup/

**Comment by zahava-ro** [comment]
> embedding_model_deployment_id: "textembeddingada002" fixed

Where does this line get added in?

**Comment by ssharm8-bdi** [comment]
I have the model deployed in azure. Where do we specify the deployment_name parameter ?
