### ISSUE TITLE
The specified device is not open or is not recognized by MCI

### ISSUE THREAD

**Issue by Cubey42** [Significant-Gravitas/Auto-GPT#217]
Error 263 for command:
        open speech.mpeg
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close speech.mpeg
    The specified device is not open or is not recognized by MCI.
Failed to close the file: speech.mpeg
Traceback (most recent call last):
  File "H:\GPT\Auto-GPT\scripts\main.py", line 275, in <module>
    prompt = construct_prompt()
  File "H:\GPT\Auto-GPT\scripts\main.py", line 164, in construct_prompt
    print_to_console(
  File "H:\GPT\Auto-GPT\scripts\main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "H:\GPT\Auto-GPT\scripts\speak.py", line 45, in say_text
    success = eleven_labs_speech(text)
  File "H:\GPT\Auto-GPT\scripts\speak.py", line 27, in eleven_labs_speech
    playsound("speech.mpeg")
  File "C:\ProgramData\Miniconda3\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\ProgramData\Miniconda3\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open speech.mpeg
    The specified device is not open or is not recognized by MCI.

when I use --speak , I've tried looking up the issue and it recommends installing playsound= 1.12 but that causes a different issue

**Comment by alexandremassaro** [comment]
I just posted a fix for it in another post
https://github.com/Torantulino/Auto-GPT/issues/219

**Comment by Explorergt92** [comment]
@Cubey42 is this still an issue for you or can this be closed?

**Comment by Qoyyuum** [comment]
Hi @Cubey42 the repo has made a lot of changes since. Please use the latest stable release and try again. If symtoms still persist, please raise another Github issue. Closing this issue for now.

**Comment by mr-f241** [comment]
i think you should add encoding='utf-8' when reading file
