### ISSUE TITLE
TypeError: bases must be types

### ISSUE THREAD

**Issue by btedev** [Significant-Gravitas/Auto-GPT#2204]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

On 8637b8b61ba18f74e88bee822222b166f17e7773

Installed successfully and was able to run `python3 -m autogpt` a couple of times. It seemed to get stuck in "thinking" for a while so I quit and went to restart with the `--debug` flag but now I get the error below. I've also tried deleting the `Auto-GPT` directory and reinstalling from scratch. Is there possibly a config or other .json file written outside of the main directory that I need to delete?

I'm on OS X Intel 13.2.1 using local memory. I've added my OpenAI key and set the browser as Safari but it gives the same error when set to Chrome. Any advice would be much appreciated.

```
 barry:  ~/dev/auto-gpt/Auto-GPT-0.2.1  python3 -m autogpt --debug
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/app.py", line 12, in <module>
    from autogpt.commands.web_requests import scrape_links, scrape_text
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/commands/web_requests.py", line 12, in <module>
    from autogpt.memory import get_memory
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/memory/__init__.py", line 17, in <module>
    from autogpt.memory.pinecone import PineconeMemory
  File "/Users/barry/dev/auto-gpt/Auto-GPT-0.2.1/autogpt/memory/pinecone.py", line 1, in <module>
    import pinecone
  File "/usr/local/lib/python3.9/site-packages/pinecone/__init__.py", line 11, in <module>
    from .core.grpc.index_grpc import *
  File "/usr/local/lib/python3.9/site-packages/pinecone/core/grpc/index_grpc.py", line 14, in <module>
    from google.protobuf import json_format
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 51, in <module>
    from google.protobuf.internal import decoder
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/internal/decoder.py", line 87, in <module>
    from google.protobuf.internal import encoder
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/internal/encoder.py", line 71, in <module>
    from google.protobuf.internal import wire_format
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

### Current behavior 😯

Stack dump shown above when launching.

### Expected behavior 🤔

Interactive console should appear.

### Your prompt 📝

`cat: last_run_ai_settings.yaml: No such file or directory`

**Comment by k-boikov** [comment]
Have you tried updating you python to 3.10 or higher? Officially 3.9 is not supported.

**Comment by btedev** [comment]
Yes, I just updated to 3.11.3 and the issue is now resolved. Thank you!
