### ISSUE TITLE
Python error after installation: ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by romandesign** [Significant-Gravitas/Auto-GPT#2230]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I installed AutoGPT 0.2.1

- Copied the code to D:\AutoGPT (Windows11)
- Run CMD, run `pip install -r requirements.txt` and it seemed to run OK
- renamed .env and entered the API key
- run `python -m autogpt` and got the error.

### Current behavior 😯

Error:
D:\Auto-GPT>python -m autogpt
Traceback (most recent call last):
  File "d:\program files\python\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "d:\program files\python\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "d:\program files\python\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Auto-GPT\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "D:\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "D:\Auto-GPT\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "D:\Auto-GPT\autogpt\app.py", line 12, in <module>
    from autogpt.commands.web_requests import scrape_links, scrape_text
  File "D:\Auto-GPT\autogpt\commands\web_requests.py", line 12, in <module>
    from autogpt.memory import get_memory
  File "D:\Auto-GPT\autogpt\memory\__init__.py", line 1, in <module>
    from autogpt.memory.local import LocalCache
  File "D:\Auto-GPT\autogpt\memory\local.py", line 7, in <module>
    import numpy as np
  File "d:\program files\python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "d:\program files\python\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "d:\program files\python\python.exe"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

### Expected behavior 🤔

no error

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
Try upgrading numpy by running
` pip install numpy --upgrade`

**Comment by troymroberts** [comment]
Weirdly enough. Try installing the latest Visual C++ Redistribuatble

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
