### ISSUE TITLE
Updated my Auto GPT today after using for about a week and seeing a lot of changes. After input of goals receiving the following: 

### ISSUE THREAD

**Issue by Dnorth0x** [Significant-Gravitas/Auto-GPT#2283]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Unsure, updated my .env as well as ran the pip requirments.

### Current behavior 😯

Traceback (most recent call last):
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\Auto-GPT-master\autogpt\__main__.py", line 53, in <module>
    main()
  File "C:\ai\Auto-GPT-master\autogpt\__main__.py", line 36, in main
    memory = get_memory(cfg, init=True)
  File "C:\ai\Auto-GPT-master\autogpt\memory\__init__.py", line 52, in get_memory
    memory.clear()
  File "C:\ai\Auto-GPT-master\autogpt\memory\pinecone.py", line 58, in clear
    self.index.delete(deleteAll=True)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\index.py", line 329, in delete
    return self._vector_api.delete(
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 222, in request
    raise ForbiddenException(http_resp=r)
pinecone.core.client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Tue, 18 Apr 2023 01:31:56 GMT', 'server': 'envoy'})

### Expected behavior 🤔

Normally would run after goal input no issue. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Are your Pinecone settings valid?

**Comment by ntindle** [comment]
Tell us a bit more about your setup

**Comment by ntindle** [comment]
Reset up from scratch. Lots of changes have been made
