### ISSUE TITLE
pyo3_runtime.PanicException: assertion failed: encoder.len() == decoder.len()

### ISSUE THREAD

**Issue by zhang4014439175** [Significant-Gravitas/Auto-GPT#2377]
thread '<unnamed>' panicked at 'assertion failed: encoder.len() == decoder.len()', src/lib.rs:458:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/env1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/__main__.py", line 53, in <module>
    main()
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/agent/agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/chat.py", line 95, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/chat.py", line 43, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/autogpt/token_counter.py", line 25, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/venv/lib/python3.10/site-packages/tiktoken/model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/venv/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/Users/mac/Desktop/JAVA/文档/AI/Auto-GPT-0.2.1/venv/lib/python3.10/site-packages/tiktoken/core.py", line 50, in __init__
    self._core_bpe = _tiktoken.CoreBPE(mergeable_ranks, special_tokens, pat_str)
pyo3_runtime.PanicException: assertion failed: encoder.len() == decoder.len()

**Comment by k-boikov** [comment]
Please follow the Bug report template and post your setup and prompt.

**Comment by Pwuts** [comment]
@k-boikov said it

**Comment by Pwuts** [comment]
Multi-byte encoding issues: #232
