### ISSUE TITLE
Milvus connection timeout

### ISSUE THREAD

**Issue by Rithox** [Significant-Gravitas/Auto-GPT#2393]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

E:\IA\AutoGPT\Auto-GPT-0.2.1>python -m autogpt
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\pymilvus\client\grpc_handler.py", line 114, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_utilities.py", line 151, in result
    self._block(timeout)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_utilities.py", line 97, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\app.py", line 12, in <module>
    from autogpt.commands.web_requests import scrape_links, scrape_text
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\commands\web_requests.py", line 16, in <module>
    memory = get_memory(CFG)
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\memory\__init__.py", line 70, in get_memory
    memory = MilvusMemory(cfg)
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\config\singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "E:\IA\AutoGPT\Auto-GPT-0.2.1\autogpt\memory\milvus.py", line 23, in __init__
    connections.connect(address=cfg.milvus_addr)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\pymilvus\orm\connections.py", line 303, in connect
    connect_milvus(**kwargs, user=user, password=password)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\pymilvus\orm\connections.py", line 274, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\pymilvus\client\grpc_handler.py", line 117, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-387603fe41c3088.gcp-us-west1.vectordb.zillizcloud.com:443. Timeout)>

### Expected behavior 🤔

Hi, I've set up all requirement and API needed but seems having problem when trying to start autogpt
Can someone help me please

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
Seems lime a milvus issue, check your MILVUS_ADDR in .env.

**Comment by dfatih** [comment]
well i can start it now but still have this output:
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'

**Comment by k-boikov** [comment]
Ensure that git is in PATH and restart your OS.

**Comment by Pwuts** [comment]
`Fail connecting to server on in01-387603fe41c3088.gcp-us-west1.vectordb.zillizcloud.com:443. Timeout`

Seems to be a networking or config issue.

**Comment by Rithox** [comment]
> Ensure that git is in PATH and restart your OS.

This solves the issue, git environment was already set up, I've missed the reboot part. Great thanks @k-boikov
