### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' (D:\Phan mem\Python\Lib\site-packages\PIL\__init__.py)

### ISSUE THREAD

**Issue by buingochieumc7** [Significant-Gravitas/Auto-GPT#2532]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

It displays an error instead of expecting.

### Expected behavior 🤔

It should run normally.

### Your prompt 📝

run.bat

### Your Logs 📒

All packages are installed.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Phan mem\Auto-GPT-0.2.1\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "D:\Phan mem\Auto-GPT-0.2.1\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "D:\Phan mem\Auto-GPT-0.2.1\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "D:\Phan mem\Auto-GPT-0.2.1\autogpt\app.py", line 10, in <module>
    from autogpt.commands.image_gen import generate_image
  File "D:\Phan mem\Auto-GPT-0.2.1\autogpt\commands\image_gen.py", line 9, in <module>
    from PIL import Image
  File "D:\Phan mem\Python\Lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (D:\Phan mem\Python\Lib\site-packages\PIL\__init__.py)

**Comment by k-boikov** [comment]
Your Pillow seems broken. What is you python version an what is the output of "pip show Pillow"?
