### ISSUE TITLE
chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by cuchorapido** [Significant-Gravitas/Auto-GPT#2543]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

from the `stable` branch run:

python -m autogpt --continuous

### Current behavior 😯
**It works for the first google search command then breaks on every browse_website command...**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/new/20230419/stable/Auto-GPT/autogpt/__main__.py", line 53, in <module>
    main()
  File "/opt/new/20230419/stable/Auto-GPT/autogpt/__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "/opt/new/20230419/stable/Auto-GPT/autogpt/agent/agent.py", line 170, in start_interaction_loop
    self.memory.add(memory_to_add)
  File "/opt/new/20230419/stable/Auto-GPT/autogpt/memory/local.py", line 76, in add
    embedding = create_embedding_with_ada(text)
  File "/opt/new/20230419/stable/Auto-GPT/autogpt/llm_utils.py", line 137, in create_embedding_with_ada
    return openai.Embedding.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 5f823ad4f7fa32fef3537abb5df043fd in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 5f823ad4f7fa32fef3537abb5df043fd in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
openai.error.APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 76402fabc6ec...68de061f87c1fbd4e in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 76402fabc6ecd...8de061f87c1fbd4e in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 76402fabc6ecd...8de061f87c1fbd4e in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 19 Apr 2023 14:29:39 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-organization': 'user-1vmy57r7jcupi0me52k50qgf', 'openai-processing-ms': '30019', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3000', 'x-ratelimit-remaining-requests': '2999', 'x-ratelimit-reset-requests': '20ms', 'x-request-id': '76402fabc6ecde468de061f87c1fbd4e', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ba5d68dfe3b6dcb-MIA', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
```

### Expected behavior 🤔

run smoothly

### Your prompt 📝

```yaml
ai_goals:
- Recopilar información difamatoria de un streamer en línea.
- Evaluar si el contenido cumple con los criterios legales de difamación.
- Identificar conexiones, patrones e intenciones en las acciones de un streamer.
- Documentar y organizar pruebas de manera accesible y legalmente admisible.
- Establecer un caso sólido para iniciar un proceso legal por difamación y apagate.
ai_name: cuchcorapido-gpt
ai_role: un ai encargado de extractraer toda la informacion incriminante sobre un streamer para entabler un caso legal por difamacion en español
```

### Your Logs 📒

```
 Command browse_website returned: Error: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127
```

**Comment by aevfly** [comment]
what's version of chrome do you have ? (not a chromedriver)

**Comment by Pwuts** [comment]
This should be resolved in `master`. If not, feel free to reopen.

**Comment by vmajor** [comment]
I still get exit with error 127 in both master and stable and with the individual pr installed

**Comment by Pwuts** [comment]
@vmajor what device/platform/Auto-GPT version/python version are you on?

**Comment by vmajor** [comment]
Python 3.10.9
gpt-3.5-turbo

**Comment by Pwuts** [comment]
Thanks. Can you also post a full log from `browse_website` up until `chromedriver unexpectedly exited`?

**Comment by vmajor** [comment]
There is no such entry. 

error.log is empty, activity.log is not informative and only shows that the process exited.

2023-04-20 20:03:00,349 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
2023-04-20 20:03:07,305 INFO SYSTEM:  Command browse_website returned: Error: Message: Process unexpectedly closed with status 1

How do I enable error logging?

As an aside, Auto-GPT works with firefox under Windows, but is much slower for some reason. I do not have chrome installed to try it.

**Comment by vmajor** [comment]
I just tested it in windows with chrome, and there is no error. The chrome exiting error is linux specific.

This is unfortunate because under windows Auto-GPT does not work reliably when file output is required. In the current task it is stuck in a failure loop trying to set output directory using linux path finding environment syntax (wrongly) 

`mkdir -p /path/to/local/directory`

PowerShell would accept the  forward slashes fine if Auto-GPT would give up trying to use this particular method, but it is not.

**Comment by karbassi** [comment]
I'm having the same issue on macOS via docker.

**Comment by OmarHory** [comment]
Same issue on Linux without docker.

**Comment by methuz** [comment]
Same issue on WSL2 Ubuntu

**Comment by Pwuts** [comment]
@karbassi see #2600

**Comment by Pwuts** [comment]
It seems that even simple things can throw really ugly errors:

URL = `barrel-roll.com`
```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'barrel-roll.com', 'question': 'How to execute a barrel roll'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
[WDM] - Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████| 6.75M/6.75M [00:01<00:00, 6.44MB/s]
SYSTEM:  Command browse_website returned: Error: Message: invalid argument (Session info: headless chrome=112.0.5615.138)
Stacktrace:
#0 0x56413e60afe3 <unknown> #1 0x56413e349bc1 <unknown> #2 0x56413e334446 <unknown>
#3 0x56413e3327f3 <unknown> #4 0x56413e332c3d <unknown> #5 0x56413e34bb16 <unknown>
#6 0x56413e3c08c5 <unknown> #7 0x56413e3a78c2 <unknown> #8 0x56413e3c0232 <unknown>
#9 0x56413e3a7693 <unknown> #10 0x56413e37a03a <unknown> #11 0x56413e37b17e <unknown>
#12 0x56413e5ccdbd <unknown> #13 0x56413e5d0c6c <unknown> #14 0x56413e5da4b0 <unknown>
#15 0x56413e5d1d63 <unknown> #16 0x56413e5a4c35 <unknown> #17 0x56413e5f5138 <unknown>
#18 0x56413e5f52c7 <unknown> #19 0x56413e603093 <unknown> #20 0x7fa787a00ea7 start_thread
```

Connection error:
```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://barrel-roll.com', 'question': "Can this website help me achieve the user's goal?"}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
[WDM] - Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████| 6.75M/6.75M [00:01<00:00, 6.20MB/s]
SYSTEM:  Command browse_website returned: Error: Message: unknown error: net::ERR_CONNECTION_CLOSED (Session info: headless chrome=112.0.5615.138)
Stacktrace:
#0 0x561c26ed8fe3 <unknown> #1 0x561c26c17d36 <unknown> #2 0x561c26c0fcd8 <unknown>
#3 0x561c26c02862 <unknown> #4 0x561c26c03f72 <unknown> #5 0x561c26c02c2a <unknown>
#6 0x561c26c01cf8 <unknown> #7 0x561c26c01b30 <unknown> #8 0x561c26c00608 <unknown>
#9 0x561c26c00c3d <unknown> #10 0x561c26c19b16 <unknown> #11 0x561c26c8e8c5 <unknown>
#12 0x561c26c758c2 <unknown> #13 0x561c26c8e232 <unknown> #14 0x561c26c75693 <unknown>
#15 0x561c26c4803a <unknown> #16 0x561c26c4917e <unknown> #17 0x561c26e9adbd <unknown>
#18 0x561c26e9ec6c <unknown> #19 0x561c26ea84b0 <unknown> #20 0x561c26e9fd63 <unknown>
#21 0x561c26e72c35 <unknown> #22 0x561c26ec3138 <unknown> #23 0x561c26ec32c7 <unknown>
#24 0x561c26ed1093 <unknown> #25 0x7fcdddaeaea7 start_thread
```

**Comment by Samael27** [comment]
Same issue on debian no docker on stable version, I didn't try the master one yet.

**Comment by rbucks** [comment]
Here's what I get. Running on docker. 
``` THOUGHTS:  I will use the 'browse_website' command to look at the websites of the conferences listed in the search results to determine which ones are related to www.shovels.ai. I will also use the 'google' command to search for companies related to www.shovels.ai and see if they are attending or sponsoring any of the conferences.
REASONING:  Browsing the websites of the conferences will give me more information about them and help me determine if they are related to www.shovels.ai. Searching for companies related to www.shovels.ai and seeing if they are attending or sponsoring any of the conferences will help me find conferences that are relevant to www.shovels.ai.
PLAN: 
-  Use the 'browse_website' command to look at the websites of the conferences listed in the search results to determine which ones are related to www.shovels.ai
-  Use the 'google' command to search for companies related to www.shovels.ai and see if they are attending or sponsoring any of the conferences
CRITICISM:  I need to ensure that the websites I am browsing are up-to-date and that the companies I find are relevant to www.shovels.ai.
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.forbes.com/sites/qai/2023/02/20/top-ai-conferences-2023-roundup-of-top-ai-conferences/', 'question': 'What conferences listed on this page are related to www.shovels.ai?'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command browse_website returned: Error: Message: Service /home/appuser/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 255```

**Comment by Pwuts** [comment]
@rbucks please provide info about the device/platform you're running it on

**Comment by ebauch** [comment]
```
Command browse_website returned: Error: Message: Service /home/appuser/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 255
```

Same issue on Apple M2 Max 2023/Mac OS Ventura 13.2 with the most recent git repo pull and docker build. Tried to follow the workarounds described at https://github.com/Significant-Gravitas/Auto-GPT/issues/1641 but 
1. I can't install google-chrome-stable for some reason (the repo doesn't seem to support it)
2. The additional options seem to be all already set in function _scrape_text_with_selenium_ in the web_selenium.py file.

**Comment by Pwuts** [comment]
@ebauch it's an issue with the `webdriver-manager`, which seems to incorrectly identify the platform and then downloads the wrong driver. We fixed it by using the `chromium-driver` that is installed in the docker image. @jcalderonzumba figured that out for us :)
