### ISSUE TITLE
Redis connection won't work even though it's running and configured correctly

### ISSUE THREAD

**Issue by W01v3n** [Significant-Gravitas/Auto-GPT#2581]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

`python -m autogpt --speak --gpt3only`

### Current behavior 😯

It says Redis isn't installed, but it is, including python required dependencies, I even installed the required version.
Redis is installed and running and I configured everything correctly in the .env, it just won't connect.
In addition, you can see it complains about _gi, which enables it to speak, but that won't work either and it fails.

Before you tell me to run the docker stack, I tried, and as I thought it didn't change a thing, both are still the same Redis after all..

```
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
WARNING:  You are running on `master` branch - this is not a supported branch.
Welcome back!  Would you like me to return to being Bella?
Continue with the last settings?
Name:  Bella
Role:  an AI designed to help me make additional incomes with the goal of increasing my net worth.
Goals: ['Increase net worth', 'Help me with my life and tasks and serve me as good as possible', 'Make my life easier.', 'Develop successful businesses and manage them autonomously', 'Think of the easiest, most profitable and high potential ways to make money that can be automated and with almost no human work required']
Continue (y/n): Exception in thread Thread-1 (speak):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/say.py", line 33, in speak
    success = VOICE_ENGINE.say(text, voice_index)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/base.py", line 33, in say
    return self._speech(text, voice_index)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/eleven_labs.py", line 80, in _speech
    playsound("speech.mpeg", True)
  File "/home/w01v3n/.local/lib/python3.10/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)

```

### Expected behavior 🤔

That it will work without errors or warnings, Redis to be connected, and speak function would work as well.

### Your prompt 📝

```yaml
# Paste your prompt here
```
No prompt yet even, it starts out like this

### Your Logs 📒

```log
2023-04-19 21:50:53,394 INFO Speak Mode:  ENABLED
2023-04-19 21:50:53,535 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:50:53,935 INFO NEWS:   ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:50:54,498 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:50:54,763 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:07,448 INFO Speak Mode:  ENABLED
2023-04-19 21:52:07,586 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:52:07,911 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:52:08,425 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:52:08,711 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:49,726 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:52:50,430 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:52:50,945 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:52:51,296 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:51,491 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-04-19 21:52:51,843 INFO Name your AI:  For example, 'Entrepreneur-GPT'
2023-04-19 21:55:20,331 INFO Speak Mode:  ENABLED
2023-04-19 21:55:20,457 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:55:20,804 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:55:21,281 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:55:21,601 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:58:18,396 INFO Speak Mode:  ENABLED
2023-04-19 21:58:18,515 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:58:18,911 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:58:19,503 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:58:19,820 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:58:28,403 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-04-19 21:58:28,861 INFO Name your AI:  For example, 'Entrepreneur-GPT'
2023-04-19 21:59:06,497 INFO Bella here! I am at your service.
2023-04-19 21:59:06,652 INFO Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
2023-04-19 22:00:39,475 INFO Enter up to 5 goals for your AI:  For example: 
Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
2023-04-19 22:03:58,497 INFO Using memory of type: LocalCache
2023-04-19 22:03:58,659 INFO Using Browser: chrome
2023-04-19 22:04:23,663 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:04:24,262 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:04:24,851 INFO PLAN: 
2023-04-19 22:04:24,890 INFO -  Brainstorm potential business ideas
2023-04-19 22:04:25,052 INFO -  Research market demand and competition for each idea
2023-04-19 22:04:25,322 INFO -  Determine feasibility and profitability of each idea
2023-04-19 22:04:25,599 INFO -  Automate tasks to reduce costs and increase efficiency
2023-04-19 22:04:25,826 INFO CRITICISM: We need to ensure that we are not limiting ourselves to only ideas that align with your current interests and skills. It is important to consider new and emerging industries that may have high potential for growth and profitability. Additionally, we need to be cautious of over-automation, as it may lead to a lack of personal touch and customer satisfaction.
2023-04-19 22:04:54,052 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:05:35,985 INFO SYSTEM:  Human feedback: Can you use redis instead of localcache?
2023-04-19 22:05:46,861 INFO  THOUGHTS: I am not sure what you are referring to. Can you please provide more context or information about the use case for Redis and LocalCache?
2023-04-19 22:05:47,331 INFO REASONING: As an AI, I need to understand the context and purpose of the request in order to provide an appropriate response. By asking for more information, I can better understand the situation and provide a more helpful response.
2023-04-19 22:05:47,875 INFO PLAN: 
2023-04-19 22:05:47,947 INFO -  Ask for more information to better understand the situation
2023-04-19 22:05:48,224 INFO CRITICISM: None
2023-04-19 22:05:58,838 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:10:36,687 INFO Speak Mode:  ENABLED
2023-04-19 22:10:37,036 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:10:37,494 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:10:37,855 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:10:50,176 INFO Using memory of type: LocalCache
2023-04-19 22:10:50,363 INFO Using Browser: chrome
2023-04-19 22:11:09,409 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:11:10,038 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:11:10,707 INFO PLAN: 
2023-04-19 22:11:10,758 INFO -  Brainstorm potential business ideas
2023-04-19 22:11:10,909 INFO -  Research market demand and competition for each idea
2023-04-19 22:11:11,105 INFO -  Determine feasibility and profitability of each idea
2023-04-19 22:11:11,290 INFO -  Automate tasks to reduce costs and increase efficiency
2023-04-19 22:11:11,524 INFO CRITICISM: I need to ensure that I am considering a wide range of potential business ideas and not limiting myself to a narrow set of options. Additionally, I need to be mindful of the potential risks and challenges associated with each idea and develop contingency plans to address them.
2023-04-19 22:11:39,311 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:13:34,805 INFO Speak Mode:  ENABLED
2023-04-19 22:13:35,124 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:13:35,622 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:13:35,926 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:13:41,195 INFO Using memory of type: RedisMemory
2023-04-19 22:13:41,407 INFO Using Browser: chrome
2023-04-19 22:14:47,911 INFO Speak Mode:  ENABLED
2023-04-19 22:14:48,014 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:14:48,439 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:14:48,948 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:14:49,251 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:15:01,646 INFO Using memory of type: LocalCache
2023-04-19 22:15:01,782 INFO Using Browser: chrome
2023-04-19 22:15:20,313 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:15:20,873 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:15:21,447 INFO PLAN: 
2023-04-19 22:15:21,516 INFO -  Brainstorm potential business ideas
2023-04-19 22:15:21,645 INFO -  Research market demand and competition for each idea
2023-04-19 22:15:21,859 INFO -  Identify the most profitable and feasible options
2023-04-19 22:15:22,058 INFO -  Consider automating tasks to reduce costs and increase efficiency
2023-04-19 22:15:22,331 INFO CRITICISM: I need to ensure that the business ideas we pursue are legal and ethical, and that the automation of tasks does not compromise quality or customer satisfaction.
2023-04-19 22:15:51,046 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:18:03,086 INFO Speak Mode:  ENABLED
2023-04-19 22:18:03,179 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:18:03,527 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:18:03,954 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:18:04,278 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:20:18,425 INFO Speak Mode:  ENABLED
2023-04-19 22:20:18,556 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:20:19,068 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:20:19,571 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:20:19,913 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:21:23,512 INFO Speak Mode:  ENABLED
2023-04-19 22:21:23,643 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:21:23,975 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:21:24,487 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:21:24,778 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:29:58,058 INFO Speak Mode:  ENABLED
2023-04-19 22:29:58,142 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:29:58,495 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:29:59,071 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:29:59,412 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:32:50,568 INFO Speak Mode:  ENABLED
2023-04-19 22:32:50,679 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:32:51,059 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:32:51,546 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:32:51,872 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:34:58,227 INFO Speak Mode:  ENABLED
2023-04-19 22:34:58,334 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:34:58,646 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:34:59,120 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:34:59,371 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:36:34,757 INFO Speak Mode:  ENABLED
2023-04-19 22:36:34,847 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:36:35,657 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:36:36,173 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:36:36,447 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:36:39,691 INFO Using memory of type: LocalCache
2023-04-19 22:36:39,825 INFO Using Browser: chrome
2023-04-19 22:37:16,583 INFO Speak Mode:  ENABLED
2023-04-19 22:37:16,697 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:37:17,056 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:37:17,588 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:37:17,942 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:37:24,541 INFO Using memory of type: LocalCache
2023-04-19 22:37:24,733 INFO Using Browser: chrome
2023-04-19 22:40:24,202 INFO Speak Mode:  ENABLED
2023-04-19 22:40:24,326 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:40:24,686 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:40:25,216 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:40:25,528 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:40:31,767 INFO Speak Mode:  ENABLED
2023-04-19 22:40:32,096 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:40:32,599 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:42:50,107 INFO Speak Mode:  ENABLED
2023-04-19 22:42:50,226 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:42:50,612 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:42:51,153 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:42:51,536 INFO Welcome back!  Would you like me to return to being Bella?

```

**Comment by ntindle** [comment]
run `python -m pip list` and reply the results please

**Comment by W01v3n** [comment]
> run `python -m pip list` and reply the results please

Ok, quite a long one:
```
Package                  Version
------------------------ ------------
aiohttp                  3.8.4
aiosignal                1.3.1
apturl                   0.5.2
async-generator          1.10
async-timeout            4.0.2
asynctest                0.13.0
attrs                    23.1.0
Babel                    2.10.3
bcrypt                   3.1.7
beautifulsoup4           4.11.1
black                    23.3.0
blinker                  1.4
Brlapi                   0.7.0
bs4                      0.0.1
cachetools               4.0.0
cairocffi                0.9.0
certifi                  2022.12.7
cffi                     1.14.0
cfgv                     3.3.1
chardet                  3.0.4
charset-normalizer       3.1.0
chrome-gnome-shell       0.0.0
click                    8.1.3
colorama                 0.4.6
command-not-found        0.3
commonmark               0.9.1
coverage                 7.2.3
cryptography             2.8
cssselect                1.2.0
cupshelpers              1.0
cycler                   0.10.0
dbus-python              1.2.16
defer                    1.0.6
distlib                  0.3.6
distro                   1.4.0
distro-info              0.23ubuntu1
dnspython                2.3.0
docker                   6.0.1
duckduckgo-search        2.8.6
duplicity                0.8.12.0
entrypoints              0.3
exceptiongroup           1.1.1
fasteners                0.14.1
filelock                 3.8.0
flake8                   6.0.0
folder-color-common      0.0.88
frozenlist               1.3.3
future                   0.18.2
gitdb                    4.0.10
GitPython                3.1.31
google-api-python-client 1.7.11
google-auth              1.5.1
google-auth-httplib2     0.0.3
gTTS                     2.3.1
h11                      0.14.0
hiredis                  2.2.2
httplib2                 0.14.0
huggingface-hub          0.9.1
identify                 2.5.22
idna                     2.8
iniconfig                2.0.0
isort                    5.12.0
Jinja2                   2.10.1
joblib                   1.1.0
jsonschema               4.17.3
kazam                    1.4.5
keyring                  18.0.1
kiwisolver               1.0.1
language-selector        0.1
launchpadlib             1.10.13
lazr.restfulclient       0.14.2
lazr.uri                 1.0.3
lockfile                 0.12.2
loguru                   0.7.0
louis                    3.12.0
lxml                     4.9.2
macaroonbakery           1.3.1
Mako                     1.1.0
MarkupSafe               1.1.0
matplotlib               3.1.2
mccabe                   0.7.0
monotonic                1.5
multidict                6.0.4
mypy-extensions          1.0.0
mysql-connector-python   8.0.31
netifaces                0.10.4
nltk                     3.7
nodeenv                  1.7.0
nose                     1.3.7
numpy                    1.23.3
oauth2client             4.1.2
oauthlib                 3.2.2
olefile                  0.46
openai                   0.27.2
orjson                   3.8.10
outcome                  1.2.0
packaging                23.1
paramiko                 2.6.0
pathspec                 0.11.1
pexpect                  4.6.0
Pillow                   9.5.0
pinecone-client          2.2.1
pip                      23.1
platformdirs             3.2.0
playsound                1.2.2
pluggy                   1.0.0
ply                      3.11
pre-commit               3.2.2
protobuf                 3.20.1
proton-client            0.7.1
protonvpn-cli            3.13.0
protonvpn-gui            1.11.0
protonvpn-nm-lib         3.13.0
psutil                   5.5.1
py-cpuinfo               9.0.0
pyasn1                   0.4.2
pyasn1-modules           0.2.1
pycairo                  1.16.2
pycodestyle              2.10.0
pycparser                2.19
pycups                   1.9.73
PyDrive                  1.3.1
pyflakes                 3.0.1
Pygments                 2.12.0
PyGObject                3.36.0
PyJWT                    1.7.1
pymacaroons              0.13.0
PyNaCl                   1.3.0
pyOpenSSL                19.0.0
pyparsing                3.0.9
PyQt5                    5.14.1
pyRFC3339                1.1
pyrsistent               0.19.3
PySocks                  1.7.1
pytest                   7.3.1
pytest-asyncio           0.21.0
pytest-benchmark         4.0.0
pytest-cov               4.0.0
pytest-integration       0.2.3
pytest-mock              3.10.0
python-apt               2.0.1+zorin1
python-dateutil          2.7.3
python-debian            0.1.49
python-dotenv            1.0.0
python-gnupg             0.4.5
pythondialog             3.4.0
pytz                     2019.3
pyxdg                    0.26
PyYAML                   6.0
readability-lxml         0.8.1
redis                    3.5.3
redisearch               2.1.1
regex                    2022.8.17
rejson                   0.5.6
reportlab                3.5.34
requests                 2.28.2
requests-oauthlib        1.3.1
requests-unixsocket      0.2.0
rich                     12.5.1
rsa                      4.0
sacremoses               0.0.53
screen-resolution-extra  0.0.0
SecretStorage            2.3.1
selenium                 4.8.3
sentencepiece            0.1.97
setuptools               45.2.0
simplejson               3.16.0
sip                      4.19.21
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.3.2.post1
SQLAlchemy               1.3.12
ssh-import-id            5.10
systemd-python           234
termcolor                2.1.1
textblob                 0.17.1
tiktoken                 0.3.3
tokenizers               0.12.1
tomli                    2.0.1
tqdm                     4.64.1
transformers             4.21.3
trio                     0.22.0
trio-websocket           0.10.2
tweepy                   4.13.0
typer                    0.4.2
typing_extensions        4.3.0
ubuntu-drivers-common    0.0.0
ufw                      0.36
unattended-upgrades      0.1
uritemplate              0.6
urllib3                  1.26.15
vboxapi                  1.0
virtualenv               20.21.0
wadllib                  1.3.3
webdriver-manager        3.8.6
websocket-client         1.5.1
wheel                    0.34.2
wsproto                  1.2.0
wxPython                 4.0.7
xcffib                   0.8.1
xkit                     0.0.0
yarl                     1.8.2
zorin-appearance         4.1
zorin-connect            1.2
zorin-exec-guard         1.5

```

**Comment by ntindle** [comment]
Whelp, no idea from my side. Hope someone else can help

**Comment by nachobuey** [comment]
'WARNING:  You are running on `master` branch - this is not a supported branch.'

**Comment by ntindle** [comment]
Checkout the stable version via git or download it here: [latest stable release](https://github.com/Significant-Gravitas/Auto-GPT/releases/latest)

**Comment by W01v3n** [comment]
> Contributor

Still no dice, I setup from scratch and still the very same errors:
```
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
Welcome to Auto-GPT!  run with '--help' for more information.
Exception in thread Thread-1 (speak):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w01v3n/Downloads/Auto-GPT-0.2.2/autogpt/speech/say.py", line 33, in speak
    success = VOICE_ENGINE.say(text, voice_index)
  File "/home/w01v3n/Downloads/Auto-GPT-0.2.2/autogpt/speech/base.py", line 33, in say
    return self._speech(text, voice_index)
  File "/home/w01v3n/Downloads/Auto-GPT-0.2.2/autogpt/speech/eleven_labs.py", line 80, in _speech
    playsound("speech.mpeg", True)
  File "/home/w01v3n/.local/lib/python3.10/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)

```

**Comment by theSkele** [comment]
why was this closed? what was the solution

**Comment by W01v3n** [comment]
> why was this closed? what was the solution

Good question, I don't remember closing it, it still doesn't work!

**Comment by W01v3n** [comment]
> Checkout the stable version via git or download it here: [latest stable release](https://github.com/Significant-Gravitas/Auto-GPT/releases/latest)

Hello??? This didn't solve the problem as I described, why did you close the issue??
