### ISSUE TITLE
The SSL/TLS handshake failed. Procedure

### ISSUE THREAD

**Issue by 666-shit** [Significant-Gravitas/Auto-GPT#2608]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11279117/activity.log)

### Current behavior 😯

When I use autogpt, he visits the Google search engine and gives an error message：
```
Traceback (most recent call last):
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
network    raise MaxRetryError(_pool, url, error or ResponseError(cause))
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.elevenlabs.io', port=443): Max retries exceeded with url: /v1/text-to-speech/EXAVITQu4vr4xnSDxMaL (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AutoGPT\autogpt\speech\say.py", line 34, in speak
    success = VOICE_ENGINE.say(text, voice_index)
  File "D:\AutoGPT\autogpt\speech\base.py", line 33, in say
    return self._speech(text, voice_index)
  File "D:\AutoGPT\autogpt\speech\eleven_labs.py", line 75, in _speech
    response = requests.post(tts_url, headers=self._headers, json={"text": text})
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\c1533\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.elevenlabs.io', port=443): Max retries exceeded with url: /v1/text-to-speech/EXAVITQu4vr4xnSDxMaL (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
programming in Python?'}
```
I then typed y as normal and it opened chrome for a search and returned the following error message：
```
D:\AutoGPT\autogpt\commands\web_selenium.py:79: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(

DevTools listening on ws://127.0.0.1:4262/devtools/browser/ddb22f67-dc6e-445a-a058-bc5405b041af
[21876:22504:0420/094339.536:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
[21876:22504:0420/094339.537:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
[21876:22504:0420/094339.538:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
...
D:\AutoGPT\autogpt\commands\web_selenium.py:143: ResourceWarning: unclosed file <_io.TextIOWrapper name='D:\\AutoGPT\\autogpt/js/overlay.js' mode='r' encoding='cp936'>
  driver.execute_script(open(f"{FILE_DIR}/js/overlay.js", "r").read())
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Text length: 3054 characters
Adding chunk 1 / 1 to memory
[21392:22016:0420/094343.625:ERROR:device_event_log_impl.cc(222)] [09:43:43.625] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[21876:22504:0420/094344.528:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
[21876:22504:0420/094344.529:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
Summarizing chunk 1 / 1
[21876:22504:0420/094346.632:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
[21876:22504:0420/094346.634:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -100
...
Added chunk 1 summary to memory
Summarized 1 chunks.
```
This appears to be an invalid SSL certificate. How can I resolve this problem?

### Expected behavior 🤔

This error is usually caused by a failed SSL/TLS handshake. The possible causes are certificate verification failure, incompatible protocol versions, unsupported password suites, or incorrect server configurations. I hope it can access the website normally

### Your prompt 📝

```yaml
ai_goals:
- You can use python for network programming
- Construct an xss attack script that gets user cookies
- Using python programming, scripting dvwa, and get user cookies
ai_name: neko
ai_role: An artificial intelligence designed to independently develop python programs,
  its goal is to help me write python programs and help me learn.

```

### Your Logs 📒

[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11279103/activity.log)
[error.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11279104/error.log)

**Comment by ntindle** [comment]
Are you using a proxy?

**Comment by 666-shit** [comment]
> Are you using a proxy?

Yes, but if I quit the proxy, I can't even download autogpt or access many websites such as Google. Will the proxy affect the normal operation of autogpt?

**Comment by ntindle** [comment]
Yes, currently, proxy support is limited. See if  #1275 helps
