### ISSUE TITLE
Missing imports: plugins.py

### ISSUE THREAD

**Issue by itsureis** [Significant-Gravitas/Auto-GPT#2650]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

docker-compose run --build --rm auto-gpt

### Current behavior 😯

 File "/home/appuser/autogpt/plugins.py", line 12, in <module>
    import openapi_python_client
ModuleNotFoundError: No module named 'openapi_python_client'

Also, other missing modules in plugins.py

import openapi_python_client
import requests
from auto_gpt_plugin_template import AutoGPTPluginTemplate
from openapi_python_client.cli import Config as OpenAPIConfig

from autogpt.config import Config
from autogpt.models.base_open_ai_plugin import BaseOpenAIPlugin

### Expected behavior 🤔

run auto-gtp

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

D:\Alt C drive\AutoGPT\Auto-GPT>docker-compose run --build --rm auto-gpt
[+] Running 1/0
 ✔ Container auto-gpt-redis-1  Running                                                                             0.0s
[+] Building 3.0s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                2.1s
 => [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c235d6a65e  0.0s
 => [internal] load build context                                                                                  0.3s
 => => transferring context: 3.65kB                                                                                0.0s
 => CACHED [ 2/11] RUN apt-get -y update                                                                           0.0s
 => CACHED [ 3/11] RUN apt-get -y install git chromium-driver                                                      0.0s
 => CACHED [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11   0.0s
 => CACHED [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   0.0s
 => CACHED [ 6/11] RUN useradd --create-home appuser                                                               0.0s
 => CACHED [ 7/11] WORKDIR /home/appuser                                                                           0.0s
 => CACHED [ 8/11] RUN chown appuser:appuser /home/appuser                                                         0.0s
 => CACHED [ 9/11] COPY --chown=appuser:appuser requirements.txt .                                                 0.0s
 => CACHED [10/11] RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements  0.0s
 => [11/11] COPY --chown=appuser:appuser autogpt/ ./autogpt                                                        0.2s
 => exporting to image                                                                                             0.2s
 => => exporting layers                                                                                            0.2s
 => => writing image sha256:0ad08ddd36a507a83bc4a8c0c0412097f24705dd92395390ea1525adf709f949                       0.0s
 => => naming to docker.io/library/auto-gpt-auto-gpt                                                               0.0s
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/appuser/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/appuser/autogpt/cli.py", line 83, in main
    from autogpt.plugins import scan_plugins
  File "/home/appuser/autogpt/plugins.py", line 12, in <module>
    import openapi_python_client
ModuleNotFoundError: No module named 'openapi_python_client'

**Comment by k-boikov** [comment]
Should be fixed now.
