### ISSUE TITLE
Docker images crashes on start built with current master

### ISSUE THREAD

**Issue by psvensson** [Significant-Gravitas/Auto-GPT#2658]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

1. Check out master
2. remove all existing docker containers for autgpt
3. remove all existing images for autgpt
4. build a docker image from scratch from README isntructions
5. Start docker container in the manner found in the README

### Current behavior 😯

After a few seconds and before any prompt show up we get this crash;
------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/appuser/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/appuser/autogpt/cli.py", line 83, in main
    from autogpt.plugins import scan_plugins
  File "/home/appuser/autogpt/plugins.py", line 12, in <module>
    import openapi_python_client
ModuleNotFoundError: No module named 'openapi_python_client'

### Expected behavior 🤔

No crash

### Your prompt 📝

```yaml
# no prompt
```

### Your Logs 📒

```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/appuser/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/appuser/autogpt/cli.py", line 83, in main
    from autogpt.plugins import scan_plugins
  File "/home/appuser/autogpt/plugins.py", line 12, in <module>
    import openapi_python_client
ModuleNotFoundError: No module named 'openapi_python_client'

```

**Comment by hurrisonma** [comment]
`ubuntu@VM-4-14-ubuntu:~/Auto-GPT$ sudo docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/appuser/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/appuser/autogpt/cli.py", line 83, in main
    from autogpt.plugins import scan_plugins
  File "/home/appuser/autogpt/plugins.py", line 12, in <module>
    import openapi_python_client
ModuleNotFoundError: No module named 'openapi_python_client'
/
/`

**Comment by psvensson** [comment]
@hurrisonma I think your problem might not be docker-related. Can you see if you can run auto-gpt without docker and configure local storage correctly, and then try again in docker?

**Comment by psvensson** [comment]
Right, I don't even know what is being done here, honestly.
I'm a but miffed that the person making the change to the Dockerfile did not test the Dockerfile.

**Comment by Pwuts** [comment]
Docker build test passed CI, not sure how. Will evaluate to make sure it doesn't happen again.

**Comment by deb999983** [comment]
> Docker build test passed CI, not sure how. Will evaluate to make sure it doesn't happen again.

I think that's because in the ci.yml, all the dependencies are installed, and then tested. there is no command to remove the dependencies like in the Dockerfile.

**Comment by Pwuts** [comment]
@deb999983 it literally uses the Dockerfile to build the image.

**Comment by Pwuts** [comment]
Update: it tests *building* the image, not *running* the image 🤦🏼

**Comment by deb999983** [comment]
> @deb999983 it literally uses the Dockerfile to build the image.
Actually just tests building the image, apologies for my previous comment I thought you were talking about the Python CI.

**Comment by mikekelly** [comment]
> Right, I don't even know what is being done here, honestly. I'm a but miffed that the person making the change to the Dockerfile did not test the Dockerfile.

I'm going to make the CI pipeline for docker/docker-compose more robust so this can't happen again, and I'm going to review all the PRs tagged with `docker` to keep on top of these changes to make sure nothing sneaks in
