### ISSUE TITLE
Testing newest update for release tomorrow and got this error upon launch

### ISSUE THREAD

**Issue by HostileRespite** [Significant-Gravitas/Auto-GPT#2713]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Upload the https://github.com/Significant-Gravitas/Auto-GPT/tree/test-0.2.2 repository.
Install all requirements.
Launch.

### Current behavior 😯

C:\Users\Owner\Documents\GitHub\Auto-GPT>python -m autogpt --ai-settings ai_ember.yaml
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\Documents\GitHub\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "C:\Users\Owner\Documents\GitHub\Auto-GPT\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

### Expected behavior 🤔

For it to display name and instructions and commence execution.

### Your prompt 📝

python -m autogpt --ai-settings ai_ember.yaml

### Your Logs 📒

No log was generated

**Comment by HostileRespite** [comment]
This was issue was resolved per dev via Discord.

**Comment by HostileRespite** [comment]
If you are experiencing this issue, upload the repository and install requirements again and it will go away.
