### ISSUE TITLE
 ModuleNotFoundError: No module named 'autogpt.config.singleton' Stable version - Demo April 16th 2023

### ISSUE THREAD

**Issue by jcrsantiago** [Significant-Gravitas/Auto-GPT#2722]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

git log
commit 999990b614f9c5e32dbfb560ab9516755d212884 (HEAD -> stable, origin/stable)
Author: BillSchumacher <34168009+BillSchumacher@users.noreply.github.com>
Date:   Thu Apr 20 01:15:46 2023 -0500

python -m autogpt

### Current behavior 😯

(auto-gpt) c:\Auto-GPT>python -m autogpt
Traceback (most recent call last):
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\Users\Trust\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\Auto-GPT\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "c:\Auto-GPT\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "c:\Auto-GPT\autogpt\app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "c:\Auto-GPT\autogpt\agent\agent_manager.py", line 6, in <module>
    from autogpt.config.config import Singleton
  File "c:\Auto-GPT\autogpt\config\__init__.py", line 5, in <module>
    from autogpt.config.config import Config, check_openai_api_key
  File "c:\Auto-GPT\autogpt\config\config.py", line 9, in <module>
    from autogpt.config.singleton import Singleton
ModuleNotFoundError: No module named 'autogpt.config.singleton'

### Expected behavior 🤔

It should run

### Your prompt 📝

Doesn't get that far.

### Your Logs 📒

Empty

**Comment by jcrsantiago** [comment]
I'm not sure what caused this, but i resolved it by deleting the entire folder and starting from scratch.

**Comment by jcrsantiago** [comment]
I'm not sure what caused this, but i resolved it by deleting the entire folder and starting from scratch.
