### ISSUE TITLE
When  I running Auto-GPT, there is an error I can't resolve

### ISSUE THREAD

**Issue by FLAWING2016** [Significant-Gravitas/Auto-GPT#2781]
I did anything before running,but when I  run it with  command "./run.bat" or "python  -m  autogpt",  python  report this error message:

------------------------------
"All packages are installed.
Traceback (most recent call last):
  File "F:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\code\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "F:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\python\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "F:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\python\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\code\Auto-GPT\autogpt\cli.py", line 83, in main
    from autogpt.plugins import scan_plugins
  File "E:\code\Auto-GPT\autogpt\plugins.py", line 12, in <module>
    import openapi_python_client
  File "F:\python\lib\site-packages\openapi_python_client\__init__.py", line 21, in <module>
    from .parser import GeneratorData, import_string_from_class
  File "F:\python\lib\site-packages\openapi_python_client\parser\__init__.py", line 5, in <module>
    from .openapi import GeneratorData, import_string_from_class
  File "F:\python\lib\site-packages\openapi_python_client\parser\openapi.py", line 11, in <module>
    from .. import schema as oai
  File "F:\python\lib\site-packages\openapi_python_client\schema\__init__.py", line 19, in <module>
    from .openapi_schema_pydantic import (
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\__init__.py", line 44, in <module>
    from .components import Components
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\components.py", line 7, in <module>
    from .header import Header
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\header.py", line 4, in <module>    from .parameter import Parameter
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\parameter.py", line 7, in <module>
    from .media_type import MediaType
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\media_type.py", line 5, in <module>
    from .encoding import Encoding
  File "F:\python\lib\site-packages\openapi_python_client\schema\openapi_schema_pydantic\encoding.py", line 13, in <module>
    class Encoding(BaseModel):
  File "pydantic\main.py", line 286, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\main.py", line 808, in pydantic.main.BaseModel.__try_update_forward_refs__
  File "pydantic\typing.py", line 553, in pydantic.typing.update_model_forward_refs

  File "pydantic\typing.py", line 528, in pydantic.typing.update_field_forward_refs
    '''Return the longest of two strings.'''
  File "pydantic\typing.py", line 528, in pydantic.typing.update_field_forward_refs
    '''Return the longest of two strings.'''
  File "pydantic\typing.py", line 519, in pydantic.typing.update_field_forward_refs
    checkers.  They serve as the parameters for generic types as well
  File "pydantic\typing.py", line 65, in pydantic.typing.evaluate_forwardref
    'Sized',
TypeError: _evaluate() takes 3 positional arguments but 4 were given";

-----------------------------------

I am sure all package and autogpt sourcecode was lastest , my python version is Python 3.9.0b4。
thanks for your help

**Comment by parksunwoo** [comment]
Read me, it looks like this
Python 3.10 or later

Why don't you try updating your python version? I'm using version 3.11

**Comment by FLAWING2016** [comment]
> Read me, it looks like this Python 3.10 or later
> 
> Why don't you try updating your python version? I'm using version 3.11

thank you very much
