### ISSUE TITLE
errors when starting Auto-GPT, what am i missing? 

### ISSUE THREAD

**Issue by j4rv1s1on** [Significant-Gravitas/Auto-GPT#2815]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

```
C:\Program Files\Auto-GPT-stable-0.2.2>python -m autogpt --gpt3only --continuous
Traceback (most recent call last):
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\app.py", line 13, in <module>
    from autogpt.commands.file_operations import (
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\commands\file_operations.py", line 13, in <module>
    from autogpt.utils import readable_file_size
  File "C:\Program Files\Auto-GPT-stable-0.2.2\autogpt\utils.py", line 6, in <module>
    from git import Repo
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


```

**Comment by sydneyrd** [comment]
![image](https://user-images.githubusercontent.com/102965341/233668351-a8dc4046-c14e-45c6-8fc8-4da4cdcc7299.png)

**Comment by j4rv1s1on** [comment]
oh sh*t i always understimate chatGPT hahah, i tried some older version time ago of auto-gpt didn't know that now requires git. sorry! :)

**Comment by sydneyrd** [comment]
> oh sh*t i always understimate chatGPT hahah, i tried some older version time ago of auto-gpt didn't know that now requires git. sorry! :)

haha, couldn't resist, no worries.   prepare to become obsessed though.
