### ISSUE TITLE
Pinecone

### ISSUE THREAD

**Issue by Shwing97** [Significant-Gravitas/Auto-GPT#2835]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

.\run.bat

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\app.py", line 10, in <module>
    from autogpt.processing.text import summarize_text
  File "C:\Users\Dave\pyproj\Auto-GPT\autogpt\processing\text.py", line 4, in <module>
    import spacy
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\spacy\errors.py", line 2, in <module>
    from .compat import Literal
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\spacy\compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\thinc\backends\__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\Dave\pyproj\my_env\Lib\site-packages\thinc\backends\cupy_ops.py", line 4, in <module>
    from .numpy_ops import NumpyOps
ImportError: DLL load failed while importing numpy_ops: The specified module could not be found.

### Current behavior 😯

Tells me that autogpt.json does not exist. Im using Pinecone for memory. API and region is set.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
There seems to be something wrong with "my_env", can you try to recreate the venv and run:
`pip install -r requirements.txt`
`python -m autogpt`

**Comment by Shwing97** [comment]
I actually installed it out of the venv just to see if that was the issue and I'm still getting: 

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\app.py", line 27, in <module>
    from autogpt.commands.web_selenium import browse_website
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\commands\web_selenium.py", line 20, in <module>
    import autogpt.processing.text as summary
  File "C:\Users\Dave\Documents\Projects\Auto-GPT-0.2.2\autogpt\processing\text.py", line 4, in <module>
    import spacy
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\errors.py", line 2, in <module>
    from .compat import Literal
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\thinc\backends\__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\thinc\backends\cupy_ops.py", line 4, in <module>
    from .numpy_ops import NumpyOps
ImportError: DLL load failed while importing numpy_ops: The specified module could not be found.

**Comment by Shwing97** [comment]
@k-boikov 

I was missing the docker setup and i finally have docker running and it did its thing. Now when I run 'python -m autogpt' in vscode terminal, i get this error:


_Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/Auto-GPT-0.2.2/autogpt/__main__.py", line 2, in <module>
    import autogpt.cli
  File "/workspaces/Auto-GPT-0.2.2/autogpt/cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'_


I have uninstalled and installed 'click' several times and still get this error.

**Comment by ntindle** [comment]
This seems to be a setup issue. Please work with the people in #tech-support on our discord to get a fix
