### ISSUE TITLE
openai module not found

### ISSUE THREAD

**Issue by skullcrushercmd** [Significant-Gravitas/Auto-GPT#2867]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

skull@gpt:~/AutoGPT$ python3 -m autogpt --continuous
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/skull/AutoGPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/skull/AutoGPT/autogpt/cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "/home/skull/AutoGPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/skull/AutoGPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/skull/AutoGPT/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/home/skull/AutoGPT/autogpt/agent/agent_manager.py", line 6, in <module>
    from autogpt.config.config import Singleton
  File "/home/skull/AutoGPT/autogpt/config/__init__.py", line 5, in <module>
    from autogpt.config.config import Config, check_openai_api_key
  File "/home/skull/AutoGPT/autogpt/config/config.py", line 4, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

### Current behavior 😯

When i try to start it in an ubuntu terminal using python3 -m  autogpt in the dir the gpt is stored in, it tells me it cant find openai. Keep in mind that i am using a vm from azure and downloaded version 0.2.2 but i was just using this and that error sprung up out of no where and reset the vm and sftp the autogpt v0.2.2 folder that i redownloaded from here and still same issue. Im also running ubuntu 22.10

### Expected behavior 🤔

It should just work

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<there is none>
```

**Comment by skullcrushercmd** [comment]
forgot to build it
