### ISSUE TITLE
Error Installing on Raspberry Pi OS

### ISSUE THREAD

**Issue by FuzzTalkAI** [Significant-Gravitas/Auto-GPT#2874]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I'm trying to install on the Raspberry Pi OS and everything seems to install correctly until I get to the prompt of ./run.sh it gives me this error

How do I fix this?

### Current behavior 😯

Just throws the error

### Expected behavior 🤔

It should run Auto-GPT

### Your prompt 📝

```yaml
# Paste your prompt here
```
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fuzzy427/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fuzzy427/Auto-GPT/autogpt/cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "/home/fuzzy427/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/fuzzy427/Auto-GPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/fuzzy427/Auto-GPT/autogpt/app.py", line 27, in <module>
    from autogpt.commands.web_selenium import browse_website
  File "/home/fuzzy427/Auto-GPT/autogpt/commands/web_selenium.py", line 20, in <module>
    import autogpt.processing.text as summary
  File "/home/fuzzy427/Auto-GPT/autogpt/processing/text.py", line 4, in <module>
    import spacy
  File "/home/fuzzy427/.local/lib/python3.9/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/home/fuzzy427/.local/lib/python3.9/site-packages/spacy/errors.py", line 2, in <module>
    from .compat import Literal
  File "/home/fuzzy427/.local/lib/python3.9/site-packages/spacy/compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/usr/local/lib/python3.9/dist-packages/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/usr/local/lib/python3.9/dist-packages/thinc/backends/__init__.py", line 7, in <module>
    from .ops import Ops
  File "/usr/local/lib/python3.9/dist-packages/thinc/backends/ops.py", line 16, in <module>
    from .cblas import CBlas
  File "thinc/backends/cblas.pyx", line 1, in init thinc.backends.cblas
  File "/usr/local/lib/python3.9/dist-packages/blis/__init__.py", line 3, in <module>
    from .cy import init
ImportError: /usr/local/lib/python3.9/dist-packages/blis/cy.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by druytssa** [comment]
Hi, 

It does work on a Raspberry pi. I am running mine on a P400. It took some time but I used GPT4 to fix all the errors.

**Comment by ntindle** [comment]
> Hi,
> 
> It does work on a Raspberry pi. I am running mine on a P400. It took some time but I used GPT4 to fix all the errors.

Can you give me a summary of the changes you had to make to get it working?

**Comment by druytssa** [comment]
Hi,

Not really, I know there were a lot of python packages missing like for
instance beautifulsoup that is used for web scraping.
After running source /home/jarvis/Auto-GPT/jarvis_ai/bin/activate
and then python -m autogpt it will start generating errors.
I took those errors and copied it into GPT-Plus (GPT-4) that then made the
necessary suggestions.
It took about 4 hours to get it working.

You also need to run in sudo when running python -m autogpt or it does not
work.

Kind regards,

**Comment by FuzzTalkAI** [comment]
Definitely interested in hearing more on what you did to get it fully working. Right now I just run through the setup given and this is where I get hit with an error that I'm not sure how to fix.

**Comment by Aaronminer1** [comment]
The error missing auto-gpt.json is a known issue you basically create the file with blank content and that should fix the issue if you search for auto-gpt.json you should be able to find more on where to place the file

**Comment by leeboy1984** [comment]
Do you have any documentation to share? i'm trying to install in my rPI4 but I'm getting stuck with dependencies like `tiktoken==0.3.3`

**Comment by raphael-2023** [comment]
Hello,
The main issue I see is with Spacy and Blis versions. I didn't solve it yet and I'm trying for few days now with all suggestions from ChatGPT (3.5 & 4)
I guess I'm missing the exact versions that can work on Raspberry pi Armv7 32bit
Any suggestions will be helpful

**Comment by ntindle** [comment]
We're not planning on supporting raspberry pi at this moment as a target
