### ISSUE TITLE
pinecone.core.client.exceptions.ForbiddenException: 403

### ISSUE THREAD

**Issue by LouisRosche** [Significant-Gravitas/Auto-GPT#2941]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Installation completing all instructions, including API keys for OpenAI, Pinecone, and Twitter.

### Current behavior 😯

CMD when prompted with .\run.bat outputs the log below.

### Expected behavior 🤔

Ideally, it should begin functioning with Pinecone as memory instead of LocalCache.

### Your Logs 📒

F:\AutoGPT\Auto-GPT>.\run.bat
All packages are installed.
C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py:45: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default).
  return self.urllib3_response.getheader(name, default)
F:\AutoGPT\Auto-GPT\autogpt\memory\pinecone.py:40: ResourceWarning: unclosed <ssl.SSLSocket fd=1180, family=2, type=1, proto=0, laddr=('192.168.86.150', 49952), raddr=('34.146.254.58', 443)>
  if table_name not in pinecone.list_indexes():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
F:\AutoGPT\Auto-GPT\autogpt\utils.py:60: ResourceWarning: unclosed file <_io.TextIOWrapper name='CURRENT_BULLETIN.md' mode='r' encoding='utf-8'>
  current_bulletin = open("CURRENT_BULLETIN.md", "r", encoding="utf-8").read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
Welcome back!  Would you like me to return to being PersonalBrandingSocialMediaWizard?
Continue with the last settings?
Name:  PersonalBrandingSocialMediaWizard
Role:  an AI designed to use Twitter and LinkedIn to design and develop the personal brand and social media reach of Louis Rosche, a learning and development professional specializing in change management, data analysis, educational leadership, developing a sense of purpose in life, and human health and wellness
Goals: ["revamp Louis Rosche's Twitter and LinkedIn profiles by highlighting his areas of expertise, creating a consistent brand image, and crafting a compelling bio that showcases his unique value proposition in learning and development.", "identify and share relevant articles, research, and multimedia content on Louis Rosche's social media channels that align with his areas of specialization. This will include content on change management, data analysis, educational leadership, purpose-driven living, and health and wellness to engage his target audience and establish him as a thought leader in his field.", "actively engage with other professionals in the learning and development space by liking, sharing, and commenting on relevant posts, joining discussions in relevant LinkedIn groups, and participating in Twitter chats. This will expand Louis Rosche's network and foster relationships with like-minded professionals.", 'generating original content, such as blog articles, LinkedIn Pulse articles, and thought-provoking tweets that showcase his expertise and insights in his specialization areas. This original content will help increase his social media reach and establish him as a credible voice in the learning and development community.', "continuously monitor engagement metrics (likes, shares, comments, retweets) and key performance indicators (follower growth, profile views, website traffic) to assess the effectiveness of the personal branding strategy. The AI will then use this data to refine its approach and optimize content creation, sharing, and engagement strategies to maximize Louis Rosche's social media reach and impact."]
Continue (y/n): y
C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py:41: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
  return self.urllib3_response.getheaders()
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\AutoGPT\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AutoGPT\Auto-GPT\autogpt\cli.py", line 120, in main
    memory = get_memory(cfg, init=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AutoGPT\Auto-GPT\autogpt\memory\__init__.py", line 52, in get_memory
    memory.clear()
  File "F:\AutoGPT\Auto-GPT\autogpt\memory\pinecone.py", line 58, in clear
    self.index.delete(deleteAll=True)
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\index.py", line 329, in delete
    return self._vector_api.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api\vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 222, in request
    raise ForbiddenException(http_resp=r)
pinecone.core.client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Sat, 22 Apr 2023 18:12:49 GMT', 'server': 'envoy'})

Press any key to continue . . .

**Comment by k-boikov** [comment]
I ran into the same error, I guess its a Pinecone API issue.

**Comment by Brucegx** [comment]
I got a similar issue. my setting in env is like 
PINECONE_API_KEY= "bsdfasfeb62-1e1c-4dfsasd79-81de-safsafc4sfasdfe1c"
PINECONE_ENV= "asia-northeast1-gcp"
Do we need to add the double quote? Or is it a the pinecone side issue?

**Comment by k-boikov** [comment]
Absolutely no. The values for the given configurations in the .env are always without any quotes and any spaces.

**Comment by Rezurrekt-NFT** [comment]
Getting the same issue. I've tried setting the env variables in windows but no luck there too. It seems to be an issue with Pinecone not accepting external connections. Maybe they blocked people with starter packages now.

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this

**Comment by TeroD07** [comment]
> I got a similar issue. my setting in env is like PINECONE_API_KEY= "" PINECONE_ENV= "asia-northeast1-gcp" Do we need to add the double quote? Or is it a the pinecone side issue?

You should def remove your API key and never post it online

**Comment by Brucegx** [comment]
> > I got a similar issue. my setting in env is like PINECONE_API_KEY= "" PINECONE_ENV= "asia-northeast1-gcp" Do we need to add the double quote? Or is it a the pinecone side issue?
> 
> You should def remove your API key and never post it online

Thanks for pointing it out. The key is fake.

**Comment by brianberneker** [comment]
Not sure if this helps, but I encountered the same error right after generating a new key. Perhaps there is a delay before the key becomes usable. All i had to do was wait a short while and the key worked without any modifications to my .env file or anything.
