### ISSUE TITLE
Error on running autogpt "File "<fstring>", line 1 (err=)"

### ISSUE THREAD

**Issue by bossoss** [Significant-Gravitas/Auto-GPT#3000]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

C:\Users\XXX\Downloads\Auto-GPT-0.2.2> python -m autogpt --continuous

### Current behavior 😯

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\app.py", line 26, in <module>
    from autogpt.commands.web_requests import scrape_links, scrape_text
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\commands\web_requests.py", line 12, in <module>
    from autogpt.memory import get_memory
  File "C:\Users\XXX\Downloads\Auto-GPT-0.2.2\autogpt\memory\__init__.py", line 25, in <module>
    from autogpt.memory.weaviate import WeaviateMemory
  File "<fstring>", line 1
    (err=)
        ^
SyntaxError: invalid syntax

### Expected behavior 🤔

i expected a successful run of autogpt. i've tried using python3 and python3.7 with same outcome.
trying to run autogpt initially got me stuck in several "missing module"-dependency errors which i had to install manually but now  i'm running into this "File "<fstring>", line 1 (err=)" and i could'nt solve it.
i had to install following modules (if it helps)
python-dotenv, playsound, gtts, docker, GitPython, duckduckgo_search, pillow, tweepy, bs4, numpy and orjson

### Your prompt 📝

```yaml
# Paste your prompt here
```
ai_settings.yaml not existent (haven't started autogpt yet)

### Your Logs 📒

```log
<insert your logs here>
```
log is empty

**Comment by k-boikov** [comment]
Please upgrade python to 3.10 or higher.

**Comment by bossoss** [comment]
as i wrote, i have tried several pythong versions including my currently installed, version 3.7

**Comment by k-boikov** [comment]
3.7 is not supported - you need 3.10 or higher.

**Comment by bossoss** [comment]
ahh thank you, was mistaken 3.10 with 3.1 - with 3.10 i got it working!
