### ISSUE TITLE
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by zsmj610** [Significant-Gravitas/Auto-GPT#3111]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/3109

<div type='discussions-op-text'>

<sup>Originally posted by **zsmj610** April 24, 2023</sup>
Traceback (most recent call last):
  File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Auto-GPT-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\Auto-GPT-0.2.2\autogpt\cli.py", line 151, in main
    agent.start_interaction_loop()
  File "E:\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 75, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "E:\Auto-GPT-0.2.2\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "E:\Auto-GPT-0.2.2\autogpt\llm_utils.py", line 93, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?</div>

**Comment by johnualett** [comment]
Hi, I have the same problem? Does anyone know what it could be?

**Comment by k-boikov** [comment]
Please provide more info following the bug template.

**Comment by johnualett** [comment]
The error itself tells me little, but I was able to fix it by changing the model to be used to create the bot, in this case for what I'm doing 'davinci' is used and I was using 'gpt-3.5-turbo' in what I read a A little more in the openai documentation I was able to solve it. Now that worked for me, I don't know if it works for someone else.

**Comment by zsmj610** [comment]
> 

hi，can you describe your solution in detail.

**Comment by zsmj610** [comment]
> 

@johnualett hi，can you describe your solution in detail.

**Comment by k-boikov** [comment]
Reopened https://github.com/Significant-Gravitas/Auto-GPT/issues/3215
