### ISSUE TITLE
ModuleNotFOundError when ./run.bat

### ISSUE THREAD

**Issue by baggot4** [Significant-Gravitas/Auto-GPT#3138]
When I run ./run.bat all the requirements install, but I get this error eventually. 

ModuleNotFoundError: No module named 'click'

Traceback (most recent call last):
  File "C:\Users\baggot4\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\baggot4\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\baggot4\Documents\auto-gpt\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "C:\Users\baggot4\Documents\auto-gpt\Auto-GPT\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

![image](https://user-images.githubusercontent.com/35886854/234021487-175b7e36-b215-4df0-8511-c49e41e841e2.png)

I've attempted to fix using https://stackoverflow.com/questions/68093036/importerror-no-module-named-click but I have had no luck

**Comment by ssharlin** [comment]
hello, how did you fix that?
