### ISSUE TITLE
does not allow to continue process after crash

### ISSUE THREAD

**Issue by SvenMeyer** [Significant-Gravitas/Auto-GPT#3219]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

- after already working through ~200 iterations, Auto-GPT downloaded a larger file
- crashed
- when restarted did not remember anything from the ~200 iterations before

### Current behavior 😯

```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://docs.centrifuge.io/build/tinlake/', 'question': 'How does Tinlake work?'}
[WDM] - Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.75M/6.75M [00:01<00:00, 6.36MB/s]
Text length: 50733 characters
Adding chunk 1 / 5 to memory
Summarizing chunk 1 / 5 of length 12128 characters, or 2998 tokens
Added chunk 1 summary to memory, of length 817 characters
Adding chunk 2 / 5 to memory
Summarizing chunk 2 / 5 of length 12730 characters, or 2912 tokens
Added chunk 2 summary to memory, of length 688 characters
Adding chunk 3 / 5 to memory
Summarizing chunk 3 / 5 of length 11341 characters, or 2969 tokens
Added chunk 3 summary to memory, of length 557 characters
Adding chunk 4 / 5 to memory
Summarizing chunk 4 / 5 of length 12101 characters, or 2990 tokens
SYSTEM:  Command browse_website returned: Error: The server is overloaded or not ready yet.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sum/DEV/AI/Auto-GPT/Auto-GPT-0.2.2/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sum/DEV/AI/Auto-GPT/Auto-GPT-0.2.2/autogpt/cli.py", line 151, in main
    agent.start_interaction_loop()
  File "/home/sum/DEV/AI/Auto-GPT/Auto-GPT-0.2.2/autogpt/agent/agent.py", line 75, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/home/sum/DEV/AI/Auto-GPT/Auto-GPT-0.2.2/autogpt/chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/home/sum/DEV/AI/Auto-GPT/Auto-GPT-0.2.2/autogpt/llm_utils.py", line 93, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/home/sum/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/sum/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/sum/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/sum/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/sum/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 662, in _interpret_response_line
    raise error.ServiceUnavailableError(
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
```

### Expected behavior 🤔

- show be able to resume operation after crash or user abort

### Your prompt 📝

```
Input:can you clone the tinlake repository from centrifuge and have a look at the .sol files in the src folder. That may give you an idea how cwntrifuge has implemented RWA tokenization and using them as collateral. Therafter continue with your privious research. I think this webpage which you have found just shortly is a great resources to continue if that wasn't the plan anyway https://www.whitecase.com/insight-our-thinking/rise-digital-finance-tokenising-mining-metals-assets

```

### Your Logs 📒

will attach to next post ...

**Comment by SvenMeyer** [comment]
[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11323922/activity.log)
[error.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11323923/error.log)

**Comment by ntindle** [comment]
Thanks for the contribution! I’m closing this as a duplicate of another bug!
