### ISSUE TITLE
error running bat

### ISSUE THREAD

**Issue by gsgoldma** [Significant-Gravitas/Auto-GPT#3229]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

just running bat. 

### Current behavior 😯

Traceback (most recent call last):
  File "D:\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "D:\Auto-GPT\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Press any key to continue . . .

### Expected behavior 🤔

regular function

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

Traceback (most recent call last):
  File "D:\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "D:\Auto-GPT\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Press any key to continue . . .

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help
