### ISSUE TITLE
Can't run the AutoGPT (macos 2017 - ventura)

### ISSUE THREAD

**Issue by dmkei** [Significant-Gravitas/Auto-GPT#3236]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Running into this issues, before was the issues with lxml...wheels, solved it with macports..

running pip3/python 3.11
git 2.40

Can figure out this "click" situation, asked GPT4 to solve, tried to import it, terminal said it's already imported.

File "<frozen runpy>", line 198, in _run_module_as_main
 File "<frozen runpy>", line 88, in _run_code
 File "/Users/xxxxx/Auto-GPT/autogpt/__[main__.py](http://main__.py/)", line 2, in <module>
  import autogpt.cli
 File "/Users/xxxxxx/Auto-GPT/autogpt/[cli.py](http://cli.py/)", line 2, in <module>
  import click "

### Current behavior 😯

Nothing happens, it's the last step before launching autogpt.

### Expected behavior 🤔

Launch autogpt in terminal

### Your prompt 📝

python3 -m autogpt > run

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/xxxxxx/Auto-GPT/autogpt/__main__.py", line 2, in <module>
    import autogpt.cli
  File "/Users/xxxxxx/Auto-GPT/autogpt/cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

### Your Logs 📒

MBP ~ % history
   33  pip2 install click
   34  cd Auto-GPT
   35  pip3 -m autogpt
   36  python3 -m autogpt
   37  python3 --version
   38  pip3 --version
   39  git --version
   40  brew --version
   41  brew tap domt4/autoupdate\n
   42  brew autoupdate --start\n
   43  cd Auto-GPT
   44  python3 -m autogpt
   45  cd Auto-GPT
   46  python3 -m autogpt
   47  logs

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help
