### ISSUE TITLE
win32 file permission errror

### ISSUE THREAD

**Issue by nekohacker591** [Significant-Gravitas/Auto-GPT#331]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

run in speach mode

### Current behavior 😯

announces the speech mode quate

then proceeds to crash giving this error

D:\AI\autogpt\Auto-GPT>python scripts/main.py --speak
Speak Mode:  ENABLED
Traceback (most recent call last):
  File "D:\AI\autogpt\Auto-GPT\scripts\main.py", line 275, in <module>
    prompt = construct_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "D:\AI\autogpt\Auto-GPT\scripts\main.py", line 178, in construct_prompt
    config = prompt_user()
             ^^^^^^^^^^^^^
  File "D:\AI\autogpt\Auto-GPT\scripts\main.py", line 192, in prompt_user
    print_to_console(
  File "D:\AI\autogpt\Auto-GPT\scripts\main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "D:\AI\autogpt\Auto-GPT\scripts\speak.py", line 45, in say_text
    success = eleven_labs_speech(text, voice_index)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\autogpt\Auto-GPT\scripts\speak.py", line 28, in eleven_labs_speech
    os.remove("speech.mpeg")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'speech.mpeg'

### Expected behavior 🤔

should continue by asking the next questen

### Your prompt 📝

```yaml
N/A
```

**Comment by nekohacker591** [comment]
removing the ELEVENLABS_API_KEY= argument removed this error

**Comment by Explorergt92** [comment]
@nekohacker591 is this still an issue for you or can this be closed?

**Comment by ezzyland** [comment]
> removing the ELEVENLABS_API_KEY= argument removed this error

yea you just removed the tts.. that is not a solution brother
