### ISSUE TITLE
Error: Redis is not installed... And cannot import name '_gi'

### ISSUE THREAD

**Issue by W01v3n** [Significant-Gravitas/Auto-GPT#3388]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

First, I had another issue- [#2581](https://github.com/Significant-Gravitas/Auto-GPT/issues/2581), someone named [ntindle](https://github.com/ntindle) closed it with a comment and his advice didn't help, and still he kept the issue closed.
Hopefully, this time this issue will remain open until the issue is **solved**.

1. Download zip file of stable version.
2. Extract it.
3. cd into it.
4. install requirements.
5. run it:
`python -m autogpt --speak --gpt3only`

### Current behavior 😯

```
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Welcome back!  Would you like me to return to being Bella?
Continue with the last settings?
Name:  Bella
Role:  an AI designed to help me make additional incomes with the goal of increasing my net worth.
Goals: ['Increase net worth', 'Help me with my life and tasks and serve me as good as possible', 'Make my life easier.', 'Develop successful businesses and manage them autonomously', 'Think of the easiest, most profitable and high potential ways to make money that can be automated and with almost no human work required']
Continue (y/n): Exception in thread Thread-1 (speak):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/say.py", line 34, in speak
    success = VOICE_ENGINE.say(text, voice_index)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/base.py", line 33, in say
    return self._speech(text, voice_index)
  File "/home/w01v3n/git/Auto-GPT/autogpt/speech/eleven_labs.py", line 80, in _speech
    playsound("speech.mpeg", True)
  File "/home/w01v3n/.local/lib/python3.10/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)

```

### Expected behavior 🤔

Should work without errors or warnings. I want to use redis because it's a free, locally hosted database server. And it can and should be used in my case as the memory backend.

### Your prompt 📝

```yaml
ai_goals:
- Increase net worth
- Help me with my life and tasks and serve me as good as possible
- Make my life easier.
- Develop successful businesses and manage them autonomously
- Think of the easiest, most profitable and high potential ways to make money that
  can be automated and with almost no human work required
ai_name: Bella
ai_role: an AI designed to help me make additional incomes with the goal of increasing
  my net worth.
```

### Your Logs 📒

```log
2023-04-19 21:50:53,394 INFO Speak Mode:  ENABLED
2023-04-19 21:50:53,535 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:50:53,935 INFO NEWS:   ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:50:54,498 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:50:54,763 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:07,448 INFO Speak Mode:  ENABLED
2023-04-19 21:52:07,586 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:52:07,911 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:52:08,425 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:52:08,711 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:49,726 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:52:50,430 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:52:50,945 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:52:51,296 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:52:51,491 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-04-19 21:52:51,843 INFO Name your AI:  For example, 'Entrepreneur-GPT'
2023-04-19 21:55:20,331 INFO Speak Mode:  ENABLED
2023-04-19 21:55:20,457 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:55:20,804 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:55:21,281 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:55:21,601 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:58:18,396 INFO Speak Mode:  ENABLED
2023-04-19 21:58:18,515 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 21:58:18,911 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 21:58:19,503 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 21:58:19,820 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-19 21:58:28,403 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-04-19 21:58:28,861 INFO Name your AI:  For example, 'Entrepreneur-GPT'
2023-04-19 21:59:06,497 INFO Bella here! I am at your service.
2023-04-19 21:59:06,652 INFO Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
2023-04-19 22:00:39,475 INFO Enter up to 5 goals for your AI:  For example: 
Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
2023-04-19 22:03:58,497 INFO Using memory of type: LocalCache
2023-04-19 22:03:58,659 INFO Using Browser: chrome
2023-04-19 22:04:23,663 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:04:24,262 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:04:24,851 INFO PLAN: 
2023-04-19 22:04:24,890 INFO -  Brainstorm potential business ideas
2023-04-19 22:04:25,052 INFO -  Research market demand and competition for each idea
2023-04-19 22:04:25,322 INFO -  Determine feasibility and profitability of each idea
2023-04-19 22:04:25,599 INFO -  Automate tasks to reduce costs and increase efficiency
2023-04-19 22:04:25,826 INFO CRITICISM: We need to ensure that we are not limiting ourselves to only ideas that align with your current interests and skills. It is important to consider new and emerging industries that may have high potential for growth and profitability. Additionally, we need to be cautious of over-automation, as it may lead to a lack of personal touch and customer satisfaction.
2023-04-19 22:04:54,052 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:05:35,985 INFO SYSTEM:  Human feedback: Can you use redis instead of localcache?
2023-04-19 22:05:46,861 INFO  THOUGHTS: I am not sure what you are referring to. Can you please provide more context or information about the use case for Redis and LocalCache?
2023-04-19 22:05:47,331 INFO REASONING: As an AI, I need to understand the context and purpose of the request in order to provide an appropriate response. By asking for more information, I can better understand the situation and provide a more helpful response.
2023-04-19 22:05:47,875 INFO PLAN: 
2023-04-19 22:05:47,947 INFO -  Ask for more information to better understand the situation
2023-04-19 22:05:48,224 INFO CRITICISM: None
2023-04-19 22:05:58,838 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:10:36,687 INFO Speak Mode:  ENABLED
2023-04-19 22:10:37,036 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:10:37,494 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:10:37,855 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:10:50,176 INFO Using memory of type: LocalCache
2023-04-19 22:10:50,363 INFO Using Browser: chrome
2023-04-19 22:11:09,409 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:11:10,038 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:11:10,707 INFO PLAN: 
2023-04-19 22:11:10,758 INFO -  Brainstorm potential business ideas
2023-04-19 22:11:10,909 INFO -  Research market demand and competition for each idea
2023-04-19 22:11:11,105 INFO -  Determine feasibility and profitability of each idea
2023-04-19 22:11:11,290 INFO -  Automate tasks to reduce costs and increase efficiency
2023-04-19 22:11:11,524 INFO CRITICISM: I need to ensure that I am considering a wide range of potential business ideas and not limiting myself to a narrow set of options. Additionally, I need to be mindful of the potential risks and challenges associated with each idea and develop contingency plans to address them.
2023-04-19 22:11:39,311 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:13:34,805 INFO Speak Mode:  ENABLED
2023-04-19 22:13:35,124 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:13:35,622 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:13:35,926 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:13:41,195 INFO Using memory of type: RedisMemory
2023-04-19 22:13:41,407 INFO Using Browser: chrome
2023-04-19 22:14:47,911 INFO Speak Mode:  ENABLED
2023-04-19 22:14:48,014 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:14:48,439 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:14:48,948 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:14:49,251 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:15:01,646 INFO Using memory of type: LocalCache
2023-04-19 22:15:01,782 INFO Using Browser: chrome
2023-04-19 22:15:20,313 INFO  THOUGHTS: I think we should start by exploring potential business ideas that align with your interests and skills. We can then research the market demand and competition for those ideas to determine the most profitable and feasible options. Additionally, we can consider automating certain tasks to reduce the need for human labor and increase efficiency.
2023-04-19 22:15:20,873 INFO REASONING: By focusing on your interests and skills, we can increase the likelihood of success and enjoyment in the business ventures. Researching the market demand and competition will help us identify the most profitable and feasible options. Automating tasks can reduce costs and increase efficiency, allowing for more time and resources to be allocated towards growth and expansion.
2023-04-19 22:15:21,447 INFO PLAN: 
2023-04-19 22:15:21,516 INFO -  Brainstorm potential business ideas
2023-04-19 22:15:21,645 INFO -  Research market demand and competition for each idea
2023-04-19 22:15:21,859 INFO -  Identify the most profitable and feasible options
2023-04-19 22:15:22,058 INFO -  Consider automating tasks to reduce costs and increase efficiency
2023-04-19 22:15:22,331 INFO CRITICISM: I need to ensure that the business ideas we pursue are legal and ethical, and that the automation of tasks does not compromise quality or customer satisfaction.
2023-04-19 22:15:51,046 INFO NEXT ACTION:  COMMAND = do_nothing  ARGUMENTS = {}
2023-04-19 22:18:03,086 INFO Speak Mode:  ENABLED
2023-04-19 22:18:03,179 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:18:03,527 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:18:03,954 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:18:04,278 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:20:18,425 INFO Speak Mode:  ENABLED
2023-04-19 22:20:18,556 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:20:19,068 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:20:19,571 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:20:19,913 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:21:23,512 INFO Speak Mode:  ENABLED
2023-04-19 22:21:23,643 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:21:23,975 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:21:24,487 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:21:24,778 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:29:58,058 INFO Speak Mode:  ENABLED
2023-04-19 22:29:58,142 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:29:58,495 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:29:59,071 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:29:59,412 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:32:50,568 INFO Speak Mode:  ENABLED
2023-04-19 22:32:50,679 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:32:51,059 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:32:51,546 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:32:51,872 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:34:58,227 INFO Speak Mode:  ENABLED
2023-04-19 22:34:58,334 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:34:58,646 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:34:59,120 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:34:59,371 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:36:34,757 INFO Speak Mode:  ENABLED
2023-04-19 22:36:34,847 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:36:35,657 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:36:36,173 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:36:36,447 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:36:39,691 INFO Using memory of type: LocalCache
2023-04-19 22:36:39,825 INFO Using Browser: chrome
2023-04-19 22:37:16,583 INFO Speak Mode:  ENABLED
2023-04-19 22:37:16,697 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:37:17,056 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:37:17,588 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:37:17,942 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:37:24,541 INFO Using memory of type: LocalCache
2023-04-19 22:37:24,733 INFO Using Browser: chrome
2023-04-19 22:40:24,202 INFO Speak Mode:  ENABLED
2023-04-19 22:40:24,326 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:40:24,686 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:40:25,216 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:40:25,528 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-19 22:40:31,767 INFO Speak Mode:  ENABLED
2023-04-19 22:40:32,096 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:40:32,599 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:42:50,107 INFO Speak Mode:  ENABLED
2023-04-19 22:42:50,226 INFO GPT3.5 Only Mode:  ENABLED
2023-04-19 22:42:50,612 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-19 22:42:51,153 INFO WARNING:  You are running on `master` branch - this is not a supported branch.
2023-04-19 22:42:51,536 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-20 10:06:43,526 INFO Speak Mode:  ENABLED
2023-04-20 10:06:43,688 INFO GPT3.5 Only Mode:  ENABLED
2023-04-20 10:06:44,263 INFO NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-21 14:46:03,927 INFO Speak Mode:  ENABLED
2023-04-21 14:46:04,045 INFO GPT3.5 Only Mode:  ENABLED
2023-04-21 14:46:04,160 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-21 14:47:09,816 INFO Speak Mode:  ENABLED
2023-04-21 14:47:09,940 INFO GPT3.5 Only Mode:  ENABLED
2023-04-21 14:47:10,091 INFO Welcome back!  Would you like me to return to being Bella?
2023-04-27 10:36:44,822 INFO Speak Mode:  ENABLED
2023-04-27 10:36:44,953 INFO GPT3.5 Only Mode:  ENABLED
2023-04-27 10:36:45,115 INFO Welcome back!  Would you like me to return to being Bella?
```

**Comment by k-boikov** [comment]
I think the issue comes from having different python version at the same time. Please use venv or remove any older version of python.

**Comment by k-boikov** [comment]
And about redis - you need to switch to another memory in your .env if you don't have redis installed.

**Comment by W01v3n** [comment]
> I think the issue comes from having different python version at the same time. Please use venv or remove any older version of python.

Can you please state which version should I be using? I just seems very dumb of me to try to use every possible version, instead you can simply tell me which version I should use? Also, this should be stated in the main page.

**Comment by W01v3n** [comment]
> And about redis - you need to switch to another memory in your .env if you don't have redis installed.

About this, redis is installed and running, I'm a sysadmin, I know my stuff.
