### ISSUE TITLE
Issues with the image generation and a bunch other want it autonomous for stable diffusion and dalle or just dalle for now

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [Significant-Gravitas/Auto-GPT#3421]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I attempted to restore the template.env with my open token all others including hugging face get this issue

prob a bunch more just cant get my head around it want to be able to generate images autonomously for a project  I want to research 

### Current behavior 😯

I get all these errors my script 

Microsoft Windows [Version 10.0.19044.2846]
(c) Microsoft Corporation. All rights reserved.

C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2>python test.py
python: can't open file 'C:\\Users\\WeThe\\Documents\\AUTOGPT\\Auto-GPT-0.2.2\\test.py': [Errno 2] No such file or directory

C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2>python C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\tests.py
Python-dotenv could not parse statement starting at line 164
.........EE.json I will first need to browse the repository (https://github.com/Torantulino/Auto-GPT) and identify any potential bugs that need fixing. I will use the "browse_website" command for this.

{
    "command": {
        "name": "browse_website",
        "args":{
            "url": "https://github.com/Torantulino/Auto-GPT"
        }
    },
    "thoughts":
    {
        "text": "Browsing the repository to identify potential bugs",
        "reasoning": "Before fixing bugs, I need to identify what needs fixing. I will use the 'browse_website' command to analyze the repository.",
        "plan": "- Analyze the repository for potential bugs and areas of improvement",
        "criticism": "I need to ensure I am thorough and pay attention to detail while browsing the repository.",
        "speak": "I am browsing the repository to identify potential bugs."
    }
}
json loads error Expecting value: line 1 column 1 (char 0)
.json BEGIN: "name": "John" - "age": 30 - "city": "New York" :END
json loads error Expecting value: line 1 column 1 (char 0)
.json BEGIN: "name": "John" - "age": 30 - "city": "New York" :END
json loads error Expecting value: line 1 column 1 (char 0)
.json {"name": "John", "age": 30, "city": "New York",}
json loads error Expecting property name enclosed in double quotes: line 1 column 48 (char 47)
.......... ←[0m Warning: model not found. Using cl100k_base encoding.
.....
======================================================================
ERROR: test_dalle (test_image_gen.TestImageGen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\tests\test_image_gen.py", line 25, in test_dalle
    result = lst(generate_image("astronaut riding a horse", 256))
  File "C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\autogpt\commands\image_gen.py", line 31, in generate_image
    return generate_image_with_dalle(prompt, filename, size)
TypeError: generate_image_with_dalle() takes 2 positional arguments but 3 were given

======================================================================
ERROR: test_huggingface (test_image_gen.TestImageGen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\tests\test_image_gen.py", line 44, in test_huggingface
    result = lst(generate_image("astronaut riding a horse", 512))
  File "C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\autogpt\commands\image_gen.py", line 34, in generate_image
    return generate_image_with_hf(prompt, filename)
  File "C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2\autogpt\commands\image_gen.py", line 55, in generate_image_with_hf
    raise ValueError(
ValueError: You need to set your Hugging Face API token in the config file.

----------------------------------------------------------------------
Ran 30 tests in 0.388s

FAILED (errors=2)
Name                                     Stmts   Miss  Cover   Missing
----------------------------------------------------------------------
autogpt\__init__.py                          0      0   100%
autogpt\commands\__init__.py                 0      0   100%
autogpt\commands\image_gen.py               53     31    42%   36-38, 58-76, 89-113, 134-163
autogpt\config\__init__.py                   4      0   100%
autogpt\config\ai_config.py                 36     24    33%   36-40, 60-70, 84-90, 104-121
autogpt\config\config.py                   133     35    74%   50-53, 136-149, 164-174, 182, 206, 210, 214, 218, 222, 226, 230, 234, 238, 247-254
autogpt\config\singleton.py                  9      0   100%
autogpt\json_utils\__init__.py               0      0   100%
autogpt\json_utils\json_fix_general.py      66     28    58%   27-39, 57-58, 61-62, 66, 81, 88, 104, 110, 115-121, 123
autogpt\json_utils\json_fix_llm.py          85     51    40%   51-82, 96-112, 171-186, 190-220
autogpt\json_utils\utilities.py             25     17    32%   24-28, 37-54
autogpt\llm_utils.py                        71     58    18%   35-50, 72-138, 143-172
autogpt\logs.py                            190    114    40%   31, 84-93, 103, 114, 119, 123-124, 127-135, 145-162, 170-171, 189, 193, 207-294, 300-332
autogpt\promptgenerator.py                  32      1    97%   54
autogpt\speech\__init__.py                   2      0   100%
autogpt\speech\base.py                      20      4    80%   32-33, 40, 50
autogpt\speech\brian.py                     19     12    37%   15, 26-40
autogpt\speech\eleven_labs.py               34     24    29%   23-46, 59-60, 72-86
autogpt\speech\gtts.py                      13      5    62%   18-22
autogpt\speech\macos_tts.py                 12      7    42%   11, 15-21
autogpt\speech\say.py                       27     11    59%   15, 17, 19, 32-41
autogpt\token_counter.py                    32      2    94%   32, 35
autogpt\workspace.py                        16      7    56%   15, 27, 40-48
tests\__init__.py                            0      0   100%
tests\context.py                             3      0   100%
tests\test_config.py                        37      0   100%
tests\test_image_gen.py                     46     23    50%   13, 26-37, 45-57, 102
tests\test_json_parser.py                   30      4    87%   35-67, 111
tests\test_prompt_generator.py              54      0   100%
tests\test_token_counter.py                 33      4    88%   26-31, 63
----------------------------------------------------------------------
TOTAL                                     1082    462    57%

C:\Users\WeThe\Documents\AUTOGPT\Auto-GPT-0.2.2>

It does not generate says image provider not set

################################################################################
################################################################################

##   DALLE: 256, 512, 1024
# IMAGE_PROVIDER=dalle
# IMAGE_SIZE=256

## HUGGINGFACE_API_TOKEN - HuggingFace API token (Example: my-huggingface-api-token)
# HUGGINGFACE_IMAGE_MODEL=CompVis/stable-diffusion-v1-4
# HUGGINGFACE_API_TOKEN=blocked
## SD_WEBUI_URL - Stable diffusion webui API URL (Example: blocked
# SD_WEBUI_AUTH=
# SD_WEBUI_URL=blocked

blocked sensitive information

### Expected behavior 🤔

Autonomously will generate images via daily and stable diffusion image generation not working know its short just running out of my free time and want to get this rolling to optimize my life

### Your prompt 📝

```yaml
# Paste your prompt here
```
Not really this got that covered

### Your Logs 📒

```log
<insert your logs here>
```
]
2023-04-27 10:49:29,114 INFO  THOUGHTS: Based on the search results, it seems that the metaverse market is experiencing exciting growth, with its total size expected to reach $678.8bn by the end of 2030. This growth is driven by the increasing popularity of virtual reality (VR) and augmented reality (AR) technologies, as well as the emergence of new content, applications, and services. To cater to this growing market, we should create AI-generated art that is immersive and visually stunning. We can use the 'generate_image' command to create such art pieces.
2023-04-27 10:49:29,821 INFO REASONING: Creating visually stunning and immersive AI-generated art is likely to appeal to the growing metaverse market, which is driven by the increasing popularity of VR and AR technologies. By using the 'generate_image' command, we can create art pieces that are tailored to this market and maximize our income generation potential.
2023-04-27 10:49:30,407 INFO PLAN: 
2023-04-27 10:49:30,503 INFO -  Use the 'generate_image' command to create visually stunning and immersive AI-generated art pieces\n- Continuously analyze the market trends to ensure that our art pieces are in demand\n- Actively promote our art pieces on various metaverse platforms to attract potential buyers\n- Develop and maintain an engaging live streaming platform to showcase the art creation process in real-time and encourage viewer interaction
2023-04-27 10:49:31,158 INFO CRITICISM: I need to make sure that the art pieces we create are not only visually stunning but also unique and original. Additionally, I need to ensure that we are not oversaturating the market with too many similar art pieces.
2023-04-27 10:49:31,704 INFO NEXT ACTION:  COMMAND = generate_image  ARGUMENTS = {'prompt': 'Create a visually stunning and immersive AI-generated art piece that is tailored to the growing metaverse market.'}
2023-04-27 10:50:19,314 INFO SYSTEM:  Human feedback: I need you to test if you can generate dalle photos then deposit into a folder in workspace
2023-04-27 10:50:55,456 INFO  THOUGHTS: To test if I can generate DALL-E photos and deposit them into a folder in workspace, I can use the 'generate_image' command to create a DALL-E image and then use the 'write_to_file' command to save the image to a specified folder in workspace.
2023-04-27 10:50:55,991 INFO REASONING: By using the 'generate_image' command to create a DALL-E image and then using the 'write_to_file' command to save the image to a specified folder in workspace, I can test if I am able to generate DALL-E photos and deposit them into a folder in workspace.
2023-04-27 10:50:56,543 INFO PLAN: 
2023-04-27 10:50:56,608 INFO -  Use the 'generate_image' command to create a DALL-E image\n- Use the 'write_to_file' command to save the image to a specified folder in workspace\n- Check if the image was successfully saved to the specified folder in workspace
2023-04-27 10:50:57,122 INFO CRITICISM: I need to make sure that the folder in workspace where the image is being saved exists and that I have the necessary permissions to write to that folder.
2023-04-27 10:50:57,669 INFO NEXT ACTION:  COMMAND = generate_image  ARGUMENTS = {'prompt': 'Create a DALL-E image to test if I can generate DALL-E photos and deposit them into a folder in workspace.'}
2023-04-27 10:51:08,064 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
2023-04-27 10:51:08,643 INFO SYSTEM:  Command generate_image returned: No Image Provider Set
2023-04-27 10:51:45,548 INFO  THOUGHTS: It seems that no image provider has been set for the 'generate_image' command. I can set the image provider by using the 'message_agent' command to send a message to a GPT agent that can set the image provider for me.
2023-04-27 10:51:46,172 INFO REASONING: By using the 'message_agent' command to send a message to a GPT agent that can set the image provider for me, I can ensure that the 'generate_image' command will work properly and I can proceed with testing if I am able to generate DALL-E photos and deposit them into a folder in workspace.
2023-04-27 10:51:46,718 INFO PLAN: 
2023-04-27 10:51:46,784 INFO -  Use the 'message_agent' command to send a message to a GPT agent that can set the image provider for me\n- Use the 'generate_image' command to create a DALL-E image\n- Use the 'write_to_file' command to save the image to a specified folder in workspace\n- Check if the image was successfully saved to the specified folder in workspace
2023-04-27 10:51:47,441 INFO CRITICISM: I need to make sure that the GPT agent I am sending a message to is able to set the image provider for me and that the image provider is set correctly.
2023-04-27 10:51:48,004 INFO NEXT ACTION:  COMMAND = message_agent  ARGUMENTS = {'key': 'image_provider_agent', 'message': "Please set the image provider for the 'generate_image' command."}
2023-04-27 10:57:52,390 WARNING  Warning: model not found. Using cl100k_base encoding.

**Comment by k-boikov** [comment]
The error with Dalle was fixed, it is in the master branch. A new release is coming soon.
