### ISSUE TITLE
docker  --install-plugin-deps

### ISSUE THREAD

**Issue by rcpilotp51** [Significant-Gravitas/Auto-GPT#3556]
how do you install the plugins on docker instance? Thanks

**Comment by KenWuqianghao** [comment]
> 

How did you install the requirements for the plugins? I tried to use the Instagram plugin but couldn't install the instant requirement

**Comment by jeffmercury** [comment]
The correct way to run it in docker  is like this: docker-compose run --rm auto-gpt  --install-plugin-deps. Make sure you have the plugins already configured and you update docker-compose.yml to have  :  volumes:
- ./:/app
- ./data:/app/data
- ./plugins:/app/plugins

**Comment by GuyverMack** [comment]
`docker-compose down`
and 
`docker-compose up -d`
give me
`validating C:\Users\achri\Documents\GPT\Auto-GPT-0.2.2\docker-compose.yml: services.auto-gpt Additional property redis is not allowed`
My docker-compose.yml:
```
# To boot the app run the following:
# docker-compose run auto-gpt
version: '3.9'

services:
  auto-gpt:
    depends_on:
      - redis
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    tty: true
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./plugins:/app/plugins
    redis:
    image: 'redis/redis-stack-server:latest'
```
If I change that file to exactly match kkilatesGPT above (but with spacing) I get:

```
parsing C:\Users\achri\Documents\GPT\Auto-GPT-0.2.2\docker-compose.yml: yaml: unmarshal errors:
  line 20: mapping key "image" already defined at line 7
```
also
```
PS C:\Users\achri\Documents\GPT\Auto-GPT-0.2.2> .\run.bat --install-plugin-deps
Missing packages:
beautifulsoup4>=4.12.2, colorama==0.4.6, distro==1.8.0, openai==0.27.2, playsound==1.2.2, python-dotenv==1.0.0, pyyaml==6.0, PyPDF2, python-docx, markdown, pylatexenc, readability-lxml==0.8.1, requests, tiktoken==0.3.3, gTTS==2.3.1, docker, duckduckgo-search==3.0.2, google-api-python-client, pinecone-client==2.2.1, redis, orjson==3.8.10, Pillow, selenium==4.1.4, webdriver-manager, jsonschema, charset-normalizer>=3.1.0, spacy<4.0.0,>=3.0.0, en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl, coverage, flake8, numpy, pre-commit, black, isort, gitpython==3.1.31, auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0, mkdocs, pymdown-extensions, mypy, types-Markdown, types-beautifulsoup4, types-colorama, types-Pillow, openapi-python-client==0.13.4, pytest, asynctest, pytest-asyncio, pytest-benchmark, pytest-cov, pytest-integration, pytest-mock, vcrpy@ git+https://github.com/Significant-Gravitas/vcrpy.git@master, pytest-recording, pytest-xdist
Installing missing packages...
Requirement u'en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl' looks like a filename, but the file does not exist
Could not install packages due to an EnvironmentError: Bad path: C:\Users\achri\Documents\GPT\Auto-GPT-0.2.2\en-core-web-sm @ https:\github.com\explosion\spacy-models\releases\download\en_core_web_sm-3.5.0\en_core_web_sm-3.5.0-py3-none-any.whl

You are using pip version 18.1, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\achri\Documents\GPT\Auto-GPT-0.2.2\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "autogpt\cli.py", line 70
    ctx: click.Context,
       ^
SyntaxError: invalid syntax
Press any key to continue . . .
```
``````
