### ISSUE TITLE
Traceback (most recent call last): Multiple Lines Exceptions

### ISSUE THREAD

**Issue by sentientrisk** [Significant-Gravitas/Auto-GPT#361]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Running gpt3only version. The following errors continue despite multiple rounds of troubleshooting.

### Current behavior 😯

Traceback (most recent call last):
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000025015F3F880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tctma\OneDrive\Desktop\AUTOGPT\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "C:\Users\tctma\OneDrive\Desktop\AUTOGPT\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "C:\Users\tctma\OneDrive\Desktop\AUTOGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\tctma\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.your-pinecone-region.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025015F3F880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### Expected behavior 🤔

Auto-GPT to run the script 

### Your prompt 📝

```yaml
# Paste your prompt here
```python scripts/main.py --gpt3only

**Comment by noahrollins** [comment]
same error but not gpt3 only

**Comment by noahrollins** [comment]
Hey looks like the fix is to create an account for Pinecone and then use the given API key and environment in the .env file

![image](https://user-images.githubusercontent.com/16920631/230542073-56f6a83a-6860-4b60-a7ad-98f046f92120.png)

**Comment by sushantmore894** [comment]
Sign-up to Pinecone Console and get Your API Key and Update it in .env file as well as copy region and paste in in same file and save it'll work.

**Comment by jet3004** [comment]
Same issue as OP on a fresh install, like brand new 30 min ago, never used – Pinecone API and ENV was in .env.template from the jump and saw a bunch of fixes here that said to run requirements again but still getting this..

```
Traceback (most recent call last):
  File "/Users/jet3004/Auto-GPT/scripts/main.py", line 286, in <module>
	memory = PineconeMemory()
  File "/Users/jet3004/Auto-GPT/scripts/config.py", line 17, in __call__
	cls._instances[cls] = super(
  File "/Users/jet3004/Auto-GPT/scripts/memory.py", line 30, in __init__
	if table_name not in pinecone.list_indexes():
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
	response = api_instance.list_indexes()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
	return self.callable(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
	return self.call_with_http_info(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
	return self.api_client.call_api(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
	return self.__call_api(resource_path, method,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
	response_data = self.request(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
	return self.rest_client.GET(url,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
	return self.request("GET", url,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
	r = self.pool_manager.request(method, url,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/request.py", line 74, in request
	return self.request_encode_url(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/request.py", line 96, in request_encode_url
	return self.urlopen(method, url, **extra_kw)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
	response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
	httplib_response = self._make_request(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
	conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
	super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/http/client.py", line 1282, in request
	self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/http/client.py", line 1323, in _send_request
	self.putheader(hdr, value)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
	_HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/http/client.py", line 1259, in putheader
	if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

```

**Comment by barbsblc** [comment]
> Sign-up to Pinecone Console and get Your API Key and Update it in .env file as well as copy region and paste in in same file and save it'll work.

I did all of that and I'm still getting this error message...

**Comment by Qoyyuum** [comment]
You havn't set up your Pinecone API Key and Region in your `.env` file. Please go through the README and configure properly. Closing issue.
