### ISSUE TITLE
Auto GPT data_ingestion is not working [lacking workspace_path init]

### ISSUE THREAD

**Issue by paulofalcao-hub** [Significant-Gravitas/Auto-GPT#3623]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

***python data_ingestion.py --dir previous --init --overlap 100 --max_length 2000***

Traceback (most recent call last):
  File "C:\Tools\openai\Auto-GPT\data_ingestion.py", line 96, in <module>
    main()
  File "C:\Tools\openai\Auto-GPT\data_ingestion.py", line 73, in main
    memory = get_memory(cfg, init=args.init)
  File "C:\Tools\openai\Auto-GPT\autogpt\memory\__init__.py", line 78, in get_memory
    memory = LocalCache(cfg)
  File "C:\Tools\openai\Auto-GPT\autogpt\singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Tools\openai\Auto-GPT\autogpt\memory\local.py", line 41, in __init__
    workspace_path = Path(cfg.workspace_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Current behavior 😯

Does not work because the workspace_path is not initialized

### Expected behavior 🤔

Should work :)

### Your prompt 📝

data_ingestion, it was in the prompt mode. That works.

### Your Logs 📒

Traceback (most recent call last):
  File "C:\Tools\openai\Auto-GPT\data_ingestion.py", line 96, in <module>
    main()
  File "C:\Tools\openai\Auto-GPT\data_ingestion.py", line 73, in main
    memory = get_memory(cfg, init=args.init)
  File "C:\Tools\openai\Auto-GPT\autogpt\memory\__init__.py", line 78, in get_memory
    memory = LocalCache(cfg)
  File "C:\Tools\openai\Auto-GPT\autogpt\singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Tools\openai\Auto-GPT\autogpt\memory\local.py", line 41, in __init__
    workspace_path = Path(cfg.workspace_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by paulofalcao-hub** [comment]
Added the line: **_cfg.workspace_path = Path(__file__).parent / "autogpt/auto_gpt_workspace"_** to data_ingestion.py and now it is working.

Not sure is the best fix...leave it to you guys.
