### ISSUE TITLE
(setup) Traceback (most recent call last): 

### ISSUE THREAD

**Issue by doctor-stinkinbear** [Significant-Gravitas/Auto-GPT#370]
ayo I keep getting this error when trying to use Auto-GPT, seems to start up and lets me set role / goals, but then doesn't return anything and gives me back dis error :c Thx in advance!! :) 

- Also with this, when i try to rename the .env file, for some reason the file type doesn't change and stays as TEMPLATE file instead of a .env file, not sure if its related or how to change that, cheers! 

> C:\Users\jack\Desktop\AUTOGPT\Auto-GPT>python scripts/main.py --speak
> Speak Mode:  ENABLED
> Welcome back!  Would you like me to return to being test?
> Continue with the last settings?
> Name:  test
> Role:  testtest
> Goals: ['test']
> Continue (y/n): y
> Traceback (most recent call last):
>   File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\main.py", line 286, in <module>
>     memory = PineconeMemory()
>   File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\config.py", line 17, in __call__
>     cls._instances[cls] = super(
>   File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
>     if table_name not in pinecone.list_indexes():
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
>     response = api_instance.list_indexes()
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
>     return self.callable(self, *args, **kwargs)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
>     return self.call_with_http_info(**kwargs)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
>     return self.api_client.call_api(
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
>     return self.__call_api(resource_path, method,
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
>     response_data = self.request(
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
>     return self.rest_client.GET(url,
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
>     return self.request("GET", url,
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
>     r = self.pool_manager.request(method, url,
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request    return self.request_encode_url(
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
>     return self.urlopen(method, url, **extra_kw)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
>     response = conn.urlopen(method, u.request_uri, **kw)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 244, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
>     self.putheader(hdr, value)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 224, in putheader
>     _HTTPConnection.putheader(self, header, *values)
>   File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1259, in putheader
>     if _is_illegal_header_value(values[i]):
> TypeError: expected string or bytes-like object
> 
> C:\Users\jack\Desktop\AUTOGPT\Auto-GPT>

**Comment by sushantmore894** [comment]
Sign-up to Pinecone Console and get Your API Key and Update it in .env file as well as copy region and paste in in same file and save it'll work.

**Comment by doctor-stinkinbear** [comment]
hey! I signed up and entered my API key and copy and pasted the reigion and i still come up with this error! 

Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: test
test here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
test is: test
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: test
Goal 2:
Traceback (most recent call last):
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

C:\Users\jack\Desktop\AUTOGPT\Auto-GPT>

**Comment by PrismInvestors** [comment]
I get the same error with Pinecone on initial setup.

**Comment by dorkerdevil** [comment]
same issue

**Comment by DevCorator** [comment]
Getting the same problem

**Comment by abdoulsalamally** [comment]
Same here, any solution to this?

**Comment by heychintan** [comment]
getting same issue, eventho added pinecone api key+env and eleven labs key as well.

**Comment by rowbot1** [comment]
same error -     if _is_illegal_header_value(values[i]):

**Comment by AbhisheK5KhAtri** [comment]
Getting Same error

**Comment by danielwe123** [comment]
It seems that the .env.template file wasn't renamed properly. I had a similar issue, and could only fix it by renaming through the terminal. 

1. First, navigate to the auto-gpt folder and run the ls -a command in the terminal to list all files, including hidden ones. You should see the .env.template file.
2. Rename the .env.template file to .env by running the command mv .env.template .env.
3. Use the ls -a command again to verify that the file has been renamed correctly.

Additionally, if you don't have access to the GPT-4 API (currently only available to waitlist members), you can use GPT-3 by running the following command:

python scripts/main.py --gpt3only

I hope this helps other users who face similar issues. 

Happy coding!

**Comment by rowbot1** [comment]
Had done this but still same issue unfortunately 

`total 80
drwxrwxr-x  8 x2027756 x2027756  4096 Apr  7 02:19 .
drwxr-xr-x 31 x2027756 x2027756  4096 Apr  7 01:19 ..
-rw-rw-r--  1 x2027756 x2027756   283 Apr  7 01:19 ai_settings.yaml
drwxrwxr-x  2 x2027756 x2027756  4096 Apr  7 01:20 auto_gpt_workspace
-rw-rw-r--  1 x2027756 x2027756  1710 Apr  7 01:19 CONTRIBUTING.md
-rw-rw-r--  1 x2027756 x2027756   114 Apr  7 01:19 Dockerfile
-rw-rw-r--  1 x2027756 x2027756   245 Apr  7 01:28 .env
-rw-rw-r--  1 x2027756 x2027756   388 Apr  7 01:19 .env.template.old
drwxrwxr-x  8 x2027756 x2027756  4096 Apr  7 01:19 .git
drwxrwxr-x  4 x2027756 x2027756  4096 Apr  7 01:19 .github
-rw-rw-r--  1 x2027756 x2027756   176 Apr  7 01:19 .gitignore
-rw-rw-r--  1 x2027756 x2027756  1077 Apr  7 01:19 LICENSE
drwxrwxr-x  3 x2027756 x2027756  4096 Apr  7 01:19 outputs
-rw-rw-r--  1 x2027756 x2027756 14175 Apr  7 01:19 README.md
-rw-rw-r--  1 x2027756 x2027756   289 Apr  7 01:19 requirements.txt
drwxrwxr-x  4 x2027756 x2027756  4096 Apr  7 01:20 scripts
drwxrwxr-x  2 x2027756 x2027756  4096 Apr  7 01:19 tests
`

I have access to GPT4

**Comment by danielwe123** [comment]
@rowbot1 could you pls copy & paste your terminal logs after running python scripts/main.py --gpt3only

**Comment by heychintan** [comment]
Renaming the env again worked for me. Set the file open app - text file as default on mac.

**Comment by rowbot1** [comment]
Continue (y/n): y
Traceback (most recent call last):
  File "scripts/main.py", line 286, in <module>
    memory = PineconeMemory()
  File "/home/rowbot/Desktop/Auto-GPT/scripts/config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "/home/rowbot/Desktop/Auto-GPT/scripts/memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/home/rowbot/.local/lib/python3.8/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1297, in _send_request
    self.putheader(hdr, value)
  File "/home/rowbot/.local/lib/python3.8/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/lib/python3.8/http/client.py", line 1233, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

OPENAI_API_KEY=sk-JJ.......
ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL="gpt-4"
FAST_LLM_MODEL="gpt-3.5-turbo"
PINECONE_API_Key=7af......
PINECONE_ENV=us-east1-gcp

**Comment by ETH3R3AL93** [comment]
Is it possible to choose to use Pinecone and default to local memory as it did originally? Not sure if this is counter intuitive.

**Comment by danielwe123** [comment]
@rowbot1 Did you already create an index in pinecone? If so, try deleting & run python scripts/main.py --gpt3only again. 

Another question: Did you try running python scripts/main.py --gpt3only, or python scripts/main.py only?

**Comment by rowbot1** [comment]
I have an index in pinecone, deleted it, created a new one,  also tried running --gpt3only but still the same issue

**Comment by doctor-stinkinbear** [comment]
still having issues, created an index in pinecone and still getting 

Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: test
test here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
test is: test
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: write hello back to me
Goal 2:
Traceback (most recent call last):
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "C:\Users\jack\Desktop\AUTOGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\Users\jack\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

C:\Users\jack\Desktop\AUTOGPT\Auto-GPT>


also im on PC

**Comment by doctor-stinkinbear** [comment]
managed to get it working with another PC - the issue I am having is that when trying to change the name of the .env file windows does not prompt to change the file type. When sending the .env file from the other PC that it does recognise the file type it just calls the type 'file' instead of .env - with this pinecone is not creating the index automatically to get it working.

**Comment by doctor-stinkinbear** [comment]
update: fixed it, opened the .env.template in pycharm and it prompted me to DL extentions, renamed file in pycharm and it created the pinecone index <3 thx

**Comment by rowbot1** [comment]
wow i figured it out - typo! 

I had PINECONE_API_Key, instead of PINECONE_API_KEY - D'oh!

Thanks for your help
