### ISSUE TITLE
json.loads fails and crashes in update_running_summary

### ISSUE THREAD

**Issue by matiasvlevi** [Significant-Gravitas/Auto-GPT#3729]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

I used the latest docker image with the stable branch, no arguments specified.

Multiple configurations (ai_settings.yaml) had this issue.

I tried adding a `try/except` around the `json.load` and set `content_dict` to an empty dictionary, the loop was able to continue, but it constantly tried to do the same thing and hit the `except` case.

I had this issue happen after successful commands (`write_file`, `analyze_code`, `message_agent`).

I also had these settings in the `.env` file

```
EXECUTE_LOCAL_COMMANDS=True
RESTRICT_TO_WORKSPACE=False

HEADLESS_BROWSER=True
USE_WEB_BROWSER=chrome

TEMPERATURE=1
```

### Current behavior 😯

The application crashes with an error from `update_running_summary` in `./autogpt/memory_management/summary_memory.py`

It looks like the `event["content"]` value can't be parsed to remove the "thoughts" property from it

Here is the traceback I get 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 94, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/app/autogpt/llm/chat.py", line 166, in chat_with_ai
    agent.summary_memory = update_running_summary(
  File "/app/autogpt/memory_management/summary_memory.py", line 76, in update_running_summary
    content_dict = json.loads(event["content"])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Expected behavior 🤔

The `event["content"]` value should parse correctly

or

The loop should continue after a `json.loads` call fails, and handle the error accordingly

### Your prompt 📝

```yaml
ai_goals:
- Analyze social media trends, online searches, and other relevant data to identify
  upcoming popular tourist locations.
- Provide personalized recommendations based on the traveler's interests, preferences,
  and travel history.
- Offer practical travel tips such as local customs, visa requirements, and transportation
  options to enhance the traveler's overall experience.
- Ensure up-to-date information on attractions, events, and travel restrictions to
  prevent any inconveniences caused by unexpected changes.
- Collaborate with local travel experts to provide authentic insights into the culture,
  history, and lifestyle of the chosen destination.
ai_name: TouristGPT
ai_role: an AI assistant that helps travelers discover upcoming popular tourist locations
  by providing relevant information, personalized recommendations, and travel tips.
api_budget: 0.0

```

### Your Logs 📒

```log
2023-05-03 05:28:55,138 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
2023-05-03 05:28:56,475 INFO SYSTEM:  Command google returned: [
    {
        "title": "The 23 Best Places To Travel Around The World In 2023, Chosen ... - Forbes",
        "href": "https://www.forbes.com/sites/laurabegleybloom/2023/03/30/the-23-best-places-to-travel-in-2023-chosen-by-the-experts/",
        "body": "The 23 Best Places To Travel Around The World In 2023, Chosen By The Experts More From Forbes Apr 30, 2023,06:35pm EDT Unexplored Greenland - How Pata Degerman's Expeditions Transform..."
    },
    {
        "title": "The 50 Best Places to Travel in 2023 - travelandleisure.com",
        "href": "https://www.travelandleisure.com/best-places-to-go-2023-6827750",
        "body": "Istanbul and Bodrum are both rightly popular, but U.S. travelers will find much to love in other pockets of this diverse country — including this inland part of southwestern Anatolia, which..."
    },
    {
        "title": "Here They Are: The 23 Best Places To Travel In 2023 - Forbes",
        "href": "https://www.forbes.com/sites/christopherelliott/2022/10/22/here-they-are-the-23-best-places-to-travel-in-2023/",
        "body": "Here are the 23 best places to travel in 2023, according to OvationNetwork's list of the top leisure destinations, compiled exclusively for FORBES. Queenstown, New Zealand Marrakesh,..."
    },
    {
        "title": "Where to travel in 2023: The best destinations to visit | CNN",
        "href": "https://www.cnn.com/travel/article/where-to-travel-best-destinations-2023/index.html",
        "body": "Where to travel in 2023: The best destinations to visit CNN Travel staff Updated 4:12 AM EST, Mon January 2, 2023 Link Copied! Ottawa, Canada: In Ottawa, Rideau Canal becomes the..."
    },
    {
        "title": "Lonely Planet reveals its top destinations for 2023 | CNN",
        "href": "https://www.cnn.com/travel/article/lonely-planet-best-in-travel-2023/index.html",
        "body": "Lonely Planet Best in Travel 2023: The travel brand has revealed its destination picks for 2023. One of them is the southern European island nation of Malta (pictured). Click through to see the rest."
    },
    {
        "title": "Best global travel destinations for 2023, per National Geographic",
        "href": "https://www.usatoday.com/story/travel/news/2022/11/02/travel-destinations-2023-national-geographic/10639068002/",
        "body": "National Geographic has suggested 25 top destinations throughout the world for those looking to explore in 2023. The recommendations, released Oct. 26, range from traditional U.S. destinations ..."
    },
    {
        "title": "The top travel destinations for 2023, according to experts",
        "href": "https://www.washingtonpost.com/travel/tips/2023-travel-trends-destinations/",
        "body": "Of the Top 5 most booked domestic destinations on the travel booking platform Hopper, four are out west: Las Vegas, Denver, Los Angeles and Phoenix. For Skyscanner bookings, Las Vegas and Los..."
    },
    {
        "title": "23 Destinations to Put on Your Radar for 2023 - Oliver's Travels",
        "href": "https://www.oliverstravels.com/blog/23-destinations-for-2023/",
        "body": "So, we thought we'd deliver a dose of travel inspiration for 2023 holidays, because we all deserve a little something to look forward to. A soirée in the French Riviera, perhaps? Biarritz A chic seaside town on France's Basque Coast, Biarritz is a magnet for surfers, art lovers and foodies."
    }
]
2023-05-03 05:29:22,336 INFO  THOUGHTS: Now that I have a list of popular upcoming tourist destinations in 2023, I can analyze it further to identify locations that match the traveler's interests and travel history.
2023-05-03 05:29:22,821 INFO REASONING: The search results provide an initial list of destinations that I can analyze further to provide personalized recommendations.
2023-05-03 05:29:23,254 INFO PLAN: 
2023-05-03 05:29:23,308 INFO -  Save the search results to a file for future reference
2023-05-03 05:29:23,572 INFO -  Analyze the data to identify locations that are relevant to the traveler's interests and travel history
2023-05-03 05:29:23,922 INFO CRITICISM: I need to ensure I filter the data correctly to provide accurate and relevant recommendations.
2023-05-03 05:29:24,260 INFO NEXT ACTION:  COMMAND = write_to_file  ARGUMENTS = {'filename': '/app/autogpt/auto_gpt_workspace/popular_destinations.txt', 'text': '["The 23 Best Places To Travel Around The World In 2023, Chosen By The Experts", "The 50 Best Places to Travel in 2023", "Here They Are: The 23 Best Places To Travel In 2023", "Where to travel in 2023: The best destinations to visit", "Lonely Planet reveals its top destinations for 2023", "Best global travel destinations for 2023, per National Geographic", "The top travel destinations for 2023, according to experts", "23 Destinations to Put on Your Radar for 2023 - Oliver\'s Travels"]'}
2023-05-03 05:29:24,899 INFO  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
2023-05-03 05:29:24,900 INFO  Asking user via keyboard...
2023-05-03 05:29:30,199 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
2023-05-03 05:29:30,353 INFO SYSTEM:  Command write_to_file returned: File written to successfully.
2023-05-03 05:29:51,684 INFO  THOUGHTS: To provide personalized recommendations, I need to understand the traveler's interests and preferences. I'll use the GPT Agent to ask for this information.
2023-05-03 05:29:52,105 INFO REASONING: As an AI assistant, I need to understand the traveler's interests and preferences to provide accurate and relevant recommendations. The GPT Agent can help me gather this information by asking questions and interacting with the traveler.
2023-05-03 05:29:52,635 INFO PLAN: 
2023-05-03 05:29:52,681 INFO -  Use the message_agent command to ask the traveler about their interests and preferences
2023-05-03 05:29:53,037 INFO -  Store the traveler's responses for future use when providing recommendations
2023-05-03 05:29:53,313 INFO CRITICISM: I need to ensure that the questions are clear and relevant to the traveler's experience.
2023-05-03 05:29:53,666 INFO NEXT ACTION:  COMMAND = message_agent  ARGUMENTS = {'key': 'personalization_agent', 'message': 'Please tell me more about your interests and preferences. What type of travel experience are you looking for?'}
2023-05-03 05:29:54,129 INFO  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
2023-05-03 05:29:54,129 INFO  Asking user via keyboard...
2023-05-03 05:29:58,957 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
2023-05-03 05:29:59,164 INFO SYSTEM:  Command message_agent returned: Invalid key, must be an integer.
2023-05-03 05:30:26,877 INFO  THOUGHTS: I need to create a new GPT Agent to gather information about the traveler's interests and preferences. I'll use the start_agent command to create a new Agent for this task.
2023-05-03 05:30:27,403 INFO REASONING: As an AI assistant, I need to understand the traveler's interests and preferences to provide accurate and relevant recommendations. A dedicated GPT Agent can help me gather this information by asking questions and interacting with the traveler.
2023-05-03 05:30:27,936 INFO PLAN: 
2023-05-03 05:30:27,981 INFO -  Use the start_agent command to create a new Agent for the task of gathering information about the traveler's interests and preferences
2023-05-03 05:30:28,341 INFO -  Store the traveler's responses for future use when providing recommendations
2023-05-03 05:30:28,669 INFO CRITICISM: I need to ensure that the questions are clear and relevant to the traveler's experience, and that the Agent is able to handle different types of responses from the traveler.
2023-05-03 05:30:29,100 INFO NEXT ACTION:  COMMAND = start_agent  ARGUMENTS = {'name': 'personalization_agent', 'task': "Gather information about the traveler's interests and preferences", 'prompt': 'Please tell me more about your interests and preferences. What type of travel experience are you looking for?'}
2023-05-03 05:30:37,610 INFO SYSTEM:  Command start_agent returned: Agent personalization_agent created with key 0. First response: I'm an AI language model, so I don't have personal interests or preferences. However, I can help you plan and recommend different travel experiences based on your preferences and interests. Whether you're looking for a relaxing beach vacation, a cultural city break, or an adventure-filled getaway, I'm here to assist you in finding the best travel experience for you. So please tell me more about what you like and what you're looking for, and I'll do my best to provide you with personalized recommendations.
2023-05-03 05:31:05,279 INFO  THOUGHTS: Now that I have a new GPT Agent, I'll use the message_agent command to prompt the Agent to ask more questions and gather information about the traveler's interests and preferences.
2023-05-03 05:31:05,807 INFO REASONING: As an AI assistant, I need to understand the traveler's interests and preferences to provide accurate and relevant recommendations. By using the GPT Agent, I can ask open-ended questions and receive detailed responses from the traveler.
2023-05-03 05:31:06,370 INFO PLAN: 
2023-05-03 05:31:06,444 INFO -  Use the message_agent command to prompt the Agent to ask more questions and gather information about the traveler's interests and preferences
2023-05-03 05:31:06,863 INFO -  Store the traveler's responses for future use when providing recommendations
2023-05-03 05:31:07,141 INFO CRITICISM: I need to ensure that the questions are clear and relevant to the traveler's experience, and that the Agent is able to handle different types of responses from the traveler.
2023-05-03 05:31:07,595 INFO NEXT ACTION:  COMMAND = message_agent  ARGUMENTS = {'key': 0, 'message': 'Can you tell me more about the type of travel that you prefer? Are you looking for a relaxing beach vacation or a cultural city break? Do you prefer nature or adventure activities, or a mix of both?'}
2023-05-03 05:31:14,468 INFO SYSTEM:  Command message_agent returned: As an AI language model, I do not have personal preferences or interests as I am not capable of experiencing travel and related activities like humans. I am designed to assist you in planning and organizing your travel experiences to meet your individual preferences. 

Therefore, please let me know what types of experiences you are interested in, such as relaxing on a beach, exploring nature, experiencing different cultures or trying adventure activities, and I can provide recommendations to help create a personalized itinerary for you.

```

**Comment by Princebaskar** [comment]
same for me

**Comment by matiasvlevi** [comment]
Closing this as a it is a duplicate of issue #3672
