### ISSUE TITLE
Error when running ./run.sh in debian on x86_64

### ISSUE THREAD

**Issue by drbree82** [Significant-Gravitas/Auto-GPT#3732]
ll packages are installed.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/drbree82/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/drbree82/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drbree82/Auto-GPT/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/home/drbree82/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/home/drbree82/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/drbree82/Auto-GPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/drbree82/Auto-GPT/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/home/drbree82/Auto-GPT/autogpt/agent/agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "/home/drbree82/Auto-GPT/autogpt/llm/__init__.py", line 11, in <module>
    from autogpt.llm.chat import chat_with_ai, create_chat_message, generate_context
  File "/home/drbree82/Auto-GPT/autogpt/llm/chat.py", line 12, in <module>
    from autogpt.memory_management.store_memory import (
  File "/home/drbree82/Auto-GPT/autogpt/memory_management/store_memory.py", line 1, in <module>
    from autogpt.json_utils.utilities import (
  File "/home/drbree82/Auto-GPT/autogpt/json_utils/utilities.py", line 33, in <module>
    def validate_json(json_object: object, schema_name: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Press any key to continue...

**Comment by parveen4646** [comment]
replace | with or in  line 33 and 60 in autogpt/jasonutilityutility.py

**Comment by Lesani** [comment]
have the same on Windows

```git status
On branch stable
Your branch is up to date with 'origin/stable'.```

**Comment by k-boikov** [comment]
Please update to python 3.10 or higher, 3.9 is not officially supported.

**Comment by Lesani** [comment]
> Please update to python 3.10 or higher, 3.9 is not officially supported.

yea but THERE IS a check for that in code, that tells you you are running a too-old version of python. The check however is AFTER the problem occurs. Instead of blindly closing this, how about moving the check up, so it can perform its function?

**Comment by k-boikov** [comment]
Good idea, will investigate.
