### ISSUE TITLE
First run (Windows)... TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by wazzubrad23** [Significant-Gravitas/Auto-GPT#3741]
Guys, am getting this after running .\run.bat for the first time;

Traceback (most recent call last):
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Auto-GPT-master\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\wazzu\anaconda3\envs\auto-gpt\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Auto-GPT-master\autogpt\cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "C:\Auto-GPT-master\autogpt\main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT-master\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Auto-GPT-master\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Auto-GPT-master\autogpt\app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "C:\Auto-GPT-master\autogpt\agent\agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "C:\Auto-GPT-master\autogpt\llm\__init__.py", line 1, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "C:\Auto-GPT-master\autogpt\llm\api_manager.py", line 7, in <module>
    from autogpt.logs import logger
  File "C:\Auto-GPT-master\autogpt\logs.py", line 12, in <module>
    from autogpt.speech import say_text
  File "C:\Auto-GPT-master\autogpt\speech\__init__.py", line 2, in <module>
    from autogpt.speech.say import say_text
  File "C:\Auto-GPT-master\autogpt\speech\say.py", line 34, in <module>
    def _get_voice_engine(config: Config) -> tuple[VoiceBase, VoiceBase]:
TypeError: 'type' object is not subscriptable
Press any key to continue . . .
(auto-gpt) PS C:\Auto-GPT-master>

**Comment by k-boikov** [comment]
Smells like old python version. Update to 3.10 or higher.

**Comment by wazzubrad23** [comment]
Guys, I downloaded and installed 3.10, restarted, when I run python —version, it still shows I am on 3.8. eBay am I missing?

Brad Schmidt
Abstract Residential Design + Build
(208) 906-1650
www.abstractrd.com (http://www.abstractrd.com)

**Comment by fire717** [comment]
> Guys, I downloaded and installed 3.10, restarted, when I run python —version, it still shows I am on 3.8. what am I missing?

use conda to change env is better

**Comment by anonhostpi** [comment]
@wazzubrad23 try `python3` instead of `python`
