### ISSUE TITLE
Traceback on start

### ISSUE THREAD

**Issue by Subduction421** [Significant-Gravitas/Auto-GPT#3765]
I'm also getting a long traceback when trying to start it on Windows.  I've tried most of the fixes listed above with no progress.  any suggestions?  Thanks in advance!

python -m autogpt
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\agent\agent.py", line 5, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\agent\agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\llm\__init__.py", line 1, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\llm\api_manager.py", line 7, in <module>
    from autogpt.logs import logger
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\logs.py", line 14, in <module>
    from autogpt.speech import say_text
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\speech\__init__.py", line 2, in <module>
    from autogpt.speech.say import say_text
  File "C:\Users\Dave\Desktop\autogpt\Auto-GPT\autogpt\speech\say.py", line 34, in <module>
    def _get_voice_engine(config: Config) -> tuple[VoiceBase, VoiceBase]:
TypeError: 'type' object is not subscriptable

**Comment by k-boikov** [comment]
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/3741
