### ISSUE TITLE
No such file or directory: '/app/autogpt/config/../../azure.yaml'

### ISSUE THREAD

**Issue by diaohonghui** [Significant-Gravitas/Auto-GPT#3778]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

when running with docker using azure, system replys 
All packages are installed.
time="2023-05-04T17:04:58+08:00" level=warning msg="Found orphan containers ([auto-gpt-redis-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/app/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/app/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/app/autogpt/agent/agent.py", line 5, in <module>
    from autogpt.app import execute_command, get_command
  File "/app/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/app/autogpt/agent/agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "/app/autogpt/llm/__init__.py", line 11, in <module>
    from autogpt.llm.chat import chat_with_ai, create_chat_message, generate_context
  File "/app/autogpt/llm/chat.py", line 13, in <module>
    from autogpt.memory_management.store_memory import (
  File "/app/autogpt/memory_management/store_memory.py", line 1, in <module>
    from autogpt.json_utils.utilities import (
  File "/app/autogpt/json_utils/utilities.py", line 11, in <module>
    CFG = Config()
  File "/app/autogpt/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/app/autogpt/config/config.py", line 57, in __init__
    self.load_azure_config()
  File "/app/autogpt/config/config.py", line 185, in load_azure_config
    with open(config_file) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/app/autogpt/config/../../azure.yaml'

### Current behavior 😯

keep on telling me"No such file or directory: '/app/autogpt/config/../../azure.yaml' "

### Expected behavior 🤔

run properly

### Your prompt 📝

```yaml
# Paste your prompt here
```
No prompt using

### Your Logs 📒

```log
<insert your logs here>
```
No log on local machine

**Comment by ntindle** [comment]
Can you try this again and reopen if it persistes

**Comment by waddock** [comment]
Did this get fixed as I have the same issue.
