### ISSUE TITLE
Crashes after the 5 goals submission

### ISSUE THREAD

**Issue by j4rv1s1on** [Significant-Gravitas/Auto-GPT#3825]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

So this crash happens right when the AI starts the job, i put the goals and then dies, what is this problem related to? thanks in advance guys.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
Using memory of type:  LocalCache
Using Browser:  chrome
Warning: Bing-Search-Plugin is not fully functional. Please set the SEARCH_ENGINE and BING_API_KEY environment variables.
Auto-GPT-Email-Plugin - 0.1.3 - Email plugin not loaded, because EMAIL_PASSWORD or EMAIL_ADDRESS were not set in env.
Warning: News-Search-Plugin is not fully functional. Please set the NEWSAPI_API_KEY environment variable.
Auto-GPT-Scenex-Plugin - 0.0.1 - SceneX plugin not loaded, because SCENEX_API_KEY was not set in env.
Traceback (most recent call last):
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/chat/completions': No scheme supplied. Perhaps you meant https:///chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Auto-GPT-stable\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Auto-GPT-stable\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Program Files\Auto-GPT-stable\autogpt\main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "C:\Program Files\Auto-GPT-stable\autogpt\agent\agent.py", line 94, in start_interaction_loop
    assistant_reply = chat_with_ai(
                      ^^^^^^^^^^^^^
  File "C:\Program Files\Auto-GPT-stable\autogpt\llm\chat.py", line 237, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Auto-GPT-stable\autogpt\llm\llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Auto-GPT-stable\autogpt\llm\api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\santa\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL '/chat/completions': No scheme supplied. Perhaps you meant https:///chat/completions?
```

**Comment by j4rv1s1on** [comment]
Is this like a misconfiguration issue with the openai library?

**Comment by martinkeat** [comment]
ditto

**Comment by j4rv1s1on** [comment]
Charizard

**Comment by j4rv1s1on** [comment]
SOLVED. 

for anyone experiencing a similar issue, try to comment out the line **OPEN_AI_BASE=blablabla** in your .env file.
That did the job for me.
