### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by SAMALAMA37** [Significant-Gravitas/Auto-GPT#383]
### Duplicates

- [ ] I have searched the existing issues

### Steps to reproduce 🕹

Everytime after giving instructions it gives out error:
Traceback (most recent call last):
  File "C:\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "C:\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "C:\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\Users\emild\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
Btw i use gtp-3.5turbo because i haven't got accepted on gpt-4 api waitlist yet

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by miolamio** [comment]
Same issue, the latest version:

Traceback (most recent call last):
  File "/Users/vasilly/Lab/Auto-GPT/scripts/main.py", line 286, in <module>
    memory = PineconeMemory()
  File "/Users/vasilly/Lab/Auto-GPT/scripts/config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "/Users/vasilly/Lab/Auto-GPT/scripts/memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/http/client.py", line 1262, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

**Comment by cvarrichio** [comment]
Same issue here.

**Comment by aysaysbaby** [comment]
Had the same, when creating a pinecone.io account and adding the API key to my .env file I now get this message:
 API Rate Limit Reached. Waiting 10 seconds...

**Comment by mrpnectar** [comment]
> Had the same, when creating a pinecone.io account and adding the API key to my .env file I now get this message:
> API Rate Limit Reached. Waiting 10 seconds...

I had this issue. It may be due to your .env file. My fix was to set the variables in terminal each session:
In your app's directory, run this in terminal:
export OPENAI_API_KEY="YOUR API KEY"
export PINECONE_API_KEY="YOUR API KEY"
export PINECONE_ENV="YOUR PINECONE REGION"
python3 scripts/main.py

**Comment by barangulesen** [comment]
Traceback (most recent call last):
  File "/Users/bg/Auto-GPT/scripts/main.py", line 286, in <module>
    memory = PineconeMemory()
  File "/Users/bg/Auto-GPT/scripts/config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "/Users/bg/Auto-GPT/scripts/memory.py", line 31, in __init__
    pinecone.create_index(table_name, dimension=dimension, metric=metric, pod_type=pod_type)
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/manage.py", line 118, in create_index
    api_instance.create_index(create_request=CreateRequest(
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api/index_operations_api.py", line 370, in __create_index
    return self.call_with_http_info(**kwargs)
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 207, in __call_api
    raise e
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/api_client.py", line 459, in request
    return self.rest_client.POST(url,
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 271, in POST
    return self.request("POST", url,
  File "/Users/bg/opt/anaconda3/lib/python3.9/site-packages/pinecone/core/client/rest.py", line 230, in request
    raise ApiException(http_resp=r)
pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Tue, 11 Apr 2023 23:19:08 GMT', 'x-envoy-upstream-service-time': '1545', 'content-length': '131', 'server': 'envoy'})
HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.
