### ISSUE TITLE
ModuleNotFoundError: No module named 'distro'

### ISSUE THREAD

**Issue by lqtaaaa** [Significant-Gravitas/Auto-GPT#3881]
I had this same problem, after forking the repository, I used gitpod to open and run . /run.sh, and it prompted
Traceback (most recent call last):
  File "/nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/workspace/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/workspace/Auto-GPT/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/workspace/Auto-GPT/autogpt/agent/agent_manager.py", line 6, in <module>
    from autogpt.config.config import Config
  File "/workspace/Auto-GPT/autogpt/config/__init__.py", line 4, in <module>
    from autogpt.config.ai_config import AIConfig
  File "/workspace/Auto-GPT/autogpt/config/ai_config.py", line 12, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
How to solve this problem?

_Originally posted by @lqtaaaa in https://github.com/Significant-Gravitas/Auto-GPT/issues/3088#issuecomment-1534139054_

**Comment by mc856** [comment]
I had this same issue!

**Comment by mc856** [comment]
I tried pip install distro, but it still raised error.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
gitpod /workspace/Auto-GPT (stable) $ pip install distro
Collecting distro
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Installing collected packages: distro
Successfully installed distro-1.8.0

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: /home/gitpod/.pyenv/versions/3.11.1/bin/python3 -m pip install --upgrade pip
gitpod /workspace/Auto-GPT (stable) $ ./run.sh
Missing packages:
distro, pre-commit, auto-gpt-plugin-template, mkdocs, pymdown-extensions, openapi-python-client, pytest-integration, vcrpy, pytest-recording
Installing missing packages...

**Comment by k-boikov** [comment]
Please reopen following the Bug report template.
