### ISSUE TITLE
Cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by koltregaskes** [Significant-Gravitas/Auto-GPT#398]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Run main.py

### Current behavior 😯

I get this error when running main.py:

"C:/Program Files/Python311/python.exe" "e:/My Drive/Coding/Python/Auto-GPT/scripts/main.py"
Traceback (most recent call last):
  File "C:\Users\kolin\AppData\Roaming\Python\Python311\site-packages\dirtyjson\attributed_containers.py", line 7, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Program Files\Python311\Lib\collections\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\My Drive\Coding\Python\Auto-GPT\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "e:\My Drive\Coding\Python\Auto-GPT\scripts\commands.py", line 8, in <module>
    import ai_functions as ai
  File "e:\My Drive\Coding\Python\Auto-GPT\scripts\ai_functions.py", line 5, in <module>
    from json_parser import fix_and_parse_json
  File "e:\My Drive\Coding\Python\Auto-GPT\scripts\json_parser.py", line 1, in <module>
    import dirtyjson
  File "C:\Users\kolin\AppData\Roaming\Python\Python311\site-packages\dirtyjson\__init__.py", line 33, in <module>
    from .loader import DirtyJSONLoader
  File "C:\Users\kolin\AppData\Roaming\Python\Python311\site-packages\dirtyjson\loader.py", line 8, in <module>
    from dirtyjson.attributed_containers import AttributedDict, AttributedList
  File "C:\Users\kolin\AppData\Roaming\Python\Python311\site-packages\dirtyjson\attributed_containers.py", line 11, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

### Expected behavior 🤔

To run Auto-GPT and ask for a name.

**Comment by Qoyyuum** [comment]
Please pull latest changes from stable release and try again. This issue is resolved.
