### ISSUE TITLE
crash on token length

### ISSUE THREAD

**Issue by ram-sh** [Significant-Gravitas/Auto-GPT#4012]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Hello, 

its an ongoing issue, not the first time we encounter this however its still crashing the system.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
CRITICISM:  I should have checked if the Pinecone CLI was installed on this system before attempting to check my permissions.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'pip install pinecone-cli'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
  Executing command 'pip install pinecone-cli' in working directory '/workspace/Auto-GPT/autogpt/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'Defaulting to user installation because normal site-packages is not writeable\nRequirement already satisfied: pinecone-cli in /home/vscode/.local/lib/python3.10/site-packages (0.5.2)\nRequirement already satisfied: click in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (8.1.3)\nRequirement already satisfied: pandas in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (2.0.1)\nRequirement already satisfied: numpy in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (1.24.3)\nRequirement already satisfied: openai in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (0.27.2)\nRequirement already satisfied: pinecone-client in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (2.2.1)\nRequirement already satisfied: matplotlib in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (3.7.1)\nRequirement already satisfied: scikit-learn in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (1.2.2)\nRequirement already satisfied: beautifulsoup4 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (4.12.2)\nRequirement already satisfied: nltk in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (3.8.1)\nRequirement already satisfied: rich in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (13.3.5)\nRequirement already satisfied: python-dotenv in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-cli) (1.0.0)\nRequirement already satisfied: soupsieve>1.2 in /home/vscode/.local/lib/python3.10/site-packages (from beautifulsoup4->pinecone-cli) (2.4.1)\nRequirement already satisfied: contourpy>=1.0.1 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (1.0.7)\nRequirement already satisfied: cycler>=0.10 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (0.11.0)\nRequirement already satisfied: fonttools>=4.22.0 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (4.39.3)\nRequirement already satisfied: kiwisolver>=1.0.1 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (1.4.4)\nRequirement already satisfied: packaging>=20.0 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (23.1)\nRequirement already satisfied: pillow>=6.2.0 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (9.5.0)\nRequirement already satisfied: pyparsing>=2.3.1 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (3.0.9)\nRequirement already satisfied: python-dateutil>=2.7 in /home/vscode/.local/lib/python3.10/site-packages (from matplotlib->pinecone-cli) (2.8.2)\nRequirement already satisfied: joblib in /home/vscode/.local/lib/python3.10/site-packages (from nltk->pinecone-cli) (1.2.0)\nRequirement already satisfied: regex>=2021.8.3 in /home/vscode/.local/lib/python3.10/site-packages (from nltk->pinecone-cli) (2023.5.5)\nRequirement already satisfied: tqdm in /home/vscode/.local/lib/python3.10/site-packages (from nltk->pinecone-cli) (4.65.0)\nRequirement already satisfied: requests>=2.20 in /home/vscode/.local/lib/python3.10/site-packages (from openai->pinecone-cli) (2.29.0)\nRequirement already satisfied: aiohttp in /home/vscode/.local/lib/python3.10/site-packages (from openai->pinecone-cli) (3.8.4)\nRequirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.10/site-packages (from pandas->pinecone-cli) (2023.3)\nRequirement already satisfied: tzdata>=2022.1 in /home/vscode/.local/lib/python3.10/site-packages (from pandas->pinecone-cli) (2023.3)\nRequirement already satisfied: pyyaml>=5.4 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (6.0)\nRequirement already satisfied: loguru>=0.5.0 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (0.7.0)\nRequirement already satisfied: typing-extensions>=3.7.4 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (4.5.0)\nRequirement already satisfied: dnspython>=2.0.0 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (2.3.0)\nRequirement already satisfied: urllib3>=1.21.1 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (1.26.15)\nRequirement already satisfied: grpcio>=1.44.0 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (1.54.0)\nRequirement already satisfied: grpc-gateway-protoc-gen-openapiv2==0.1.0 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (0.1.0)\nRequirement already satisfied: googleapis-common-protos>=1.53.0 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (1.56.4)\nRequirement already satisfied: lz4>=3.1.3 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (4.3.2)\nRequirement already satisfied: protobuf==3.19.3 in /home/vscode/.local/lib/python3.10/site-packages (from pinecone-client->pinecone-cli) (3.19.3)\nRequirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/vscode/.local/lib/python3.10/site-packages (from rich->pinecone-cli) (2.2.0)\nRequirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/vscode/.local/lib/python3.10/site-packages (from rich->pinecone-cli) (2.15.1)\nRequirement already satisfied: scipy>=1.3.2 in /home/vscode/.local/lib/python3.10/site-packages (from scikit-learn->pinecone-cli) (1.10.1)\nRequirement already satisfied: threadpoolctl>=2.0.0 in /home/vscode/.local/lib/python3.10/site-packages (from scikit-learn->pinecone-cli) (3.1.0)\nRequirement already satisfied: mdurl~=0.1 in /home/vscode/.local/lib/python3.10/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->pinecone-cli) (0.1.2)\nRequirement already satisfied: six>=1.5 in /home/vscode/.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->pinecone-cli) (1.16.0)\nRequirement already satisfied: charset-normalizer<4,>=2 in /home/vscode/.local/lib/python3.10/site-packages (from requests>=2.20->openai->pinecone-cli) (3.1.0)\nRequirement already satisfied: idna<4,>=2.5 in /home/vscode/.local/lib/python3.10/site-packages (from requests>=2.20->openai->pinecone-cli) (3.4)\nRequirement already satisfied: certifi>=2017.4.17 in /home/vscode/.local/lib/python3.10/site-packages (from requests>=2.20->openai->pinecone-cli) (2022.12.7)\nRequirement already satisfied: attrs>=17.3.0 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (23.1.0)\nRequirement already satisfied: multidict<7.0,>=4.5 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (6.0.4)\nRequirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (4.0.2)\nRequirement already satisfied: yarl<2.0,>=1.0 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (1.9.2)\nRequirement already satisfied: frozenlist>=1.1.1 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (1.3.3)\nRequirement already satisfied: aiosignal>=1.1.2 in /home/vscode/.local/lib/python3.10/site-packages (from aiohttp->openai->pinecone-cli) (1.3.1)\n' STDERR: b''
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/workspace/Auto-GPT/autogpt/main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "/workspace/Auto-GPT/autogpt/agent/agent.py", line 94, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/workspace/Auto-GPT/autogpt/llm/chat.py", line 166, in chat_with_ai
    agent.summary_memory = update_running_summary(
  File "/workspace/Auto-GPT/autogpt/memory_management/summary_memory.py", line 114, in update_running_summary
    current_memory = create_chat_completion(messages, cfg.fast_llm_model)
  File "/workspace/Auto-GPT/autogpt/llm/llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "/workspace/Auto-GPT/autogpt/llm/api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4183 tokens. Please reduce the length of the messages.
Press any key to continue...
```

**Comment by gnosisd** [comment]
same here !!!what is the answer to that ?

**Comment by KittHaab** [comment]
I have tried multiple AutoGPT tasks and sooner or later thrown out due to above mentioned "openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4183 tokens. Please reduce the length of the messages. Press any key to continue...". I do not have any succesful AutGPT task fulfilled so far :)

**Comment by suparious** [comment]
I have had this issue for weeks. It seems that this only affects GPT 3.5 uses with the 4000 token limit.

I've tried using `--gpt3only` and made sure that my token limits are set

```
FAST_TOKEN_LIMIT=4000
SMART_TOKEN_LIMIT=4000
BROWSE_CHUNK_MAX_LENGTH=3000
```

**Comment by ZylerKade** [comment]
Same issue as well. Using GPT 4 API though so not sure why.

Also, this is same issue as #3681

**Comment by PastorThefo** [comment]
Same issue with me. AutoGPT is unusable until this gets fixed. Not one of my prompts gets to completion before getting kicked out by this error.

**Comment by daweiro** [comment]
Hello. same here ;( 
already try several changes even  :
FAST_TOKEN_LIMIT=3000
SMART_TOKEN_LIMIT=3000
BROWSE_CHUNK_MAX_LENGTH=2000

same problem and crash

**Comment by kinance** [comment]
We have been working on the fix. Could anyone help test this PR, #4652?

**Comment by kinance** [comment]
Duplicates #4681
