### ISSUE TITLE
message_agent selects wrong key virtual_env crashes (multiple times)

### ISSUE THREAD

**Issue by KittHaab** [Significant-Gravitas/Auto-GPT#4018]
### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Can't reproduce as  I have entered 30 times 'y' in my task.

### Current behavior 😯

Thrown out of AutoGPT

### Expected behavior 🤔

AutoGPT should continue

### Your prompt 📝

```
 Would you like me to return to being PHCGPT?
  Asking user via keyboard...
Continue with the last settings?
Name:  PHCGPT
Role:  an AI-powered autonomous agent that specializes in analyzing the private G market and private L centers in X, with a focus on Y. It provides insights on competition, pricing, patient behavior, and growth opportunities for Z.
Goals: ['Conduct a comprehensive analysis of the private primary care market in X, with a focus on Y offering Z services.', 'Determine the number of Q in W, and provide insights on the level of competition in the market, including the factors on which they compete.', 'Analyze the pricing of services offered by P, with a focus on Z fees, and provide insights on R behavior, including how often they visit M, how many visits are per day per N, and how long they last.', 'Determine how O communicate with D, including phone calls, physical visits, and electronic channels.', 'Identify the fastest-growing private V, provide their contacts (emails and phone numbers), and provide insights on new entrants and startups in the field of L in B, including regulatory threats.']
API Budget: infinite
Continue (y/n): 

```

### Your Logs 📒

```log
Input:y -10
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command download_file returned: Command 'download_file' is disabled: Error: You do not have user authorization to download files locally.
 THOUGHTS:  I will use the 'message_agent' command to request user authorization to download files locally.
REASONING:  The 'download_file' command is currently disabled because I do not have user authorization to download files locally. I will use the 'message_agent' command to request user authorization to download files locally.
PLAN:
-  Use the 'message_agent' command to request user authorization to download files locally
CRITICISM:  I need to ensure that I am not downloading any malicious files and that the files I download are relevant to my current analysis.
NEXT ACTION:  COMMAND = message_agent ARGUMENTS = {'key': 'user', 'message': 'I need user authorization to download files locally. Please grant me permission to download the report on the cost and quality of private health services in Kenya to my local directory.'}
SYSTEM:  Command message_agent returned: Invalid key, must be an integer.
 THOUGHTS:  I will use the 'message_agent' command to request user authorization to download files locally.
REASONING:  The 'download_file' command is currently disabled because I do not have user authorization to download files locally. I will use the 'message_agent' command to request user authorization to download files locally.
PLAN:
-  Use the 'message_agent' command to request user authorization to download files locally
CRITICISM:  I need to ensure that I am not downloading any malicious files and that the files I download are relevant to my current analysis.
NEXT ACTION:  COMMAND = message_agent ARGUMENTS = {'key': 123, 'message': 'I need user authorization to download files locally. Please grant me permission to download the report on the cost and quality of private health services to my local directory.'}
SYSTEM:  Command message_agent returned: Error: 123
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\agent\agent.py", line 94, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\llm\chat.py", line 166, in chat_with_ai
    agent.summary_memory = update_running_summary(
  File "C:\agpt\Auto-GPT-0.3.0\autogpt\memory_management\summary_memory.py", line 76, in update_running_summary
    content_dict = json.loads(event["content"])
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Press any key to continue . . .

(autogpt_env) C:\agpt\Auto-GPT-0.3.0>
```

**Comment by suparious** [comment]
looks like the generic and common `json.decoder.JSONDecodeError` mentionned in #4052 and #21

**Comment by k-boikov** [comment]
Fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/3996
