### ISSUE TITLE
openai.error.InvalidRequestError: Resource not found, WH

### ISSUE THREAD

**Issue by ch01ca** [Significant-Gravitas/Auto-GPT#4023]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

#.env    
################################################################################
    ### AUTO-GPT - GENERAL SETTINGS
    ################################################################################
    # EXECUTE_LOCAL_COMMANDS - Allow local command execution (Example: False)
    EXECUTE_LOCAL_COMMANDS=True
    # BROWSE_CHUNK_MAX_LENGTH - When browsing website, define the length of chunk stored in memory
    BROWSE_CHUNK_MAX_LENGTH=8192
    # USER_AGENT - Define the user-agent used by the requests library to browse website (string)
    USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
    # AI_SETTINGS_FILE - Specifies which AI Settings file to use (defaults to ai_settings.yaml)
    #AI_SETTINGS_FILE=ai_settings.yaml
    # USE_WEB_BROWSER - Sets the web-browser drivers to use with selenium (defaults to chrome).
    # Note: set this to either 'chrome', 'firefox', or 'safari' depending on your current browser
    USE_WEB_BROWSER=chrome

    ################################################################################
    ### LLM PROVIDER
    ################################################################################

    ### OPENAI
    # OPENAI_API_KEY - OpenAI API Key (Example: my-openai-api-key)
    # TEMPERATURE - Sets temperature in OpenAI (Default: 0)
    # USE_AZURE - Use Azure OpenAI or not (Default: False)
    OPENAI_API_KEY= mytoken
    TEMPERATURE=2
    USE_AZURE=True

    ### AZURE
    # cleanup azure env as already moved to `azure.yaml.template`

    ################################################################################
    ### LLM MODELS
    ################################################################################

    # SMART_LLM_MODEL - Smart language model (Default: gpt-4)
    # FAST_LLM_MODEL - Fast language model (Default: gpt-3.5-turbo)
    #SMART_LLM_MODEL=gpt-4
    FAST_LLM_MODEL=gpt-3.5-turbo

    ### LLM MODEL SETTINGS
    # FAST_TOKEN_LIMIT - Fast token limit for OpenAI (Default: 4000)
    # SMART_TOKEN_LIMIT - Smart token limit for OpenAI (Default: 8000)
    # When using --gpt3only this needs to be set to 4000.
    FAST_TOKEN_LIMIT=4000
    SMART_TOKEN_LIMIT=8000

    ################################################################################
    ### MEMORY
    ################################################################################

    ### MEMORY_BACKEND - Memory backend type
    # local - Default
    # pinecone - Pinecone (if configured)
    # redis - Redis (if configured)
    # milvus - Milvus (if configured)
    MEMORY_BACKEND=local
    
    
#azure.yaml
azure_api_type: azure
azure_api_base: https://testtest.openai.azure.com/
azure_api_version: 2023-04-30
azure_model_map:
    fast_llm_model_deployment_id: "gpt-35-turbo"
    #smart_llm_model_deployment_id: gpt-4
    #large_llm_model_deployment_id: gpt-4-32k
    #embedding_model_deployment_id: text-embedding-ada-002

### Current behavior 😯

openai.error.InvalidRequestError: Resource not found

### Your prompt 📝

```yaml
 docker-compose run --rm auto-gpt
```

### Your Logs 📒

```log
Using Browser:  chrome
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 112, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/app/autogpt/llm/chat.py", line 245, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/app/autogpt/llm/llm_utils.py", line 158, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "/app/autogpt/llm/api_manager.py", line 46, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```

**Comment by v1ct0rv** [comment]
Hi!

I face same issue, please set on `azure.yml` `azure_api_version: 2023-05-15`  and in `.env` file set:

``` yaml
OPENAI_API_KEY=<azure api key can be key1 or key2>
# TEMPERATURE=0
USE_AZURE=True
```

**Comment by ntindle** [comment]
Your deployment ID should be the deployment name you gave it
