### ISSUE TITLE
ValueError: embedded null byte - when running ./run.bat after fresh installment on windows 64bit (with python 3.10, up to date pip)

### ISSUE THREAD

**Issue by zivikivi** [Significant-Gravitas/Auto-GPT#4046]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

.\run.bat
All packages are installed.
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news 
flag.
NEWS: 
NEWS:  Website and Documentation Site 📰📖
NEWS:  Check out https://agpt.co, the official news & updates site for Auto-GPT!        
NEWS:  The documentation also has a place here, at https://docs.agpt.co
NEWS: 
NEWS:  🚀 v0.3.0 Release 🚀
NEWS:  Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
NEWS:  the release of v0.3.0! From now on, we will be focusing on major improvements rather
NEWS:  than bugfixes, as we feel stability has reached a reasonable level. Most remaining
NEWS:  issues relate to limitations in prompt generation and the memory system, which will be
NEWS:  the focus of our efforts for the next release.
NEWS: 
NEWS:  Highlights and notable changes in this release:
NEWS: 
NEWS:  Plugin support 🔌
NEWS:  Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
NEWS:  adding support for third-party services and more.
NEWS:  See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
NEWS: 
NEWS:  Changes to Docker configuration 🐋
NEWS:  The workdir has been changed from /home/appuser to /app.
NEWS:  Be sure to update any volume mounts accordingly!
NEWS: 
NEWS:  ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
NEWS:  Twitter functionality (and more) is now covered by plugins, see [Plugin support �]]
NEWS: 
Traceback (most recent call last):
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, 
in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\raviv\zivikiviAI\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\raviv\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\raviv\zivikiviAI\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Users\raviv\zivikiviAI\autogpt\main.py", line 107, in run_auto_gpt
    workspace_directory = Workspace.make_workspace(workspace_directory)
  File "C:\Users\raviv\zivikiviAI\autogpt\workspace\workspace.py", line 52, in make_workspace
    workspace_directory = cls._sanitize_path(workspace_directory)
  File "C:\Users\raviv\zivikiviAI\autogpt\workspace\workspace.py", line 112, in _sanitize_path
    raise ValueError("embedded null byte")
ValueError: embedded null byte
Press any key to continue . . . 

### Current behavior 😯

I get an error code

### Expected behavior 🤔

it should run autogpt

### Your prompt 📝

```yaml
 .\run.bat
```

### Your Logs 📒

2023-05-09 11:14:36,863 INFO GPT4 Only Mode:  ENABLED
2023-05-09 11:14:37,211 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:14:37,211 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:14:37,212 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:14:37,212 INFO NEWS: 
2023-05-09 11:14:37,213 INFO NEWS: ::NEW BULLETIN::
2023-05-09 11:14:37,213 INFO NEWS: 
2023-05-09 11:14:37,213 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:14:37,213 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:14:37,214 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:14:37,214 INFO NEWS: 
2023-05-09 11:14:37,214 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:14:37,214 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:14:37,214 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:14:37,215 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:14:37,215 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:14:37,215 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:14:37,215 INFO NEWS: 
2023-05-09 11:14:37,216 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:14:37,216 INFO NEWS: 
2023-05-09 11:14:37,216 INFO NEWS: Plugin support 🔌
2023-05-09 11:14:37,216 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:14:37,216 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:14:37,217 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:14:37,217 INFO NEWS: 
2023-05-09 11:14:37,217 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:14:37,217 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:14:37,217 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:14:37,217 INFO NEWS: 
2023-05-09 11:14:37,217 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:14:37,218 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:14:37,218 INFO NEWS: 
2023-05-09 11:26:01,601 INFO GPT4 Only Mode:  ENABLED
2023-05-09 11:26:02,136 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:26:02,136 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:26:02,137 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:26:02,137 INFO NEWS: 
2023-05-09 11:26:02,138 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:26:02,138 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:26:02,138 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:26:02,138 INFO NEWS: 
2023-05-09 11:26:02,138 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:26:02,138 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:26:02,139 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:26:02,139 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:26:02,139 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:26:02,139 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:26:02,139 INFO NEWS: 
2023-05-09 11:26:02,140 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:26:02,140 INFO NEWS: 
2023-05-09 11:26:02,140 INFO NEWS: Plugin support 🔌
2023-05-09 11:26:02,140 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:26:02,140 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:26:02,141 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:26:02,141 INFO NEWS: 
2023-05-09 11:26:02,141 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:26:02,141 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:26:02,142 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:26:02,142 INFO NEWS: 
2023-05-09 11:26:02,142 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:26:02,142 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:26:02,143 INFO NEWS: 
2023-05-09 11:29:19,475 INFO GPT4 Only Mode:  ENABLED
2023-05-09 11:29:19,913 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:29:19,913 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:29:19,913 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:29:19,914 INFO NEWS: 
2023-05-09 11:29:19,914 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:29:19,914 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:29:19,915 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:29:19,915 INFO NEWS: 
2023-05-09 11:29:19,915 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:29:19,916 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:29:19,916 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:29:19,916 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:29:19,916 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:29:19,917 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:29:19,917 INFO NEWS: 
2023-05-09 11:29:19,917 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:29:19,917 INFO NEWS: 
2023-05-09 11:29:19,917 INFO NEWS: Plugin support 🔌
2023-05-09 11:29:19,917 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:29:19,918 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:29:19,918 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:29:19,918 INFO NEWS: 
2023-05-09 11:29:19,918 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:29:19,918 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:29:19,918 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:29:19,918 INFO NEWS: 
2023-05-09 11:29:19,919 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:29:19,919 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:29:19,919 INFO NEWS: 
2023-05-09 11:31:56,475 INFO Continuous Mode:  ENABLED
2023-05-09 11:31:56,609 INFO WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
2023-05-09 11:31:57,577 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:31:57,577 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:31:57,578 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:31:57,578 INFO NEWS: 
2023-05-09 11:31:57,578 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:31:57,579 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:31:57,579 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:31:57,579 INFO NEWS: 
2023-05-09 11:31:57,579 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:31:57,580 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:31:57,580 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:31:57,580 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:31:57,580 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:31:57,581 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:31:57,581 INFO NEWS: 
2023-05-09 11:31:57,581 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:31:57,581 INFO NEWS: 
2023-05-09 11:31:57,582 INFO NEWS: Plugin support 🔌
2023-05-09 11:31:57,582 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:31:57,582 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:31:57,582 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:31:57,582 INFO NEWS: 
2023-05-09 11:31:57,583 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:31:57,583 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:31:57,583 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:31:57,583 INFO NEWS: 
2023-05-09 11:31:57,583 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:31:57,583 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:31:57,583 INFO NEWS: 
2023-05-09 11:35:48,489 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:35:48,489 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:35:48,490 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:35:48,490 INFO NEWS: 
2023-05-09 11:35:48,491 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:35:48,491 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:35:48,491 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:35:48,491 INFO NEWS: 
2023-05-09 11:35:48,492 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:35:48,492 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:35:48,492 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:35:48,492 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:35:48,492 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:35:48,493 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:35:48,493 INFO NEWS: 
2023-05-09 11:35:48,493 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:35:48,493 INFO NEWS: 
2023-05-09 11:35:48,493 INFO NEWS: Plugin support 🔌
2023-05-09 11:35:48,494 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:35:48,494 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:35:48,494 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:35:48,494 INFO NEWS: 
2023-05-09 11:35:48,494 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:35:48,494 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:35:48,494 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:35:48,494 INFO NEWS: 
2023-05-09 11:35:48,494 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:35:48,494 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:35:48,495 INFO NEWS: 
2023-05-09 11:38:50,671 INFO GPT4 Only Mode:  ENABLED
2023-05-09 11:38:51,117 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:38:51,117 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:38:51,117 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:38:51,117 INFO NEWS: 
2023-05-09 11:38:51,118 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:38:51,118 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:38:51,118 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:38:51,118 INFO NEWS: 
2023-05-09 11:38:51,119 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:38:51,119 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:38:51,119 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:38:51,120 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:38:51,120 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:38:51,120 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:38:51,120 INFO NEWS: 
2023-05-09 11:38:51,121 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:38:51,121 INFO NEWS: 
2023-05-09 11:38:51,121 INFO NEWS: Plugin support 🔌
2023-05-09 11:38:51,121 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:38:51,121 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:38:51,121 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:38:51,122 INFO NEWS: 
2023-05-09 11:38:51,122 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:38:51,122 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:38:51,122 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:38:51,123 INFO NEWS: 
2023-05-09 11:38:51,123 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:38:51,123 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:38:51,123 INFO NEWS: 
2023-05-09 11:54:32,012 INFO GPT4 Only Mode:  ENABLED
2023-05-09 11:54:32,520 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:54:32,521 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:54:32,521 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:54:32,521 INFO NEWS: 
2023-05-09 11:54:32,522 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:54:32,522 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:54:32,522 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:54:32,522 INFO NEWS: 
2023-05-09 11:54:32,523 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:54:32,523 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:54:32,523 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:54:32,523 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:54:32,524 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:54:32,524 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:54:32,524 INFO NEWS: 
2023-05-09 11:54:32,524 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:54:32,525 INFO NEWS: 
2023-05-09 11:54:32,525 INFO NEWS: Plugin support 🔌
2023-05-09 11:54:32,525 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:54:32,525 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:54:32,526 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:54:32,526 INFO NEWS: 
2023-05-09 11:54:32,526 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:54:32,526 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:54:32,526 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:54:32,526 INFO NEWS: 
2023-05-09 11:54:32,527 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:54:32,527 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:54:32,527 INFO NEWS: 
2023-05-09 11:56:30,750 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 11:56:30,750 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features!
2023-05-09 11:56:30,750 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
2023-05-09 11:56:30,751 INFO NEWS: 
2023-05-09 11:56:30,751 INFO NEWS: Website and Documentation Site 📰📖
2023-05-09 11:56:30,752 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT!
2023-05-09 11:56:30,752 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co
2023-05-09 11:56:30,752 INFO NEWS: 
2023-05-09 11:56:30,752 INFO NEWS: 🚀 v0.3.0 Release 🚀
2023-05-09 11:56:30,753 INFO NEWS: Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
2023-05-09 11:56:30,753 INFO NEWS: the release of v0.3.0! From now on, we will be focusing on major improvements rather
2023-05-09 11:56:30,753 INFO NEWS: than bugfixes, as we feel stability has reached a reasonable level. Most remaining
2023-05-09 11:56:30,753 INFO NEWS: issues relate to limitations in prompt generation and the memory system, which will be
2023-05-09 11:56:30,754 INFO NEWS: the focus of our efforts for the next release.
2023-05-09 11:56:30,754 INFO NEWS: 
2023-05-09 11:56:30,754 INFO NEWS: Highlights and notable changes in this release:
2023-05-09 11:56:30,754 INFO NEWS: 
2023-05-09 11:56:30,754 INFO NEWS: Plugin support 🔌
2023-05-09 11:56:30,755 INFO NEWS: Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
2023-05-09 11:56:30,755 INFO NEWS: adding support for third-party services and more.
2023-05-09 11:56:30,755 INFO NEWS: See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
2023-05-09 11:56:30,755 INFO NEWS: 
2023-05-09 11:56:30,755 INFO NEWS: Changes to Docker configuration 🐋
2023-05-09 11:56:30,755 INFO NEWS: The workdir has been changed from /home/appuser to /app.
2023-05-09 11:56:30,756 INFO NEWS: Be sure to update any volume mounts accordingly!
2023-05-09 11:56:30,756 INFO NEWS: 
2023-05-09 11:56:30,756 INFO NEWS: ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
2023-05-09 11:56:30,756 INFO NEWS: Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
2023-05-09 11:56:30,756 INFO NEWS:

**Comment by k-boikov** [comment]
The error comes from the fact that the folder you are running AutoGPT in starts with "z"........ @collijk

**Comment by zivikivi** [comment]
THANKS!

Ziv Raviv

CEO and Founder, Kivi Media & Daily Cookie

+972542271336 | skype: ravivziv

https://zivraviv.com ( https://zivraviv.com/ )

https://kivimedia.co ( https://kivimedia.co/ )

https://dailycookie.co

***@***.*** ( ***@***.*** )

**Comment by xubic** [comment]
I encountered the same problem today!!!!

**Comment by zjsxply** [comment]
> The error comes from the fact that the folder you are running AutoGPT in starts with "z"........ @collijk

Thanks. It works!

**Comment by lc0rp** [comment]
> The error comes from the fact that the folder you are running AutoGPT in starts with "z"........ @collijk

Workaround - rename the folder you're running AutoGPT in.

**Comment by aa11653** [comment]
Additionally, I found relevant code in the autogpt\workspace\workspace.py file where `r"\\z"` is listed in NULL_BYTES. However, `r"\\z"` seems to be a substring that can normally appear in directory strings (as demonstrated by the file path mentioned in the previous discussion). I would like to inquire if this is a potential bug.

Code snippet from autogpt\workspace\workspace.py:17:

```
class Workspace:
    """A class that represents a workspace for an AutoGPT agent."""

    NULL_BYTES = ["\0", "\000", "\x00", r"\z", "\u0000", "%00"]
```
Code snippet from autogpt\workspace\workspace.py:110:

```
        for null_byte in Workspace.NULL_BYTES:
            if null_byte in str(relative_path) or null_byte in str(root):
                raise ValueError("embedded null byte")

```
