### ISSUE TITLE
Fails at using browser step

### ISSUE THREAD

**Issue by AdamBullen** [Significant-Gravitas/Auto-GPT#4066]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Run:
sudo docker-compose run --rm auto-gpt

### Current behavior 😯

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7cccdbd3c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7cccdbd3c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 171, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 112, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/app/autogpt/llm/chat.py", line 111, in chat_with_ai
    ) = generate_context(prompt, relevant_memory, full_message_history, model)
  File "/app/autogpt/llm/chat.py", line 54, in generate_context
    current_tokens_used = count_message_tokens(current_context, model)
  File "/app/autogpt/llm/token_counter.py", line 28, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7cccdbd3c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR: 1

```

### Expected behavior 🤔

Firefox should not refuse the connection. 
I have tried with chrome also and the same behavior is observed though chrome is running as a Flatpak application and firefox is installed normally.

### Your prompt 📝

No file called ai_settings.yaml

### Your Logs 📒

```
2023-05-09 23:27:54,868 INFO NEWS: Welcome to Auto-GPT!
2023-05-09 23:27:54,882 INFO NEWS: 
2023-05-09 23:27:54,882 INFO NEWS: 
2023-05-09 23:27:54,945 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-05-09 23:27:55,193 INFO Create an AI-Assistant: input '--manual' to enter manual mode.
2023-05-09 23:27:55,426 INFO  Asking user via keyboard...
2023-05-09 23:27:58,160 INFO Manual Mode Selected 
2023-05-09 23:27:58,253 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-05-09 23:27:58,618 INFO Name your AI:  For example, 'Entrepreneur-GPT'
2023-05-09 23:27:58,814 INFO  Asking user via keyboard...
2023-05-09 23:28:00,203 INFO JJ here! I am at your service.
2023-05-09 23:28:00,447 INFO Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
2023-05-09 23:28:00,918 INFO  Asking user via keyboard...
2023-05-09 23:28:02,361 INFO Enter up to 5 goals for your AI:  For example: 
Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
2023-05-09 23:28:02,775 INFO  Enter nothing to load defaults, enter nothing when finished.
2023-05-09 23:28:02,775 INFO  Asking user via keyboard...
2023-05-09 23:28:03,125 INFO Enter your budget for API calls:  For example: $1.50
2023-05-09 23:28:03,388 INFO  Enter nothing to let the AI run without monetary limit
2023-05-09 23:28:03,388 INFO  Asking user via keyboard...
2023-05-09 23:28:04,390 INFO JJ has been created with the following details:
2023-05-09 23:28:04,622 INFO Name: JJ
2023-05-09 23:28:04,665 INFO Role: an AI designed to autonomously develop and run businesses with the
2023-05-09 23:28:04,922 INFO Goals: 
2023-05-09 23:28:04,962 INFO - Increase net worth
2023-05-09 23:28:05,078 INFO - Grow Twitter Account
2023-05-09 23:28:05,254 INFO - Develop and manage multiple businesses autonomously
2023-05-09 23:28:05,475 INFO Using memory of type: LocalCache
2023-05-09 23:28:05,605 INFO Using Browser: firefox
2023-05-09 23:28:05,750 DEBUG  []
```

**Comment by suparious** [comment]
The default `ai_settings.yaml` is found in the root of the Auto_GPT folder. It will automatically get updated after you run Auto-GPT for the first time.

Have you also tried using chrome?
Are you running this from a Powershell or Git-BASH terminal? 
Did you configure `HEADLESS_BROWSER=True` in the `Auto-GPT/.env` file?

**Comment by gunish** [comment]
Tried using the HEADLESS_BROWSER=True in the .env file = still getting the following error. 

`SYSTEM:  Command browse_website returned: Error: unknown error: Chrome failed to start: exited abnormally.
`

**Comment by AdamBullen** [comment]
I'm running from the Linux terminal

**Comment by db120** [comment]
> I'm running from the Linux terminal
> 
> I don't see the ai_settings.yaml in the folder, I haven't successfully been able to run AutoGPT yet.

I am having the same issues with you when it comes to the browser. To see the ai_setting.yaml file, use the command: ls -a

**Comment by AdamBullen** [comment]
I couldn't get it to work using docker, so I have started using the CLI version, which works.
