### ISSUE TITLE
Error when first initializing AutoGPT

### ISSUE THREAD

**Issue by 0bvio** [Significant-Gravitas/Auto-GPT#4097]
I keep getting an error when I attempt to run the program for the first time.  No issues happened during installation to my knowledge.

Here is the CMD output

`C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0>python -m autogpt
Traceback (most recent call last):
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\agent\agent.py", line 12, in <module>
    from autogpt.utils import clean_input
  File "C:\Users\Gio\Documents\Auto-GPT-0.3.0\Auto-GPT-0.3.0\autogpt\utils.py", line 7, in <module>
    from git.repo import Repo
  File "C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

`

**Comment by suparious** [comment]
did you install git from scp (ie: Git-BASH) and test that it works in your terminal?

Usually during the install of it it will ask if you want to modify your ENV variables to have the PATH updated. I would check that box, unless you've already done it manually.

the process `C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py` is simply trying to use the `git` command from your terminal, so you can try to test manually to see if installing git fixed the issue.

**Comment by joelbcampos** [comment]
Good afternoon, I downloaded it from https://git-scm.com/, installed it, restarted, and it's working now.

**Comment by 0bvio** [comment]
That solved it.  I have other errors, but that will be in a new request.  Thanks!

**Comment by 0bvio** [comment]
> It's probably trying to pull in the plugins from git
> 
> did you install git from scp (ie: Git-BASH) and test that it works in your terminal?
> 
> Usually during the install of it it will ask if you want to modify your ENV variables to have the PATH updated. I would check that box, unless you've already done it manually.
> 
> the process `C:\Users\Gio\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py` is simply trying to use the `git` command from your terminal, so you can try to test manually to see if installing git fixed the issue.
> 

This solved it.  I keep having another error, however.

Now I keep seeing Unknown error: Cannot find Chrome Binary, I can't use Google or browse_website, etc
