### ISSUE TITLE
TypeError: 'type' object is not subscriptable after ./run.sh command 

### ISSUE THREAD

**Issue by LogunPrettyMotherFucker** [Significant-Gravitas/Auto-GPT#4118]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

./run.sh command in terminal 

### Current behavior 😯

Traceback (most recent call last):
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/auto-gpt/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/agent/agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/llm/__init__.py", line 1, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/llm/api_manager.py", line 7, in <module>
    from autogpt.logs import logger
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/logs.py", line 12, in <module>
    from autogpt.speech import say_text
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/speech/__init__.py", line 2, in <module>
    from autogpt.speech.say import say_text
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/speech/say.py", line 34, in <module>
    def _get_voice_engine(config: Config) -> tuple[VoiceBase, VoiceBase]:
TypeError: 'type' object is not subscriptable

### Expected behavior 🤔

Program should initialise and run.

should go to user input AI Name:

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by suparious** [comment]
In the log, it is showing python 3.8, when the documentation is asking for 3.10+

On the Mac, a basic workflow is usually as follows:
- use homebrew to install the latest python3 (3.11.3)
- update my PATH to use the homebrew linked python (linked to python3) instead of the ancient MacOS python
- restart your shell and run `python --version` to confirm the results

A more advanced and robust workflow would be to proceed as follows:
- Install [pyenv](https://github.com/pyenv/pyenv) and update your shell
- Install [pyenv-update](https://github.com/pyenv/pyenv-update) and update your list of available python versions
- install python 3.11.3 with `pyenv install 3.11.3`
- make 3.11.3 your default python `pyenv global 3.11.3`
- restart your shell and run `python --version` to confirm the results

**Comment by LogunPrettyMotherFucker** [comment]
Perfect, I installed pyenv and updated my shell and python version via homebrew and it's working now thanks a lot

**Comment by LogunPrettyMotherFucker** [comment]
Since opening another instance of terminal and attempting to start auto gpt again I get this traceback 

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/account/Documents/Auto-GPT/Auto-GPT-0.3.0/autogpt/__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Below is an example of where it is locating modules from.
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 4)) (1.3.1)

I believe it may still be trying to use the standard python version I have installed and not the one present in the virtual environment but I can't figure out how to point it to the correct python version.

**Comment by richbeales** [comment]
https://stackoverflow.com/questions/52060867/how-to-use-pip-for-pyenv

**Comment by ReihanMudd** [comment]
I am getting the exact same issue, getting the same exact traceback as well:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/account/Auto-GPT/autogpt/__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Not sure what's happening
