### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

### ISSUE THREAD

**Issue by eugenbg** [Significant-Gravitas/Auto-GPT#4200]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

./run.sh

### Current behavior 😯

/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/www/auto-gpt/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/eugen/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/auto-gpt/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/var/www/auto-gpt/autogpt/main.py", line 147, in run_auto_gpt
    command_registry.import_commands(command_category)
  File "/var/www/auto-gpt/autogpt/commands/command.py", line 110, in import_commands
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/auto-gpt/autogpt/commands/image_gen.py", line 8, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

### Expected behavior 🤔

should work

### Your prompt 📝

none

### Your Logs 📒

eugen@eugen-NUC10i5FNK:/var/www/auto-gpt$ python -V
Python 3.10.11

eugen@eugen-NUC10i5FNK:/var/www/auto-gpt$ pip -V
pip 23.1.2 from /home/eugen/.local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by k-boikov** [comment]
Do you get the same error with docker or venv or devcontainer?

**Comment by eugenbg** [comment]
with docker-compose i am getting another error, something about not being able to mount the file system.. I ended up commenting out the command that was using this pil library
