### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by MoondarkerIT** [Significant-Gravitas/Auto-GPT#4204]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I had just gone through the instillation procces when i run the program and I get a bunch of errors.

### Current behavior 😯

Error messaegs:
All packages are installed.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/moondarker/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/moondarker/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/moondarker/Auto-GPT/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/home/moondarker/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/home/moondarker/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/moondarker/Auto-GPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/moondarker/Auto-GPT/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/home/moondarker/Auto-GPT/autogpt/agent/agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "/home/moondarker/Auto-GPT/autogpt/llm/__init__.py", line 11, in <module>
    from autogpt.llm.chat import chat_with_ai, create_chat_message, generate_context
  File "/home/moondarker/Auto-GPT/autogpt/llm/chat.py", line 12, in <module>
    from autogpt.memory_management.store_memory import (
  File "/home/moondarker/Auto-GPT/autogpt/memory_management/store_memory.py", line 1, in <module>
    from autogpt.json_utils.utilities import (
  File "/home/moondarker/Auto-GPT/autogpt/json_utils/utilities.py", line 33, in <module>
    def validate_json(json_object: object, schema_name: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### Expected behavior 🤔

Running Auto-gpt without errors

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by monkeyden** [comment]
Which version of Python are you using?  I saw a similar error, which I believe I solved by upgrading from Python 3.9.x to Python 3.10.11.

**Comment by AngeloSchulerPiletti** [comment]
I was facing the same problem. You may have installed the right version of the python. But your PATH can be still pointing to the old version. I would suggest you to use [Python Version Manager](https://github.com/pyenv/pyenv#understanding-path)

**Comment by monkeyden** [comment]
> I was facing the same problem. You may have installed the right version of the python. But your PATH can be still pointing to the old version. I would suggest you to use [Python Version Manager](https://github.com/pyenv/pyenv#understanding-path)

Is there any reason you wouldn't just use an isolated venv or a conda environment at this point?  Legit curious.
