### ISSUE TITLE
AutoGPT v0.3.1 crashes immediately after task given

### ISSUE THREAD

**Issue by KittHaab** [Significant-Gravitas/Auto-GPT#4218]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  input '--manual' to enter manual mode.
  Asking user via keyboard...
I want Auto-GPT to: Search Big Mac prices in EU countries
Unable to automatically generate AI Config based on user desire.  Falling back to manual mode.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
  Asking user via keyboard...
AI Name: MacGPT
MacGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
  Asking user via keyboard...
MacGPT is: Search for Big Mc prices in EU countries
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
  Enter nothing to load defaults, enter nothing when finished.
  Asking user via keyboard...
Goal 1: Conduct a thorough and accurate search of BigMc prices across EU countries
  Asking user via keyboard...
Goal 2: Provide price per each EU capital
  Asking user via keyboard...
Goal 3: Ensure that the information provided is up-to-date and accurate
  Asking user via keyboard...
Goal 4: Continuously improve the search algorithm to increase the accuracy and efficiency of the search process.
  Asking user via keyboard...
Goal 5: Do not crash ang give error - "openai.error.AuthenticationError: <empty message>"
Enter your budget for API calls:  For example: $1.50
  Enter nothing to let the AI run without monetary limit
  Asking user via keyboard...
Budget: $1
MacGPT  has been created with the following details:
Name:  MacGPT
Role:  Search for Big Mc prices in EU countries
Goals:
-  Conduct a thorough and accurate search of BigMc prices across EU countries
-  Provide price per each EU capital
-  Ensure that the information provided is up-to-date and accurate
-  Continuously improve the search algorithm to increase the accuracy and efficiency of the search process.
-  Do not crash ang give error - "openai.error.AuthenticationError: <empty message>"
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "C:\Users\makkolev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\makkolev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\agpt\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\agpt\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\agpt\autogpt\main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "C:\agpt\autogpt\agent\agent.py", line 113, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\agpt\autogpt\llm\chat.py", line 244, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\agpt\autogpt\llm\llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "C:\agpt\autogpt\llm\api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

### Current behavior 😯

Crashes multiple times

### Expected behavior 🤔

Starts

### Your prompt 📝

```AI Name: MacGPT
MacGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
  Asking user via keyboard...
MacGPT is: Search for Big Mc prices in EU countries
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
  Enter nothing to load defaults, enter nothing when finished.
  Asking user via keyboard...
Goal 1: Conduct a thorough and accurate search of BigMc prices across EU countries
  Asking user via keyboard...
Goal 2: Provide price per each EU capital
  Asking user via keyboard...
Goal 3: Ensure that the information provided is up-to-date and accurate
  Asking user via keyboard...
Goal 4: Continuously improve the search algorithm to increase the accuracy and efficiency of the search process.
  Asking user via keyboard...
Goal 5: Do not crash ang give error - "openai.error.AuthenticationError: <empty message>"
Enter your budget for API calls:  For example: $1.50
  Enter nothing to let the AI run without monetary limit
  Asking user via keyboard...
Budget: $1
MacGPT  has been created with the following details:
Name:  MacGPT
Role:  Search for Big Mc prices in EU countries
Goals:
-  Conduct a thorough and accurate search of BigMc prices across EU countries
-  Provide price per each EU capital
-  Ensure that the information provided is up-to-date and accurate
-  Continuously improve the search algorithm to increase the accuracy and efficiency of the search process.
-  Do not crash ang give error - "openai.error.AuthenticationError: <empty message>"
Using memory of type:  LocalCache
Using Browser:  chrome
```

### Your Logs 📒

```log
Traceback (most recent call last):
  File "C:\Users\makkolev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\makkolev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\agpt\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\agpt\autogpt_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\agpt\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\agpt\autogpt\main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "C:\agpt\autogpt\agent\agent.py", line 113, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\agpt\autogpt\llm\chat.py", line 244, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\agpt\autogpt\llm\llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "C:\agpt\autogpt\llm\api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\agpt\autogpt_env\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
Press any key to continue . . .
```

**Comment by KittHaab** [comment]
Checked OpenAI API key in .env. Created even a new key. Did not help. What is interesting is that in in API keys table ("
NAME | KEY | CREATED | LAST USED") it indicates the API key was never used (both the previous one I tried a couple of times and now the newly created one). So the new v0.3.1 code did not reach actually to the API

**Comment by KittHaab** [comment]
Although I have a correct OpenAI API key in environment variable, I tried later to set it also manually from Command Line ("set OPENAI_KEY=sk........."), but that did not help either

**Comment by lKingBearl** [comment]
My openAI key is definitely correct, I have created new API keys overwrote it in the .env, saved it and relaunched, but i still get this error, i too, cannot see the API key even being used at all in the OpenAI API key screen.
Can confirm I have paid API key also

**Comment by lKingBearl** [comment]
I fixed mine.
In another troubleshooting process I added my API key as an environment variable and I then went and generated another, which I updated in the .env, but I had not in the environment variable, updated it, restart VScode, reran the start script, and voila

**Comment by KittHaab** [comment]
Made a local temporary fix, that I do not advise to others and **please fix it properly.** 

**The problem exists - latest version (v0.3.1) can't access OpenAI API key!**

As a temporary fix I inserted OpenAPI key directly to python file "AutoGPT/autogpt/llm/api_manager.py" and it worked for now.

api_key has to be inserted in 2 places in"create_chat_completion" method, like:

response = openai.ChatCompletion.create(
                deployment_id=deployment_id,
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                api_key="sk........................... ,
) ...

Any other update, creation of new API keys or setting API key via Command Prompt did not work for me

**Comment by KittHaab** [comment]
You are correct! Commenting out line 56 works fine

**Comment by GuyenSoto** [comment]
Me too like [AxlAi](https://github.com/AxlAi)

**Comment by db120** [comment]
I'm having the same issue, API key is correct.

**Comment by GoldWaterGG** [comment]
Make sure your API key only has one set of "" quotation marks in .env before you save it. Then set everything up and try it again.

**Comment by AxlAi** [comment]
> Make sure your API key only has one set of "" quotation marks in .env before you save it. Then set everything up and try it again.

I put quotes around my api and something changed. But there are still errors. I report them:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "D:\Python\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\agent\agent.py", line 113, in start_interaction_loop
    assistant_reply = chat_with_ai(
                      ^^^^^^^^^^^^^
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\llm\chat.py", line 165, in chat_with_ai
    agent.summary_memory = update_running_summary(
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\memory_management\summary_memory.py", line 128, in update_running_summary       
    current_memory = create_chat_completion(messages, cfg.fast_llm_model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\llm\llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-IA\Auto-GPT-0.3.1\autogpt\llm\api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 
4563 tokens. Please reduce the length of the messages.

**Comment by nidhipatel979** [comment]
I am having the same issue

**Comment by H179922** [comment]
For some reason (even though I previously ran without issue) changing my browser from firefox to safari fixed this issue. It then failed to execute web searches with safari. changed to chrome and the same error as initially described occurred again. I don't have edge (also I hate it) on MacOS so I can't test that one
