### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by HirCoir** [Significant-Gravitas/Auto-GPT#4223]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/autogpt4all/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/autogpt4all/Auto-GPT/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/root/autogpt4all/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/root/autogpt4all/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/root/autogpt4all/Auto-GPT/autogpt/agent/agent.py", line 7, in <module>
    from autogpt.json_utils.json_fix_llm import fix_json_using_multiple_techniques
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/json_fix_llm.py", line 13, in <module>
    from autogpt.json_utils.json_fix_general import correct_json
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/json_fix_general.py", line 11, in <module>
    from autogpt.json_utils.utilities import extract_char_position
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/utilities.py", line 33, in <module>
    def validate_json(json_object: object, schema_name: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/autogpt4all/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/autogpt4all/Auto-GPT/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/root/autogpt4all/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/root/autogpt4all/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/root/autogpt4all/Auto-GPT/autogpt/agent/agent.py", line 7, in <module>
    from autogpt.json_utils.json_fix_llm import fix_json_using_multiple_techniques
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/json_fix_llm.py", line 13, in <module>
    from autogpt.json_utils.json_fix_general import correct_json
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/json_fix_general.py", line 11, in <module>
    from autogpt.json_utils.utilities import extract_char_position
  File "/root/autogpt4all/Auto-GPT/autogpt/json_utils/utilities.py", line 33, in <module>
    def validate_json(json_object: object, schema_name: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by k-boikov** [comment]
Please use python 3.10 or higher.
