### ISSUE TITLE
Using 's' for self-feedback crashes

### ISSUE THREAD

**Issue by hackedpassword** [Significant-Gravitas/Auto-GPT#4275]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

This is the output; user and instance replaced in []'s.

CRITICISM:  I need to make sure that I am regularly reviewing my long-term plan and updating it as necessary. I also need to improve my short-term memory management to avoid losing important information.
NEXT ACTION:  COMMAND = check_plan ARGUMENTS = {}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for [gpt_instance_name]...
  Asking user via keyboard...
Input:s
-=-=-=-=-=-=-= THOUGHTS, REASONING, PLAN AND CRITICISM WILL NOW BE VERIFIED BY AGENT -=-=-=-=-=-=-=
Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Dev\GitHub\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Dev\GitHub\Auto-GPT\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "D:\Dev\GitHub\Auto-GPT\autogpt\main.py", line 193, in run_auto_gpt
    agent.start_interaction_loop()
  File "D:\Dev\GitHub\Auto-GPT\autogpt\agent\agent.py", line 204, in start_interaction_loop
    self_feedback_resp = self.get_self_feedback(
  File "D:\Dev\GitHub\Auto-GPT\autogpt\agent\agent.py", line 356, in get_self_feedback
    feedback = create_chat_completion(messages)
  File "D:\Dev\GitHub\Auto-GPT\autogpt\llm\llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "D:\Dev\GitHub\Auto-GPT\autogpt\llm\api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 90, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'model' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

### Current behavior 😯

Takes a moment then crashes once 's' is entered as the input.

### Expected behavior 🤔

Not sure, this prompt hasn't worked yet!

### Your prompt 📝

s
^-- that's it. 's'.

### Your Logs 📒

As stated above.

**Comment by RudeDog69** [comment]
I am having the same issue in Linux on v0.3.1 Release.

**Comment by ans-4175** [comment]
Same issue here on Mac
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/3961872/9a66c94c-de76-42da-b953-d7c2358c13e1)

**Comment by ntindle** [comment]
Opened a PR to fix. Thanks for the issue!
