### ISSUE TITLE
Current stable version (0.3.1) not compatible with Docker

### ISSUE THREAD

**Issue by VisionaryMind** [Significant-Gravitas/Auto-GPT#4292]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

1. Clone AutoGPT to local directory and switch to branch stable-0.3.1.

2. Modify docker-compose.yml to include the following volumnes:
      - ./data:/app/data
      - ./plugins:/app/plugins
      
3. Copy .env.template to .env and uncomment + configure OPENAI_API_KEY variable with a valid key.

4. Modify requirements.txt to include third-party plugin dependencies, as required.

5. Run `docker-compose build auto-gpt`.

6. Run `docker-compose run --rm auto-gpt --continuous --install-plugin-deps`

7. Define the AutoGPT bot and provide goals.

Will fail on the first goal due to an OpenAI authentication error. On the Docker log, the following is displayed:

`Please set your OpenAI API key in .env or as an environment variable.`

Inspection of environment variables (through Docker GUI) shows that no value has been defined for OPENAI_API_KEY.

### Current behavior 😯

After setting goals, it errors out with the following message:

```
Using Browser:  chrome
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 113, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/app/autogpt/llm/chat.py", line 244, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/app/autogpt/llm/llm_utils.py", line 166, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "/app/autogpt/llm/api_manager.py", line 55, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
```

### Expected behavior 🤔

AutoGPT should be able to find the .env file locally (using the mounted volume and default .env location setting). It appears that docker-compose no longer copies the .env file to the Docker environment on launch, and there are no instructions at the moment to explain a workaround.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

Error does not appear in the log. It doesn't get farther than the first GPT query via API. It fails due to the inability to find the .env file.

**Comment by Amarendraar23** [comment]
@VisionaryMind  How did you solve this?
