### ISSUE TITLE
changing api_manager.py to include a method for chat completion test error handling

### ISSUE THREAD

**Issue by GoZippy** [Significant-Gravitas/Auto-GPT#4309]
Try changing api_manager.py to include a method for chat completion 

```
import openai
from openai.error import InvalidRequestError

# ...

class ApiManager(metaclass=Singleton):
    # ...

    def create_chat_completion(
        self,
        messages: list,  # type: ignore
        model: str | None = None,
        temperature: float = None,
        max_tokens: int | None = None,
        deployment_id=None,
    ) -> str:
        cfg = Config()
        if temperature is None:
            temperature = cfg.temperature
        try:
            if deployment_id is not None:
                response = openai.ChatCompletion.create(
                    deployment_id=deployment_id,
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    api_key=cfg.openai_api_key,
                )
            else:
                response = openai.ChatCompletion.create(
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    api_key=cfg.openai_api_key,
                )
        except InvalidRequestError as e:
            # Handle the specific error, e.g., if it's a token limit error
            if e.code == "invalid_request" and "token limit" in e.message.lower():
                # Implement your logic to reduce the length of messages or split them into smaller parts
                # Modify messages or take appropriate action
                pass
            else:
                # Handle other specific error cases or fallback to a general error handling strategy
                pass
        else:
            if not hasattr(response, "error"):
                logger.debug(f"Response: {response}")
                prompt_tokens = response.usage.prompt_tokens
                completion_tokens = response.usage.completion_tokens
                self.update_cost(prompt_tokens, completion_tokens, model)
        return response
```

Lets see if something like this would work.

_Originally posted by @GoZippy in https://github.com/Significant-Gravitas/Auto-GPT/issues/4019#issuecomment-1555034958_

**Comment by GoZippy** [comment]
Here's an updated version of the create_chat_completion method in api_manager.py that includes the logic for handling invalid requests and token limit errors, as well as attempting to reduce the token size and retrying the API call:

```
import openai
from openai.error import InvalidRequestError

# ...

class ApiManager(metaclass=Singleton):
    # ...

    def create_chat_completion(
        self,
        messages: list,
        model: str | None = None,
        temperature: float = None,
        max_tokens: int | None = None,
        deployment_id=None,
    ) -> str:
        cfg = Config()
        if temperature is None:
            temperature = cfg.temperature
        try:
            if deployment_id is not None:
                response = openai.ChatCompletion.create(
                    deployment_id=deployment_id,
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    api_key=cfg.openai_api_key,
                )
            else:
                response = openai.ChatCompletion.create(
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    api_key=cfg.openai_api_key,
                )
        except InvalidRequestError as e:
            if e.code == "invalid_request" and "token limit" in e.message.lower():
                # Token limit error handling
                reduced_messages = self.reduce_message_tokens(messages)
                return self.create_chat_completion(
                    reduced_messages,
                    model=model,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    deployment_id=deployment_id,
                )
            else:
                # Handle other specific error cases or fallback to a general error handling strategy
                # For example, you can raise a custom exception or log the error and return an appropriate response
                raise MyCustomException("Error calling OpenAI API: " + str(e))
        else:
            if not hasattr(response, "error"):
                logger.debug(f"Response: {response}")
                prompt_tokens = response.usage.prompt_tokens
                completion_tokens = response.usage.completion_tokens
                self.update_cost(prompt_tokens, completion_tokens, model)
        return response

    def reduce_message_tokens(self, messages):
        """
        Reduce the token size of the messages by removing or truncating content.

        Args:
        messages (list): The list of messages to reduce.

        Returns:
        list: The reduced messages.
        """
        # Implement your logic to reduce the token size of the messages
        # For example, you can truncate the messages or remove the least important parts
        # Modify the messages and return the reduced version
        reduced_messages = messages
        return reduced_messages

```
In this updated code, the reduce_message_tokens method is introduced to handle the reduction of token size in the messages. We can implement our own logic within this method to reduce the token size of the messages. This can involve truncating the messages, removing less important parts, or any other strategy that suits project requirements.

If a token limit error occurs, the code invokes the reduce_message_tokens method to obtain a reduced version of the messages. Then, it retries the API call recursively with the reduced messages until the token limit error is resolved or another error occurs.

We can further customize the error handling by adding more specific error cases and their corresponding actions inside the except block. For example, you can handle specific error codes, log errors, raise custom exceptions, or return appropriate responses to the calling function.

TODO - get list of all known error codes and generate a helper file to script solutions to try to resolve the exception or error thrown then rewrite or save files as appropriate and try the api calls again.

**Comment by GoZippy** [comment]
new api_manager.py

```
from __future__ import annotations

import openai

from autogpt.config import Config
from autogpt.llm.modelsinfo import COSTS
from autogpt.logs import logger
from autogpt.singleton import Singleton

model_token_limit = {
    "gpt-3.5-turbo": 4096,
    # Add more models and their respective token limits if needed
}


def handle_token_limit_error(messages, model, max_tokens):
    """
    Handles the token limit error by splitting the messages into smaller chunks.

    Args:
        messages (list): The list of messages.
        model (str): The model used for the API call.
        max_tokens (int): The maximum number of tokens for the API call.

    Returns:
        list: List of responses for each message chunk.
    """
    # Calculate the maximum tokens per message based on the model's context length limit
    max_context_tokens = model_token_limit[model] - len(messages[0]["role"]) - len(messages[0]["content"]) - 1
    max_tokens_per_message = max_context_tokens + max_tokens - 1

    # Split the messages into smaller chunks
    message_chunks = []
    current_chunk = []
    current_chunk_tokens = 0

    for message in messages:
        message_tokens = len(message["role"]) + len(message["content"]) + 1

        if current_chunk_tokens + message_tokens <= max_tokens_per_message:
            current_chunk.append(message)
            current_chunk_tokens += message_tokens
        else:
            message_chunks.append(current_chunk)
            current_chunk = [message]
            current_chunk_tokens = message_tokens

    if current_chunk:
        message_chunks.append(current_chunk)

    # Make API calls for each message chunk
    responses = []
    for chunk in message_chunks:
        response = api_manager.create_chat_completion(chunk, model=model, max_tokens=max_tokens)
        responses.append(response)

    return responses


class ApiManager(metaclass=Singleton):
    def __init__(self):
        # Initialize total counts and cost
        self.total_prompt_tokens = 0
        self.total_completion_tokens = 0
        self.total_cost = 0
        self.total_budget = 0

    def reset(self):
        # Reset total counts and cost
        self.total_prompt_tokens = 0
        self.total_completion_tokens = 0
        self.total_cost = 0
        self.total_budget = 0.0

    def create_chat_completion(
        self,
        messages: list,
        model: str | None = None,
        temperature: float = None,
        max_tokens: int | None = None,
        deployment_id=None,
    ) -> str:
        """
        Create a chat completion and update the cost.

        Args:
            messages (list): The list of messages to send to the API.
            model (str): The model to use for the API call.
            temperature (float): The temperature to use for the API call.
            max_tokens (int): The maximum number of tokens for the API call.
            deployment_id: The deployment ID for Chat models.

        Returns:
            str: The AI's response.
        """
        cfg = Config()
        if temperature is None:
            temperature = cfg.temperature

        if deployment_id is not None:
            response = openai.ChatCompletion.create(
                deployment_id=deployment_id,
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                api_key=cfg.openai_api_key,
            )
        else:
            response = openai.ChatCompletion.create(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                api_key=cfg.openai_api_key,
            )

        if hasattr(response, "error"):
            error_message = response.error.message
            if "token limit" in error_message.lower():
                logger.info("Received token limit error. Attempting to handle the error.")

                # Handle the token limit error
                responses = handle_token_limit_error(messages, model, max_tokens)

                # Combine the responses into a single response
                combined_response = {
                    "id": response.id,
                    "object": response.object,
                    "created": response.created,
                    "model": response.model,
                    "usage": response.usage,
                    "choices": [],
                }

                for resp in responses:
                    combined_response["choices"].extend(resp.choices)

                prompt_tokens = combined_response["usage"]["prompt_tokens"]
                completion_tokens = combined_response["usage"]["completion_tokens"]
                self.update_cost(prompt_tokens, completion_tokens, model)

                return combined_response

            logger.error(f"API error: {response.error}")

        logger.debug(f"Response: {response}")
        prompt_tokens = response.usage.prompt_tokens
        completion_tokens = response.usage.completion_tokens
        self.update_cost(prompt_tokens, completion_tokens, model)

        return response

    def update_cost(self, prompt_tokens, completion_tokens, model):
        """
        Update the total cost, prompt tokens, and completion tokens.

        Args:
            prompt_tokens (int): The number of tokens used in the prompt.
            completion_tokens (int): The number of tokens used in the completion.
            model (str): The model used for the API call.
        """
        self.total_prompt_tokens += prompt_tokens
        self.total_completion_tokens += completion_tokens
        self.total_cost += (
            prompt_tokens * COSTS[model]["prompt"]
            + completion_tokens * COSTS[model]["completion"]
        ) / 1000
        logger.debug(f"Total running cost: ${self.total_cost:.3f}")

    def set_total_budget(self, total_budget):
        """
        Sets the total user-defined budget for API calls.

        Args:
            total_budget (float): The total budget for API calls.
        """
        self.total_budget = total_budget

    def get_total_prompt_tokens(self):
        """
        Get the total number of prompt tokens.

        Returns:
            int: The total number of prompt tokens.
        """
        return self.total_prompt_tokens

    def get_total_completion_tokens(self):
        """
        Get the total number of completion tokens.

        Returns:
            int: The total number of completion tokens.
        """
        return self.total_completion_tokens

    def get_total_cost(self):
        """
        Get the total cost of API calls.

        Returns:
            float: The total cost of API calls.
        """
        return self.total_cost

    def get_total_budget(self):
        """
        Get the total user-defined budget for API calls.

        Returns:
            float: The total budget for API calls.
        """
        return self.total_budget

```

**Comment by GoZippy** [comment]
While this is a workaround in part- I would like to implement solution to read the message in full - define intent - and try first to summarize or condense and try again instead of simply chunking it - or else try finding multiple intents within the message to see if there is a logical way to generate multiple smaller calls from a longer one.

**Comment by bckirkup** [comment]
This can be partially related to the SmartGPT strategy of task sub-division; but instead of attempting to evaluate a set of answers to the same question, it requires a consistency check across answers that address parts of the larger problem.  

Meanwhile, of course, failing gracefully (and intelligibly to AutoGPT itself, not to mention the user) is a necessary feature of the software.

**Comment by GoZippy** [comment]
> This can be partially related to the SmartGPT strategy of task sub-division; but instead of attempting to evaluate a set of answers to the same question, it requires a consistency check across answers that address parts of the larger problem.
> 
> Meanwhile, of course, failing gracefully (and intelligibly to AutoGPT itself, not to mention the user) is a necessary feature of the software.

That's what I'm working on... I'll update GitHub tonight with my progress.

**Comment by guppyO** [comment]
I receive this error when attempting to use your latest "api_manager.py"

C:\Users\beres\Desktop\Auto-GPT>python -m autogpt --continuous
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\beres\Desktop\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\Desktop\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\beres\Desktop\Auto-GPT\autogpt\main.py", line 51, in run_auto_gpt
    create_config(
  File "C:\Users\beres\Desktop\Auto-GPT\autogpt\configurator.py", line 51, in create_config
    CFG.set_fast_llm_model(check_model(CFG.fast_llm_model, "fast_llm_model"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beres\Desktop\Auto-GPT\autogpt\llm\llm_utils.py", line 303, in check_model
    models = api_manager.get_models()
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ApiManager' object has no attribute 'get_models'

**Comment by GoZippy** [comment]
yeah I had to change the way its called in utils... working on patches now... every patch leaves one more thing to fix it seems - probably by tomorrow

**Comment by samuelbutler** [comment]
It seems like this should be a Pull Request (not an Issue) whenever you do get all the bugs worked out of this proposed change to AutoGPT's code. 

I'm going to close this issue, as any further discussion on this should be as a Pull Request.

**Comment by GoZippy** [comment]
Bummer for closing... I prefer collaboration before pushing a pull request thru...
