### ISSUE TITLE
Pinecone Forbidden

### ISSUE THREAD

**Issue by jimmylimshopping** [Significant-Gravitas/Auto-GPT#431]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "/Users/jimmylim1/Auto-GPT/scripts/main.py", line 287, in <module>
    memory.clear()
  File "/Users/jimmylim1/Auto-GPT/scripts/memory.py", line 46, in clear
    self.index.delete(deleteAll=True)
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/utils/error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/index.py", line 329, in delete
    return self._vector_api.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api/vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 207, in __call_api
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pinecone/core/client/rest.py", line 222, in request
    raise ForbiddenException(http_resp=r)
pinecone.core.client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Fri, 07 Apr 2023 21:58:43 GMT', 'server': 'envoy'})

### Current behavior 😯

After adding the Pinecone API, and ran Auto-GPT, this error appeared.

### Expected behavior 🤔

Auto-GPT to not crash.

### Your prompt 📝

```yaml
Name:  Bot
Role:  Some kind of API bot
Goals: ['create a recipe for halloween', 'save the recipe to a list', 'shutdown upon achieving your goal'] 
```

**Comment by LiThiuMElectro** [comment]
Getting some weird error with Pinecone too
Traceback (most recent call last):
  File "D:\AutoGPT\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "D:\AutoGPT\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "D:\AutoGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\rest.py", line 219, in request
    raise UnauthorizedException(http_resp=r)
pinecone.core.client.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'www-authenticate': 'API key is missing or invalid for the environment "us-east1-gcp". Check that the correct environment is specified.', 'content-length': '114', 'date': 'Fri, 07 Apr 2023 22:14:40 GMT', 'server': 'envoy'})
HTTP response body: API key is missing or invalid for the environment "us-east1-gcp". Check that the correct environment is specified.

Key is not missing

**Comment by jorgpt** [comment]
> Getting some weird error with Pinecone too Traceback (most recent call last): File "D:\AutoGPT\Auto-GPT\scripts\main.py", line 286, in memory = PineconeMemory() File "D:\AutoGPT\Auto-GPT\scripts\config.py", line 17, in **call** cls._instances[cls] = super( File "D:\AutoGPT\Auto-GPT\scripts\memory.py", line 30, in **init** if table_name not in pinecone.list_indexes(): File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\manage.py", line 185, in list_indexes response = api_instance.list_indexes() File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 776, in **call** return self.callable(self, *args, **kwargs) File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes return self.call_with_http_info(**kwargs) File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info return self.api_client.call_api( File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api return self.__call_api(resource_path, method, File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api raise e File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api response_data = self.request( File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request return self.rest_client.GET(url, File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET return self.request("GET", url, File "C:\Users\LiThiuM\AppData\Local\Programs\Python\Python39\lib\site-packages\pinecone\core\client\rest.py", line 219, in request raise UnauthorizedException(http_resp=r) pinecone.core.client.exceptions.UnauthorizedException: (401) Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'www-authenticate': 'API key is missing or invalid for the environment "us-east1-gcp". Check that the correct environment is specified.', 'content-length': '114', 'date': 'Fri, 07 Apr 2023 22:14:40 GMT', 'server': 'envoy'}) HTTP response body: API key is missing or invalid for the environment "us-east1-gcp". Check that the correct environment is specified.
> 
> Key is not missing

ive been trying to fix this all day, maybe because our directory is in users?

**Comment by mrMaxsu** [comment]
same issue-
 i got it to work by puting in the pinecone env var ands api key

Traceback (most recent call last):
  File "C:\Users\k\Documents\coding\ai\auto\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "C:\Users\k\Documents\coding\ai\auto\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "C:\Users\k\Documents\coding\ai\auto\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes   
    return self.call_with_http_info(**kwargs)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1324, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1260, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

**Comment by Ryuu3rs** [comment]
i got an error for Pinecone as well but it was telling me that its Index is too small and I need to upgrade my plan I was working with GPT to try and fix it.

**Comment by dreiscm** [comment]
same thing here

**Comment by BrandoPeter** [comment]
There's a bit of latency with index creation in Pinecone. In my case, I just reran the script after 5 minutes or so.

**Comment by panlina** [comment]
Same as above. Reran and it went well.

**Comment by gsquared1** [comment]
Same problem as above.

**Comment by Explorergt92** [comment]
@jimmylimshopping is this still an issue for you or can this be closed?

**Comment by Qoyyuum** [comment]
Just make sure your Pinecone API Key and Region is set up correctly in .env when running autogpt. Also because the changes have been rapidly improved in the last few days, this should work now. If not, please raise a separate Github Issue with details from `--debug` and attaching a log file.

Thanks!
