### ISSUE TITLE
Failing to start autoGPT after pull : OSError: Starting path not found

### ISSUE THREAD

**Issue by sjnt1** [Significant-Gravitas/Auto-GPT#4336]
Hi. Last used it at 2.0 or something, 

Im running it outside docker. 

When i try to start it i get this: 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\AutoGPT\auto-gpt\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AutoGPT\auto-gpt\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\AutoGPT\auto-gpt\autogpt\main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AutoGPT\auto-gpt\autogpt\plugins.py", line 223, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins\autogpt-twitter.zip.zip\autogpt-twitter-master\__init__.py", line 9, in <module>
  File "plugins\autogpt-twitter.zip.zip\autogpt-twitter-master\twitter.py", line 10, in <module>
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\dotenv\main.py", line 336, in load_dotenv
    dotenv_path = find_dotenv()
                  ^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\dotenv\main.py", line 300, in find_dotenv
    for dirname in _walk_to_root(path):
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\dotenv\main.py", line 257, in _walk_to_root
    raise IOError('Starting path not found')
OSError: Starting path not found

**Comment by ntindle** [comment]
Restart the setup from scratch including your .env. Lots has changed/been renamed. Keep your old .env for reference

**Comment by sjnt1** [comment]
Restart the setup? I pulled the new stable, updated my the new env with my credentials. What else to do?
