### ISSUE TITLE
I got many errors

### ISSUE THREAD

**Issue by m1hamedCS** [Significant-Gravitas/Auto-GPT#4358]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mohamed/opt/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mohamed/autogpt/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mohamed/opt/Auto-GPT/autogpt/cli.py", line 93, in main
    from autogpt.main import run_auto_gpt
  File "/home/mohamed/opt/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/home/mohamed/opt/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/mohamed/opt/Auto-GPT/autogpt/agent/agent.py", line 9, in <module>
    from autogpt.json_utils.json_fix_llm import fix_json_using_multiple_techniques
  File "/home/mohamed/opt/Auto-GPT/autogpt/json_utils/json_fix_llm.py", line 13, in <module>
    from autogpt.json_utils.json_fix_general import correct_json
  File "/home/mohamed/opt/Auto-GPT/autogpt/json_utils/json_fix_general.py", line 11, in <module>
    from autogpt.json_utils.utilities import extract_char_position
  File "/home/mohamed/opt/Auto-GPT/autogpt/json_utils/utilities.py", line 33, in <module>
    def validate_json(json_object: object, schema_name: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Qoyyuum** [comment]
@m1hamedCS what python version are you using? How did you set up your autogpt? What Linux distro are you using?

**Comment by DGdev91** [comment]
You are using python 3.9, AutoGPT neds at least Python 3.10

**Comment by AngeloSchulerPiletti** [comment]
I was facing the same problem. You may have installed the right version of the python. But your PATH can be still pointing to the old version. I would suggest you to use [Python Version Manager](https://github.com/pyenv/pyenv#understanding-path)

**Comment by m1hamedCS** [comment]
@Qoyyuum 
I tried python3 and python3.1 and python3.8 and python3.9 but get the same error
I use Linux Mint VERSION="20.3 (Una)"

**Comment by m1hamedCS** [comment]
@AngeloSchulerPiletti 
The solution you provided worked wonderfully for me. Thank you, my friend.
