### ISSUE TITLE
ModuleNotFoundError: No module named 'docx'

### ISSUE THREAD

**Issue by cvarrichio** [Significant-Gravitas/Auto-GPT#4641]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I run 
`docker-compose` run --rm auto-gpt`
I receive the following error:

```
    import docx
ModuleNotFoundError: No module named 'docx'
ERROR: 1
```

For a long time, this did not affect the stable branch and only affected the latest version of master.  However, since the new release this affects all versions.  

Although, I shouldn't need to, I have tried manually instally python-docx in my local environment and adding an additional like to Dockerfile that manually installs it.  This does not work.

### Upload Error Log Content

Traceback (most recent call last):   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main     return _run_code(code, main_globals, None,   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code     exec(code, run_globals)   File "/app/autogpt/__main__.py", line 5, in <module>     autogpt.cli.main()   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__     return self.main(*args, **kwargs)   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main     rv = self.invoke(ctx)   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke     rv = super().invoke(ctx)   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke     return ctx.invoke(self.callback, **ctx.params)   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke     return __callback(*args, **kwargs)   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func     return f(get_current_context(), *args, **kwargs)   File "/app/autogpt/cli.py", line 96, in main     run_auto_gpt(   File "/app/autogpt/main.py", line 158, in run_auto_gpt     command_registry.import_commands(command_category)   File "/app/autogpt/commands/command.py", line 121, in import_commands     module = importlib.import_module(module_name)   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 883, in exec_module   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   File "/app/autogpt/commands/file_operations.py", line 14, in <module>     from autogpt.commands.file_operations_utils import read_textual_file   File "/app/autogpt/commands/file_operations_utils.py", line 5, in <module>     import docx ModuleNotFoundError: No module named 'docx' ERROR: 1

**Comment by cvarrichio** [comment]
Additional info:
If I work around the docx import, the imports for pypdf and DDGS also fail.  Everything else works successfully.
