### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by loootte** [Significant-Gravitas/Auto-GPT#4667]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

.\run.bat  in Anaconda Powershell Prompt

I get error message as below:
Traceback (most recent call last):
  File "E:\Users\MI\anaconda3\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\Users\MI\anaconda3\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "E:\Users\MI\anaconda3\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\workspace\Auto-GPT\autogpt\__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

### Upload Activity Log Content

Traceback (most recent call last):   File "E:\Users\MI\anaconda3\lib\runpy.py", line 187, in _run_module_as_main     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)   File "E:\Users\MI\anaconda3\lib\runpy.py", line 146, in _get_module_details     return _get_module_details(pkg_main_name, error)   File "E:\Users\MI\anaconda3\lib\runpy.py", line 110, in _get_module_details     __import__(pkg_name)   File "D:\workspace\Auto-GPT\autogpt\__init__.py", line 5, in <module>     from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'

**Comment by loootte** [comment]
(base) C:\Users\MI>python --version
Python 3.10.9

**Comment by Carmisito** [comment]
I encountered a very similar problem!
Thought I was going crazy. I tried to install dotenv in any way I could find and it just wasn't recognized.
I'm still using the stable version - How did you solve it?
d:\Auto-GPT>python -m autogpt
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "d:\Auto-GPT\autogpt\__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by BAHLZ** [comment]
Same issue
Python 3.12.0

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\Initus\Desktop\AutoGPT-0.4.7\autogpt\__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
