### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit'

### ISSUE THREAD

**Issue by chrisduk112** [Significant-Gravitas/Auto-GPT#4679]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I updated AutoGPT to fix a bug the developers fixed for me in another post.
Now when i run:

`root@AutoGPT:~/Auto-GPT# python3 -m autogpt`

I get this:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Auto-GPT/autogpt/cli.py", line 93, in main
    from autogpt.main import run_auto_gpt
  File "/root/Auto-GPT/autogpt/main.py", line 8, in <module>
    from autogpt.agent import Agent
  File "/root/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/root/Auto-GPT/autogpt/agent/agent.py", line 26, in <module>
    from autogpt.memory.vector import VectorMemory
  File "/root/Auto-GPT/autogpt/memory/vector/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
  File "/root/Auto-GPT/autogpt/memory/vector/memory_item.py", line 13, in <module>
    from autogpt.processing.text import chunk_content, split_text, summarize_text
  File "/root/Auto-GPT/autogpt/processing/text.py", line 13, in <module>
    from autogpt.utils import batch
  File "/root/Auto-GPT/autogpt/utils.py", line 8, in <module>
    from prompt_toolkit import ANSI, PromptSession
ModuleNotFoundError: No module named 'prompt_toolkit'
```

I am using Pyton 3.11.2:

Python 3.11.2 (main, May 30 2023, 17:45:26) [GCC 12.2.0] on linux

**Comment by chrisduk112** [comment]
I fixed this by running:

`sudo apt install jupyter-console`

must be something new needed in todays build of auto gpt

**Comment by merwanehamadi** [comment]
most likely the issue was something else, we don't have jupyter-console installed

**Comment by erik-megarad** [comment]
Need to update your python dependencies
