### ISSUE TITLE
not enough tokens?

### ISSUE THREAD

**Issue by vipervs** [Significant-Gravitas/Auto-GPT#4759]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Agents

### Describe your issue.

this is my issue after letting him google for documents to summarize them into a file, oh and also it is not possible to use the 3.5.-16k model.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/andi/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/
site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/andi/Auto-GPT/autogpt/main.py", line 197, in run_auto_gpt
    agent.start_interaction_loop()
  File "/Users/andi/Auto-GPT/autogpt/agent/agent.py", line 130, in start_interaction_loop
    assistant_reply = chat_with_ai(
                      ^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/llm/chat.py", line 112, in chat_with_ai
    new_summary_message, trimmed_messages = agent.history.trim_messages(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/memory/message_history.py", line 79, in trim_messages
    new_summary_message = self.update_running_summary(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/memory/message_history.py", line 194, in update_running_summary
    self.summary = create_chat_completion(prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/llm/utils/__init__.py", line 53, in metered_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/llm/utils/__init__.py", line 87, in _wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/llm/utils/__init__.py", line 235, in create_chat_completion
    response = api_manager.create_chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/autogpt/llm/api_manager.py", line 61, in create_chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/andi/Auto-GPT/venvAutoGPT/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 7183 tokens. Please reduce the length of the messages.

**Comment by krrishdholakia** [comment]
Hey! try doing this but wrap the openai base with reliableGPT 

`from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...)`

source: https://github.com/BerriAI/reliableGPT
