### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ZNCisPRO** [Significant-Gravitas/Auto-GPT#4792]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\agent\agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\app.py", line 27, in <module>
    from autogpt.commands.web_selenium import browse_website
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\commands\web_selenium.py", line 20, in <module>
    import autogpt.processing.text as summary
  File "C:\Users\kaust\Auto-GPT-stable-0.2.2\autogpt\processing\text.py", line 4, in <module>
    import spacy
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\__init__.py", line 6, in <module>    from .errors import setup_default_warnings
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\errors.py", line 2, in <module>
    from .compat import Literal
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\thinc\backends\__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python311\Lib\site-packages\thinc\backends\cupy_ops.py", line 4, in <module>
    from .numpy_ops import NumpyOps
ImportError: DLL load failed while importing numpy_ops: The specified module could not be found.

**Comment by chaoscreater** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/2773
