### ISSUE TITLE
--Speak is broken TypeError: say_text() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by NeonN3mesis** [Significant-Gravitas/Auto-GPT#4794]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

Running speak gives an error 
```
Traceback (most recent call last):
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nips\Desktop\New_autogpt\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Nips\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Nips\Desktop\New_autogpt\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\Nips\Desktop\New_autogpt\Auto-GPT\autogpt\main.py", line 142, in run_auto_gpt
    ai_config = construct_main_ai_config(config)
  File "C:\Users\Nips\Desktop\New_autogpt\Auto-GPT\autogpt\prompts\prompt.py", line 62, in construct_main_ai_config
    logger.typewriter_log(
  File "C:\Users\Nips\Desktop\New_autogpt\Auto-GPT\autogpt\logs.py", line 92, in typewriter_log
    say_text(f"{title}. {content}")
TypeError: say_text() missing 1 required positional argument: 'config'
```
### Upload Activity Log Content

2023-06-25 21:05:26,937 INFO  You interrupted Auto-GPT 2023-06-25 21:05:26,937 INFO  Quitting... 2023-06-25 21:06:50,033 INFO Debug Mode:  ENABLED 2023-06-25 21:06:50,176 INFO Speak Mode:  ENABLED 2023-06-25 21:06:50,759 INFO NEWS: Welcome to Auto-GPT! 2023-06-25 21:06:50,759 INFO NEWS: Below you'll find the latest Auto-GPT News and updates regarding features! 2023-06-25 21:06:50,759 INFO NEWS: If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag. 2023-06-25 21:06:50,759 INFO NEWS:  2023-06-25 21:06:50,760 INFO NEWS: Website and Documentation Site 📰📖 2023-06-25 21:06:50,760 INFO NEWS: Check out https://agpt.co, the official news & updates site for Auto-GPT! 2023-06-25 21:06:50,760 INFO NEWS: The documentation also has a place here, at https://docs.agpt.co 2023-06-25 21:06:50,760 INFO NEWS:  2023-06-25 21:06:50,760 INFO NEWS: For contributors 👷🏼 2023-06-25 21:06:50,760 INFO NEWS: Since releasing v0.3.0, whave been working on re-architecting the Auto-GPT core to make it more extensible and make room for structural performance-oriented R&D. 2023-06-25 21:06:50,760 INFO NEWS:  2023-06-25 21:06:50,760 INFO NEWS: Check out the contribution guide on our wiki: 2023-06-25 21:06:50,760 INFO NEWS: https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing 2023-06-25 21:06:50,760 INFO NEWS:  2023-06-25 21:06:50,762 INFO NEWS: 🚀 v0.4.1 Release 🚀 2023-06-25 21:06:50,762 INFO NEWS: Two weeks and 50+ pull requests have passed since v0.4.0, and we are happy to announce the release of v0.4.1! 2023-06-25 21:06:50,762 INFO NEWS:  2023-06-25 21:06:50,762 INFO NEWS: Highlights and notable changes since v0.4.0: 2023-06-25 21:06:50,762 INFO NEWS: - The .env.template is more readable and better explains the purpose of each environment variable. 2023-06-25 21:06:50,762 INFO NEWS: - More dependable search 2023-06-25 21:06:50,762 INFO NEWS:     - The CUSTOM_SEARCH_ENGINE_ID variable has been replaced to GOOGLE_CUSTOM_SEARCH_ENGINE_ID, make sure you update it. 2023-06-25 21:06:50,762 INFO NEWS: - Better read_file 2023-06-25 21:06:50,762 INFO NEWS: - More reliable python code execution 2023-06-25 21:06:50,763 INFO NEWS: - Lots of JSON error fixes 2023-06-25 21:06:50,763 INFO NEWS: - Directory-based plugins 2023-06-25 21:06:50,763 INFO NEWS:  2023-06-25 21:06:50,763 INFO NEWS: Further fixes and changes 🛠️ 2023-06-25 21:06:50,763 INFO NEWS: Under the hood, we've done a bunch of work improving architectures and streamlining code. Most of that won't be user-visible 2023-06-25 21:06:50,764 INFO NEWS:  2023-06-25 21:06:50,764 INFO NEWS: Take a look at the Release Notes on Github for the full changelog! 2023-06-25 21:06:50,764 INFO NEWS: https://github.com/Significant-Gravitas/Auto-GPT/releases 2023-06-25 21:06:50,764 INFO NEWS:  2023-06-25 21:06:50,765 INFO WARNING:  You are running on `master` branch - this is not a supported branch. 2023-06-25 21:06:51,234 DEBUG  The following command categories are disabled: [] 2023-06-25 21:06:51,234 DEBUG  The following command categories are enabled: ['autogpt.commands.execute_code', 'autogpt.commands.file_operations', 'autogpt.commands.web_search', 'autogpt.commands.web_selenium', 'autogpt.app', 'autogpt.commands.task_statuses']

**Comment by DonChi-Chi** [comment]
Same error here! Only tried with ElevenLabs.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\Documents\AI\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__    
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main        
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke      
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke      
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke       
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\AI\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\User\Documents\AI\Auto-GPT\autogpt\main.py", line 157, in run_auto_gpt
    ai_config = construct_main_ai_config(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\AI\Auto-GPT\autogpt\prompts\prompt.py", line 62, in construct_main_ai_config
    logger.typewriter_log(
  File "C:\Users\User\Documents\AI\Auto-GPT\autogpt\logs.py", line 92, in typewriter_log
    say_text(f"{title}. {content}")
TypeError: say_text() missing 1 required positional argument: 'config'

**Comment by cshirley001** [comment]
Same results with the same setup (Win10, ElevenLabs) py -m autogpt --speak:

Traceback (most recent call last):
  File "C:\Users\corey\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\corey\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\corey\AppData\Roaming\Python\Python310\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\main.py", line 157, in run_auto_gpt
    ai_config = construct_main_ai_config(config)
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\prompts\prompt.py", line 81, in construct_main_ai_config
    ai_config = prompt_user(config)
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\setup.py", line 30, in prompt_user
    logger.typewriter_log(
  File "C:\_ai\agpt\Auto-GPT-0.4.3\autogpt\logs.py", line 92, in typewriter_log
    say_text(f"{title}. {content}")
TypeError: say_text() missing 1 required positional argument: 'config'

**Comment by Monty1122** [comment]
same for me on Mac OS - something about - GPT4 thinks its to do with parameters being called but I cant find it (and neither can GPT4) 

"When say_text is called here, it's being provided with only one argument (f"{title}. {content}"), but it needs at least two (text and config), with an optional third (voice_index)."

**Comment by Sylvien** [comment]
me too
