### ISSUE TITLE
When having files in the plugin directory, I get this error (even if the configuration is set to false for all the plugins).

### ISSUE THREAD

**Issue by LanceLake** [Significant-Gravitas/Auto-GPT#4817]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

WARNING:  You are running on `master` branch - this is not a supported branch.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Coderoot\AI\AutoGPT\Pure\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Coderoot\AI\AutoGPT\Pure\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Coderoot\AI\AutoGPT\Pure\autogpt\main.py", line 124, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Coderoot\AI\AutoGPT\Pure\autogpt\plugins\__init__.py", line 270, in scan_plugins
    plugin_enabled = plugins_config.is_enabled(plugin_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'is_enabled'

**Comment by suziaki** [comment]
Have you found a fix or workaround, I get the same error

**Comment by LanceLake** [comment]
Nope. I just removed all plugins from the directory. 

I should also point out, ALL the plugins. Even the one that is from the same repo user here.

**Comment by LanceLake** [comment]
> I deleted plugins/Auto-GPT-Plugins.zip `rm -rf plugins/Auto-GPT-Plugins.zip` This solve the issue.
> 
> You can install again the plugins again from here https://github.com/Significant-Gravitas/Auto-GPT-Plugins#installation

Yes. As I mentioned, removing the plugins does make it load. However, putting them back in breaks it again.

**Comment by Dunya-8a** [comment]
Same problem here
