### ISSUE TITLE
unable to run using Azure AccessToken 

### ISSUE THREAD

**Issue by barroei** [Significant-Gravitas/Auto-GPT#4841]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when trying to run AutoGPT i adjusted the .env per request with USE_Azure=True 
and the API_Access_Key=Azure Access Token 

on top of this, i edited azure.yaml 
azure_api_type: azure
azure_api_base: https://openai-chat-gpt.openai.azure.com 
azure_api_version: 2023-03-15-preview
azure_model_map:
    fast_llm_model_deployment_id: gpt-35-turbo
    smart_llm_model_deployment_id: gpt-4 
    embedding_model_deployment_id: text-embedding-ada-002

tried running it via run.sh, and via docker-compose. 
on both i get the following :Debug Mode:  ENABLED
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/main.py", line 60, in run_auto_gpt
    create_config(
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/configurator.py", line 103, in create_config
    config.fast_llm_model = check_model(config.fast_llm_model, "fast_llm_model")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/llm/utils/__init__.py", line 182, in check_model
    models = api_manager.get_models()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rbar/Downloads/Auto-GPT/autogpt/llm/api_manager.py", line 107, in get_models
    all_models = openai.Model.list()["data"]
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: **Your authentication token is not from a valid issuer.**

please help, as i cant make it run.

**Comment by moluuser** [comment]
I have the same problem. I use the following method to get the key.
https://gist.github.com/primaryobjects/523577860628974501ffd3c52cd73525

**Comment by moluuser** [comment]
> I have the same problem. I use the following method to get the key. https://gist.github.com/primaryobjects/523577860628974501ffd3c52cd73525

I use the wrong command to get the key, maybe should use `az cognitiveservices account keys list --name {} --resource-group {}` for the above example.
