### ISSUE TITLE
Deploying docker image using Azure access token results in 'str type expected' error

### ISSUE THREAD

**Issue by theJamess** [Significant-Gravitas/Auto-GPT#4844]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Attempting to run an auto-gpt Docker container on an Azure ACR that also uses Azure Cognitive Services. Container builds fine, and it runs properly when using an OpenAI API key with USE_AZURE=False. When using the Azure access token as the api key, however, container returns the following error on run and then exits without writing anything to the log file:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 55, in run_auto_gpt
    config = Config.build_config_from_env()
  File "/app/autogpt/config/config.py", line 257, in build_config_from_env
    return cls.build_agent_configuration(config_dict_without_none_values)
  File "/app/autogpt/core/configuration/schema.py", line 46, in build_agent_configuration
    return cls.defaults_settings.__class__.parse_obj(final_configuration)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigSettings
openai_api_version
  str type expected (type=type_error.str)
```

**Comment by VectorZhao** [comment]
same error

```
(autogpt) C:\Users\10923\Auto-GPT>.\run.bat
All packages are installed.
Plugin config is invalid, continuing without plugins. Error: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\10923\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\anaconda3\envs\autogpt\Lib\site-packages\click\decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\Auto-GPT\autogpt\cli.py", line 117, in main
    run_auto_gpt(
  File "C:\Users\10923\Auto-GPT\autogpt\main.py", line 59, in run_auto_gpt
    config = ConfigBuilder.build_config_from_env()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\Auto-GPT\autogpt\config\config.py", line 310, in build_config_from_env
    return cls.build_agent_configuration(config_dict_without_none_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10923\Auto-GPT\autogpt\core\configuration\schema.py", line 52, in build_agent_configuration
    return cls.default_settings.__class__.parse_obj(final_configuration)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Config
openai_api_version
  str type expected (type=type_error.str)
```

**Comment by VectorZhao** [comment]
What is the current progress?

**Comment by VectorZhao** [comment]
Is there any update about this?
