### ISSUE TITLE
I couldn't run plugins on Auto-GPT v0.4.3 i can run plugins in the older version but with the ALLOWLISTED_PLUGINS removd i couldnt make it work.

### ISSUE THREAD

**Issue by ilaisudri07** [Significant-Gravitas/Auto-GPT#4854]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Plugins

### Describe your issue.

ilais-Air:Auto-GPT ilaisudri$ python3 -m autogpt
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
NEWS:  
NEWS:  Website and Documentation Site 📰📖
NEWS:  Check out https://agpt.co, the official news & updates site for Auto-GPT!
NEWS:  The documentation also has a place here, at https://docs.agpt.co
NEWS:  
NEWS:  For contributors 👷🏼
NEWS:  Since releasing v0.3.0, whave been working on re-architecting the Auto-GPT core to make it more extensible and make room for structural performance-oriented R&D.
NEWS:  
NEWS:  Check out the contribution guide on our wiki:
NEWS:  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing
NEWS:  
NEWS:  🚀 v0.4.3 Release 🚀
NEWS:  We're happy to announce the 0.4.3 maintenance release, which primarily focuses on refining the LLM command execution,
NEWS:  extending support for OpenAI's latest models (including the powerful GPT-3 16k model), and laying the groundwork 
NEWS:  for future compatibility with OpenAI's function calling feature.
NEWS:  
NEWS:  Key Highlights:
NEWS:  - OpenAI API Key Prompt: Auto-GPT will now courteously prompt users for their OpenAI API key, if it's not already provided.
NEWS:  - Summarization Enhancements: We've optimized Auto-GPT's use of the LLM context window even further.
NEWS:  - JSON Memory Reading: Support for reading memories from JSON files has been improved, resulting in enhanced task execution.
NEWS:  - Deprecated commands, removed for a leaner, more performant LLM: analyze_code, write_tests, improve_code, audio_text, web_playwright, web_requests
NEWS:  Take a look at the Release Notes on Github for the full changelog!
NEWS:  https://github.com/Significant-Gravitas/Auto-GPT/releases
NEWS:  
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ilaisudri/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ilaisudri/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/ilaisudri/Auto-GPT/autogpt/main.py", line 124, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
  File "/Users/ilaisudri/Auto-GPT/autogpt/plugins/__init__.py", line 270, in scan_plugins
    plugin_enabled = plugins_config.is_enabled(plugin_name)
AttributeError: 'dict' object has no attribute 'is_enabled'

**Comment by derekslenk** [comment]
Same issue on Ubuntu:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 124, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
  File "/app/autogpt/plugins/__init__.py", line 270, in scan_plugins
    plugin_enabled = plugins_config.is_enabled(plugin_name)
AttributeError: 'dict' object has no attribute 'is_enabled'
```

**Comment by dvirarad** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/4817#issuecomment-1627269315
fixed here

**Comment by derekslenk** [comment]
Working for me
