### ISSUE TITLE
clean docker installation: ModuleNotFoundError: No module named 'autogpt.memory_item'

### ISSUE THREAD

**Issue by ram-sh** [Significant-Gravitas/Auto-GPT#4989]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Hello, clean installation on windows docker ver 0.44, install without errors, when running for first time I get the error:

`vscode ➜ /workspace/Auto-GPT $ '/workspace/Auto-GPT/run.sh'
All packages are installed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'
Press any key to continue...`

I've also set the memory to redis in the env file but that didnt change anything, same error.

[added the unit test output]

can you pls point me to what is it i'm missing here?

Many thanks!
RS

### Upload Error Log Content

vscode ➜ /workspace/Auto-GPT $ python tests.py 
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: challenges.basic_abilities.test_browse_website (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.basic_abilities.test_browse_website
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/basic_abilities/test_browse_website.py", line 3, in <module>
    from autogpt.workspace import Workspace
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: challenges.basic_abilities.test_write_file (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.basic_abilities.test_write_file
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/basic_abilities/test_write_file.py", line 4, in <module>
    from autogpt.workspace import Workspace
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: challenges.memory.test_memory_challenge_a (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.memory.test_memory_challenge_a
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/memory/test_memory_challenge_a.py", line 5, in <module>
    from autogpt.workspace import Workspace
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: challenges.memory.test_memory_challenge_b (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.memory.test_memory_challenge_b
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/memory/test_memory_challenge_b.py", line 4, in <module>
    from autogpt.workspace import Workspace
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: challenges.memory.test_memory_challenge_c (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.memory.test_memory_challenge_c
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/memory/test_memory_challenge_c.py", line 4, in <module>
    from autogpt.commands.file_operations import read_file
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: challenges.memory.test_memory_challenge_d (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: challenges.memory.test_memory_challenge_d
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/challenges/memory/test_memory_challenge_d.py", line 7, in <module>
    from autogpt.commands.file_operations import read_file
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.memory.test_json_file_memory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.memory.test_json_file_memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/memory/test_json_file_memory.py", line 7, in <module>
    from autogpt.memory.vector import JSONFileMemory, MemoryItem
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.test_execute_code (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.test_execute_code
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/test_execute_code.py", line 8, in <module>
    import autogpt.commands.execute_code as sut  # system under testing
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.test_image_gen (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.test_image_gen
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/test_image_gen.py", line 9, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.test_provider_openai (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.test_provider_openai
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/test_provider_openai.py", line 5, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.test_setup (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.test_setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/test_setup.py", line 6, in <module>
    from autogpt.setup import generate_aiconfig_automatic, prompt_user
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: integration.test_web_selenium (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration.test_web_selenium
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/integration/test_web_selenium.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_agent (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_agent
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_agent.py", line 5, in <module>
    from autogpt.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_agent_manager (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_agent_manager
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_agent_manager.py", line 3, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_api_manager (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_api_manager
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_api_manager.py", line 6, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_commands (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_commands
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_commands.py", line 9, in <module>
    from autogpt.models.command_registry import CommandRegistry
  File "/workspace/Auto-GPT/autogpt/models/command_registry.py", line 5, in <module>
    from autogpt.command_decorator import AUTO_GPT_COMMAND_IDENTIFIER
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_config (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_config
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_config.py", line 12, in <module>
    from autogpt.configurator import GPT_3_MODEL, GPT_4_MODEL, create_config
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_execute_command (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_execute_command
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_execute_command.py", line 1, in <module>
    from autogpt.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_file_operations (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_file_operations
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_file_operations.py", line 14, in <module>
    import autogpt.commands.file_operations as file_ops
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_git_commands (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_git_commands
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_git_commands.py", line 5, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_message_history (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_message_history
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_message_history.py", line 7, in <module>
    from autogpt.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_prompt_config (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_prompt_config
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_prompt_config.py", line 1, in <module>
    from autogpt.config.prompt_config import PromptConfig
  File "/workspace/Auto-GPT/autogpt/config/prompt_config.py", line 8, in <module>
    from autogpt import utils
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_prompt_generator (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_prompt_generator
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_prompt_generator.py", line 1, in <module>
    from autogpt.prompts.generator import PromptGenerator
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_retry_provider_openai (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_retry_provider_openai
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_retry_provider_openai.py", line 4, in <module>
    from autogpt.llm.providers import openai
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_spinner (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_spinner
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_spinner.py", line 4, in <module>
    from autogpt.spinner import Spinner
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_text_file_parsers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_text_file_parsers
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_text_file_parsers.py", line 10, in <module>
    from autogpt.commands.file_operations_utils import is_file_binary_fn, read_textual_file
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_token_counter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_token_counter
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_token_counter.py", line 3, in <module>
    from autogpt.llm.base import Message
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_url_validation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_url_validation
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_url_validation.py", line 4, in <module>
    from autogpt.url_utils.validators import validate_url
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_utils
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_utils.py", line 8, in <module>
    from autogpt.json_utils.utilities import extract_json_from_response, validate_json
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_web_search (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_web_search
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_web_search.py", line 6, in <module>
    from autogpt.agent.agent import Agent
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

======================================================================
ERROR: unit.test_workspace (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_workspace
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspace/Auto-GPT/tests/unit/test_workspace.py", line 6, in <module>
    from autogpt.workspace import Workspace
  File "/workspace/Auto-GPT/autogpt/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
ModuleNotFoundError: No module named 'autogpt.memory_item'

----------------------------------------------------------------------
Ran 31 tests in 0.003s

FAILED (errors=31)
Name                                                              Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------
autogpt/__init__.py                                                  30     27    10%   5-142
autogpt/config/__init__.py                                            3      0   100%
autogpt/config/ai_config.py                                          61     45    26%   16-17, 52-57, 73-89, 103-110, 126-165
autogpt/config/config.py                                            155     59    62%   90-98, 104-148, 158, 160, 162, 223-319, 333-336, 350-375, 380-382
autogpt/config/prompt_config.py                                      17     13    24%   9-47
autogpt/core/__init__.py                                              0      0   100%
autogpt/core/configuration/__init__.py                                1      0   100%
autogpt/core/configuration/schema.py                                 49     23    53%   9, 14, 43, 49-52, 65-84, 98-107
autogpt/log_cycle/__init__.py                                         0      0   100%
autogpt/log_cycle/json_handler.py                                    13      5    62%   7, 10-12, 20
autogpt/logs.py                                                     177    102    42%   15, 33, 93, 97-100, 105-119, 129, 137, 145, 148, 157-160, 165-166, 169-177, 181-192, 195-197, 207-224, 229-233, 243-260, 264-265, 269, 280-321
autogpt/models/__init__.py                                            0      0   100%
autogpt/models/base_open_ai_plugin.py                                60     26    57%   21-26, 33, 37, 44, 54, 61, 77, 86, 93, 102, 109, 124, 133, 140, 152, 159, 169, 183, 205, 224, 242
autogpt/models/command.py                                            23     16    30%   27-33, 36-42, 45-49
autogpt/models/command_parameter.py                                   9      1    89%   12
autogpt/models/command_registry.py                                   57     53     7%   6-110
autogpt/plugins/__init__.py                                         160    134    16%   21, 42-50, 60-61, 73-115, 126-136, 151-190, 206-209, 222-320
autogpt/plugins/plugin_config.py                                      6      0   100%
autogpt/plugins/plugins_config.py                                    57     39    32%   19, 22, 25-26, 35-54, 63-86, 95-112
autogpt/singleton.py                                                  8      0   100%
tests/challenges/__init__.py                                          0      0   100%
tests/challenges/basic_abilities/__init__.py                          0      0   100%
tests/challenges/basic_abilities/test_browse_website.py              13     11    15%   4-34
tests/challenges/basic_abilities/test_write_file.py                  18     15    17%   5-45
tests/challenges/challenge_decorator/__init__.py                      0      0   100%
tests/challenges/memory/__init__.py                                   0      0   100%
tests/challenges/memory/test_memory_challenge_a.py                   30     26    13%   6-86
tests/challenges/memory/test_memory_challenge_b.py                   33     30     9%   5-86
tests/challenges/memory/test_memory_challenge_c.py                   34     31     9%   5-105
tests/challenges/memory/test_memory_challenge_d.py                   44     39    11%   8-213
tests/challenges/test_challenge_should_be_formatted_properly.py      32     21    34%   15-24, 28-35, 39, 47-48, 54-59
tests/integration/__init__.py                                         0      0   100%
tests/integration/memory/__init__.py                                  0      0   100%
tests/integration/memory/test_json_file_memory.py                    88     83     6%   8-132
tests/integration/test_execute_code.py                               76     70     8%   9-139
tests/integration/test_image_gen.py                                 115    108     6%   10-252
tests/integration/test_provider_openai.py                            36     33     8%   6-54
tests/integration/test_setup.py                                      43     39     9%   9-73
tests/integration/test_web_selenium.py                               12      9    25%   5-17
tests/mocks/__init__.py                                               0      0   100%
tests/unit/__init__.py                                                0      0   100%
tests/unit/test_agent.py                                             26     23    12%   6-43
tests/unit/test_agent_manager.py                                     43     41     5%   4-70
tests/unit/test_ai_config.py                                         35     30    14%   12-45, 51-59, 65-74
tests/unit/test_api_manager.py                                       52     48     8%   7-86
tests/unit/test_commands.py                                         112    105     6%   11-229
tests/unit/test_config.py                                            95     89     6%   13-251
tests/unit/test_execute_command.py                                    9      8    11%   2-23
tests/unit/test_file_operations.py                                  159    151     5%   15-330
tests/unit/test_git_commands.py                                      24     20    17%   6-43
tests/unit/test_logs.py                                               5      1    80%   28
tests/unit/test_message_history.py                                   79     74     6%   8-143
tests/unit/test_plugins.py                                           60     44    27%   17-25, 30-42, 47-59, 63-64, 69-90, 101-120
tests/unit/test_prompt_config.py                                     19     18     5%   3-45
tests/unit/test_prompt_generator.py                                  50     49     2%   4-101
tests/unit/test_retry_provider_openai.py                             81     78     4%   7-135
tests/unit/test_spinner.py                                           31     29     6%   6-70
tests/unit/test_text_file_parsers.py                                 95     87     8%   11-150
tests/unit/test_token_counter.py                                     23     21     9%   4-55
tests/unit/test_url_validation.py                                    65     62     5%   6-166
tests/unit/test_utils.py                                            113    107     5%   9-206
tests/unit/test_web_search.py                                        43     39     9%   7-136
tests/unit/test_workspace.py                                         32     28    12%   8-99
tests/vcr/__init__.py                                                40     24    40%   24, 29-35, 40-41, 45-47, 52-67
tests/vcr/vcr_filter.py                                              53     36    32%   26-27, 35-39, 43-63, 67-69, 73-79, 86-94, 99-102
-----------------------------------------------------------------------------------------------
TOTAL

**Comment by ram-sh** [comment]
there are missing paths in the init:

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/5938042/7d77639e-80e2-4559-8a67-92110e2ea87d)

adding `autogpt.memory.vector` solved this but now i crash on plugin part...

**Comment by b8kings0ga** [comment]
ModuleNotFoundError: No module named 'autogpt.prompts.generator'
