### ISSUE TITLE
cant find API key although it is in the .env file

### ISSUE THREAD

**Issue by ram-sh** [Significant-Gravitas/Auto-GPT#4990]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

hello, a clean install of 0.44, windows, vs code, dev container - the API key is in the `.env` file but the system can't find it:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/5938042/f89a0f8f-0cf3-487b-8b49-7c4842a3e86a)

Please advice,
Thx much!
RS

### Upload Error Log Content

vscode ➜ /workspace/Auto-GPT $ python tests.py 
  Reading file /tmp/tmpp_rhe95z.txt with parser <autogpt.commands.file_operations_utils.TXTParser object at 0x7ffa8a4a3ca0>
  Reading '/tmp/tmpp_rhe95z.txt' with encoding 'ascii'
  Reading file /tmp/tmpip09q4i_.csv with parser <autogpt.commands.file_operations_utils.TXTParser object at 0x7ffa8a4a3cd0>
  Reading '/tmp/tmpip09q4i_.csv' with encoding 'ascii'
  Reading file /tmp/tmpsv26zcy8.pdf with parser <autogpt.commands.file_operations_utils.PDFParser object at 0x7ffa8a4a3d00>
incorrect startxref pointer(1)
  Reading file /tmp/tmpkcdnmhu_.docx with parser <autogpt.commands.file_operations_utils.DOCXParser object at 0x7ffa8a4a3d30>
  Reading file /tmp/tmp8ql881u7.json with parser <autogpt.commands.file_operations_utils.JSONParser object at 0x7ffa8a4a3d60>
  Reading file /tmp/tmpf_bvq8iz.xml with parser <autogpt.commands.file_operations_utils.XMLParser object at 0x7ffa8a4a3d90>
  Reading file /tmp/tmpzxygzvk4.yaml with parser <autogpt.commands.file_operations_utils.YAMLParser object at 0x7ffa8a4a3dc0>
  Reading file /tmp/tmp25ug8xpx.html with parser <autogpt.commands.file_operations_utils.HTMLParser object at 0x7ffa8a4a3e20>
  Reading file /tmp/tmpl4b9jm5j.md with parser <autogpt.commands.file_operations_utils.MarkdownParser object at 0x7ffa8a4a3eb0>
  Reading file /tmp/tmpct7udchz.tex with parser <autogpt.commands.file_operations_utils.LaTeXParser object at 0x7ffa8a4a3f10>
.
----------------------------------------------------------------------
Ran 1 test in 0.053s

OK
Name                                                              Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------
autogpt/__init__.py                                                  30     20    33%   58-135, 139
autogpt/agent/__init__.py                                             3      0   100%
autogpt/agent/agent.py                                              147    122    17%   71-84, 88-307, 312-320
autogpt/agent/agent_manager.py                                       69     58    16%   14-18, 36-72, 84-119, 129, 141-145
autogpt/app.py                                                       43     35    19%   19-23, 44-78, 96-114
autogpt/command_decorator.py                                         20      1    95%   49
autogpt/commands/__init__.py                                          0      0   100%
autogpt/commands/execute_code.py                                    102     80    22%   46-65, 88-169, 182-190, 217-236, 264-286, 295
autogpt/commands/file_operations.py                                 125     96    23%   23, 30-51, 68-74, 91-96, 109-113, 138-148, 163-174, 204-215, 247-260, 283-290, 313-324
autogpt/commands/file_operations_utils.py                            98      7    93%   18, 105-106, 149, 156-159
autogpt/commands/git_operations.py                                   14      7    50%   39-49
autogpt/commands/image_gen.py                                        74     58    22%   40-51, 64-109, 127-149, 171-200
autogpt/commands/web_search.py                                       45     32    29%   38-55, 84-124, 137-143
autogpt/commands/web_selenium.py                                    107     66    38%   65-81, 93-157, 169-177, 189, 201-206, 227-237
autogpt/config/__init__.py                                            3      0   100%
autogpt/config/ai_config.py                                          61     45    26%   16-17, 52-57, 73-89, 103-110, 126-165
autogpt/config/config.py                                            155     59    62%   90-98, 104-148, 158, 160, 162, 223-319, 333-336, 350-375, 380-382
autogpt/config/prompt_config.py                                      17     10    41%   36-47
autogpt/configurator.py                                              78     67    14%   16, 52-167
autogpt/core/__init__.py                                              0      0   100%
autogpt/core/configuration/__init__.py                                1      0   100%
autogpt/core/configuration/schema.py                                 49     23    53%   9, 14, 43, 49-52, 65-84, 98-107
autogpt/json_utils/__init__.py                                        0      0   100%
autogpt/json_utils/utilities.py                                      39     28    28%   17-28, 34-40, 54-73
autogpt/llm/__init__.py                                               2      0   100%
autogpt/llm/api_manager.py                                           45     23    49%   22-26, 38-51, 60, 69, 78, 87, 96, 106-110
autogpt/llm/base.py                                                  88     25    72%   8, 31, 79, 82, 85, 88, 91, 94-95, 99-104, 109, 113-115, 118, 121-130, 154-155
autogpt/llm/chat.py                                                  77     65    16%   9, 43-207
autogpt/llm/providers/__init__.py                                     0      0   100%
autogpt/llm/providers/openai.py                                     109     42    61%   16, 126-135, 138-141, 144-149, 182-204, 227-233, 252, 274, 311, 334-337
autogpt/llm/utils/__init__.py                                        65     52    20%   41-59, 69-85, 109-164, 177-190
autogpt/llm/utils/token_counter.py                                   32     25    22%   27-57, 71-72
autogpt/log_cycle/__init__.py                                         0      0   100%
autogpt/log_cycle/json_handler.py                                    13      5    62%   7, 10-12, 20
autogpt/log_cycle/log_cycle.py                                       46     24    48%   24, 28-29, 32-43, 46, 49-53, 58-61, 78-88
autogpt/logs.py                                                     177     87    51%   15, 33, 93, 97-100, 105-119, 137, 145, 148, 159, 165-166, 169-177, 181-192, 195-197, 207-224, 232-233, 251, 259, 269, 280-321
autogpt/main.py                                                      76     58    24%   57-205
autogpt/memory/message_history.py                                    98     69    30%   9, 30, 33, 36, 44, 47, 65-85, 94-111, 116, 140-202, 205-231
autogpt/memory/vector/__init__.py                                    30     20    33%   58-135, 139
autogpt/memory/vector/memory_item.py                                 88     39    56%   33, 44-90, 102, 107, 114-135, 145, 154-158, 170, 211-213, 232-239, 244, 249-250, 253
autogpt/memory/vector/providers/__init__.py                           3      0   100%
autogpt/memory/vector/providers/base.py                              29     13    55%   18, 30-31, 47-61, 70-71, 78
autogpt/memory/vector/providers/json_file.py                         56     35    38%   32-45, 48, 51, 54, 57-60, 63-66, 70-71, 75-82, 85-87
autogpt/memory/vector/providers/no_memory.py                         20      7    65%   18, 21, 24, 27, 30, 33, 36
autogpt/memory/vector/utils.py                                       31     18    42%   16, 21, 36-64
autogpt/models/__init__.py                                            0      0   100%
autogpt/models/base_open_ai_plugin.py                                60     26    57%   21-26, 33, 37, 44, 54, 61, 77, 86, 93, 102, 109, 124, 133, 140, 152, 159, 169, 183, 205, 224, 242
autogpt/models/command.py                                            23      9    61%   36-42, 45-49
autogpt/models/command_parameter.py                                   9      1    89%   12
autogpt/models/command_registry.py                                   57     38    33%   22, 25, 28, 31-43, 46-51, 55-60, 63-67, 70-72, 78-81, 96-110
autogpt/plugins/__init__.py                                         160    134    16%   21, 42-50, 60-61, 73-115, 126-136, 151-190, 206-209, 222-320
autogpt/plugins/plugin_config.py                                      6      0   100%
autogpt/plugins/plugins_config.py                                    57     39    32%   19, 22, 25-26, 35-54, 63-86, 95-112
autogpt/processing/__init__.py                                        0      0   100%
autogpt/processing/html.py                                            7      2    71%   18, 33
autogpt/processing/text.py                                          106     91    14%   17-20, 26, 39-57, 79-140, 168-244
autogpt/prompts/__init__.py                                           0      0   100%
autogpt/prompts/default_prompts.py                                    3      0   100%
autogpt/prompts/generator.py                                         57     28    51%   11, 38-46, 55, 78-87, 99-102, 111, 120, 134-146, 156, 175-177
autogpt/prompts/prompt.py                                            53     40    25%   27-44, 58-132
autogpt/setup.py                                                     78     64    18%   35-87, 109-195, 205-238
autogpt/singleton.py                                                  8      0   100%
autogpt/speech/__init__.py                                            2      0   100%
autogpt/speech/base.py                                               24     10    58%   10, 24-29, 39-45
autogpt/speech/eleven_labs.py                                        37     25    32%   11, 27-49, 62-63, 75-91
autogpt/speech/gtts.py                                               14      6    57%   15, 19-23
autogpt/speech/macos_tts.py                                          13      7    46%   12, 16-22
autogpt/speech/say.py                                                32     19    41%   9, 24-35, 40-50
autogpt/speech/stream_elements_speech.py                             19     10    47%   27-44
autogpt/spinner.py                                                   39     28    28%   24-29, 33-38, 41-43, 47-51, 61-65, 73-76
autogpt/url_utils/__init__.py                                         0      0   100%
autogpt/url_utils/validators.py                                      31     19    39%   27-38, 52-56, 68-70, 82-107
autogpt/utils.py                                                     98     78    20%   20-23, 27-63, 67-78, 87-91, 95-104, 108-113, 117-138, 142-160, 164-181
autogpt/workspace/__init__.py                                         2      0   100%
autogpt/workspace/workspace.py                                       56     35    38%   25-26, 31, 36, 54-56, 72, 112-140, 144-148, 154-162
benchmarks.py                                                        30     20    33%   11-12, 16-32, 46-52
scripts/__init__.py                                                   0      0   100%
scripts/install_plugin_deps.py                                       35     26    26%   21-61, 65
tests/__init__.py                                                     0      0   100%
tests/challenges/__init__.py                                          0      0   100%
tests/challenges/basic_abilities/__init__.py                          0      0   100%
tests/challenges/basic_abilities/test_browse_website.py              13      5    62%   22-34
tests/challenges/basic_abilities/test_write_file.py                  18      8    56%   29-45
tests/challenges/challenge_decorator/__init__.py                      0      0   100%
tests/challenges/challenge_decorator/challenge.py                    13      8    38%   17-24
tests/challenges/challenge_decorator/challenge_decorator.py          53     35    34%   27-69, 79-84
tests/challenges/challenge_decorator/challenge_utils.py              32     23    28%   15-25, 42-54, 58-61, 69, 81
tests/challenges/challenge_decorator/score_utils.py                  32     20    38%   17-18, 24-29, 33-34, 38-41, 45-49, 53-59
tests/challenges/memory/__init__.py                                   0      0   100%
tests/challenges/memory/test_memory_challenge_a.py                   30     18    40%   33-43, 60-65, 80-86
tests/challenges/memory/test_memory_challenge_b.py                   33     21    36%   32-43, 61-67, 80-86
tests/challenges/memory/test_memory_challenge_c.py                   34     21    38%   34-61, 79-84, 99-105
tests/challenges/memory/test_memory_challenge_d.py                   44     26    41%   33-49, 54-162, 170-172, 189-194, 208-213
tests/challenges/schema.py                                            3      0   100%
tests/challenges/test_challenge_should_be_formatted_properly.py      32     21    34%   15-24, 28-35, 39, 47-48, 54-59
tests/challenges/utils.py                                            35     19    46%   16-17, 32-41, 47-50, 56, 62-64, 74-78
tests/integration/__init__.py                                         0      0   100%
tests/integration/memory/__init__.py                                  0      0   100%
tests/integration/memory/test_json_file_memory.py                    88     69    22%   13-14, 18-23, 27-33, 39-50, 54-56, 60-67, 71-79, 83-97, 103-121, 128-132
tests/integration/test_execute_code.py                               76     50    34%   15, 20-25, 30, 34-35, 39-49, 55-63, 67-80, 84, 91, 101-102, 106-107, 111-114, 118-122, 126-130, 134-139
tests/integration/test_image_gen.py                                 115     83    28%   16, 23, 41, 53, 63-81, 86, 98-105, 125-154, 158-177, 181-202, 206-225, 229-240, 244-252
tests/integration/test_provider_openai.py                            36     24    33%   13-14, 21-35, 40-54
tests/integration/test_setup.py                                      43     27    37%   12-19, 25-31, 37-52, 58-73
tests/integration/test_web_selenium.py                               12      5    58%   11-17
tests/mocks/__init__.py                                               0      0   100%
tests/unit/__init__.py                                                0      0   100%
tests/unit/test_agent.py                                             26     18    31%   12-32, 36-43
tests/unit/test_agent_manager.py                                     43     24    44%   12-13, 18, 23, 28, 33-42, 46-49, 53-56, 60-63, 67-70
tests/unit/test_ai_config.py                                         35     30    14%   12-45, 51-59, 65-74
tests/unit/test_api_manager.py                                       52     32    38%   14-15, 20-29, 35-40, 45-48, 53-61, 69-76, 81-86
tests/unit/test_commands.py                                         112     84    25%   20, 25-35, 42, 52-53, 58-59, 64-69, 74-80, 85-86, 91-100, 105-114, 119-130, 135-140, 145-148, 153-164, 169-172, 177-188, 193-200, 211-229
tests/unit/test_config.py                                            95     76    20%   20-24, 32-38, 46-52, 60-66, 74-80, 88-94, 102-132, 136-146, 150-205, 209-228, 232-251
tests/unit/test_execute_command.py                                    9      5    44%   6, 11-23
tests/unit/test_file_operations.py                                  159    115    28%   24, 31, 48, 53-56, 61-66, 71, 76, 80-98, 103-119, 124-163, 173-176, 180-183, 187-190, 199-200, 204-206, 210-214, 218-223, 227-235, 241-245, 249-257, 263-274, 281-283, 287-295, 300-330
tests/unit/test_git_commands.py                                      24     15    38%   11, 15-27, 34-43
tests/unit/test_logs.py                                               5      1    80%   28
tests/unit/test_message_history.py                                   79     65    18%   18-38, 42-143
tests/unit/test_plugins.py                                           60     44    27%   17-25, 30-42, 47-59, 63-64, 69-90, 101-120
tests/unit/test_prompt_config.py                                     19     16    16%   12-45
tests/unit/test_prompt_generator.py                                  50     44    12%   8-11, 18-29, 36-39, 47-50, 60-101
tests/unit/test_retry_provider_openai.py                             81     69    15%   9-12, 18-31, 37-46, 56-83, 88-100, 105-119, 124-135
tests/unit/test_spinner.py                                           31     21    32%   33-35, 40-42, 48-52, 57-63, 68-70
tests/unit/test_text_file_parsers.py                                 95      0   100%
tests/unit/test_token_counter.py                                     23     13    43%   8-12, 17, 22-27, 31-35, 41-42, 48, 54-55
tests/unit/test_url_validation.py                                    65     41    37%   36, 49, 62-63, 77-78, 86-91, 97-101, 110-115, 121-126, 132-136, 145-150, 154-155, 159-161, 165-166
tests/unit/test_utils.py                                            113     77    32%   21, 38, 51-57, 61-64, 68-77, 81-84, 89-96, 103-106, 111-114, 118-122, 126-135, 139-149, 153-162, 167-170, 175-178, 183-186, 190, 194, 198-199, 205-206
tests/unit/test_web_search.py                                        43     27    37%   15-17, 21-22, 41-47, 52-55, 86-88, 120-136
tests/unit/test_workspace.py                                         32     15    53%   57, 62, 67, 71-77, 81-82, 90-93, 97-99
tests/utils.py                                                        6      1    83%   14
tests/vcr/__init__.py                                                40     24    40%   24, 29-35, 40-41, 45-47, 52-67
tests/vcr/vcr_filter.py                                              53     36    32%   26-27, 35-39, 43-63, 67-69, 73-79, 86-94, 99-102
-----------------------------------------------------------------------------------------------
TOTAL                                                              5573   3552    36%

**Comment by ram-sh** [comment]
adding the key manually, crashed the system,  
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/cli.py", line 117, in main
    run_auto_gpt(
  File "/workspace/Auto-GPT/autogpt/main.py", line 65, in run_auto_gpt
    check_openai_api_key(config)
  File "/workspace/Auto-GPT/autogpt/config/config.py", line 368, in check_openai_api_key
    + Fore.ORANGE
AttributeError: 'AnsiFore' object has no attribute 'ORANGE'
Press any key to continue...`

the reason is that there is no `Fore.ORANGE`, change it to BLUE bypassed this error...

however, this has not solved the reading of the key from the `.env` file.
