### ISSUE TITLE
Network problems?为什么啊？

### ISSUE THREAD

**Issue by 1219ls** [Significant-Gravitas/Auto-GPT#5029]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

fatal: unable to access 'https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template/': Failed to connect to github.com port 443 after 21058 ms: Timed out
说是网络问题？试了好几次，有其他解决办法没

**Comment by 1219ls** [comment]
Missing packages:
beautifulsoup4>=4.12.2, colorama==0.4.6, distro==1.8.0, openai==0.27.2, playsound==1.2.2, pyyaml==6.0, PyPDF2, python-docx, markdown, pylatexenc, readability-lxml==0.8.1, requests, tiktoken==0.3.3, gTTS==2.3.1, docker, duckduckgo-search==3.0.2, google-api-python-client, pinecone-client==2.2.1, redis, orjson==3.8.10, Pillow, selenium==4.1.4, webdriver-manager, jsonschema, click, charset-normalizer>=3.1.0, spacy<4.0.0,>=3.0.0, en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl, prompt_toolkit>=3.0.38, pydantic, inflection, fastapi, uvicorn, coverage, flake8, numpy, pre-commit, black, isort, gitpython==3.1.31, auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0, mkdocs, pymdown-extensions, mypy, types-Markdown, types-beautifulsoup4, types-colorama, types-Pillow, openapi-python-client==0.13.4, pytest, asynctest, pytest-asyncio, pytest-benchmark, pytest-cov, pytest-integration, pytest-mock, vcrpy@ git+https://github.com/Significant-Gravitas/vcrpy.git@master, pytest-recording, pytest-xdist
Installing missing packages...
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (from -r requirements.txt (line 29))
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 16.8 MB/s eta 0:00:00
Collecting auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0 (from -r requirements.txt (line 46))
  Cloning https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template (to revision 0.1.0) to c:\users\18298\appdata\local\temp\pip-install-e6x022jd\auto-gpt-plugin-template_8fb9a58a931343e69077af32ee10da16
  Running command git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\18298\AppData\Local\Temp\pip-install-e6x022jd\auto-gpt-plugin-template_8fb9a58a931343e69077af32ee10da16'
  fatal: unable to access 'https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template/': Failed to connect to github.com port 443 after 21058 ms: Timed out
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\18298\AppData\Local\Temp\pip-install-e6x022jd\auto-gpt-plugin-template_8fb9a58a931343e69077af32ee10da16' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\18298\AppData\Local\Temp\pip-install-e6x022jd\auto-gpt-plugin-template_8fb9a58a931343e69077af32ee10da16' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\18298\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "C:\Users\18298\Auto-GPT\autogpt\cli.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
请按任意键继续. . .
