### ISSUE TITLE
failed to connect to port 

### ISSUE THREAD

**Issue by DMTarmey** [Significant-Gravitas/Auto-GPT#5110]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa998c039d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Upload Error Log Content

@DMTarmey ➜ /workspace/Auto-GPT $ ./run.sh --continuous
All packages are installed.
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f832a87c100>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f832a87c100>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f832a87c100>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/app/cli.py", line 121, in main
    run_auto_gpt(
  File "/workspace/Auto-GPT/autogpt/app/main.py", line 70, in run_auto_gpt
    create_config(
  File "/workspace/Auto-GPT/autogpt/app/configurator.py", line 99, in create_config
    config.fast_llm = check_model(config.fast_llm, "fast_llm", config=config)
  File "/workspace/Auto-GPT/autogpt/app/configurator.py", line 176, in check_model
    models = api_manager.get_models(**openai_credentials)
  File "/workspace/Auto-GPT/autogpt/llm/api_manager.py", line 107, in get_models
    all_models = openai.Model.list(**openai_credentials)["data"]
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 288, in request
    result = self.request_raw(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f832a87c100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Press any key to continue...
@DMTarmey ➜ /workspace/Auto-GPT $ dir
Auto-GPT            LICENSE           auto_gpt_workspace   data                logs          plugins               run.bat             speech.mp3
BULLETIN.md         Pipfile           autogpt              data_ingestion.py   mkdocs.yml    plugins_config.yaml   run.sh              tests
CODE_OF_CONDUCT.md  README.md         azure.yaml.template  docker-compose.yml  mypy.ini      prompt_settings.yaml  run_continuous.bat  venvAutoGPT
CONTRIBUTING.md     agbenchmark       benchmarks.py        docs                netlify.toml  pyproject.toml        run_continuous.sh
Dockerfile          ai_settings.yaml  codecov.yml          hooks               plugin.png    requirements.txt      scripts
@DMTarmey ➜ /workspace/Auto-GPT $  run_continuous.bat
bash: run_continuous.bat: command not found
@DMTarmey ➜ /workspace/Auto-GPT $ ./run.sh --gpt3only
All packages are installed.
GPT3.5 Only Mode:  ENABLED
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
NEWS:  
NEWS:  QUICK LINKS 🔗
NEWS:  --------------
NEWS:  🌎 Official Website: https://agpt.co.
NEWS:  📖 User Guide: https://docs.agpt.co.
NEWS:  👩 Contributors Wiki: https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing.
NEWS:  
NEWS:  v0.4.6 RELEASE HIGHLIGHTS! 🚀
NEWS:  -----------------------------
NEWS:  This release includes under-the-hood improvements and bug fixes, including better UTF-8
NEWS:  special character support, workspace write access for sandboxed Python execution,
NEWS:  more robust path resolution for config files and the workspace, and a full restructure
NEWS:  of the Agent class, the "brain" of Auto-GPT, to make it more extensible.
NEWS:  
NEWS:  We have also released some documentation updates, including:
NEWS:  
NEWS:  - How to share your system logs
NEWS:    Visit [docs/share-your-logs.md] to learn how to how to share logs with us
NEWS:    via a log analyzer graciously contributed by https://www.e2b.dev/
NEWS:  
NEWS:  - Auto-GPT re-architecture documentation
NEWS:    You can learn more about the inner-workings of the Auto-GPT re-architecture
NEWS:    released last cycle, via these links:
NEWS:    * [autogpt/core/README.md]
NEWS:    * [autogpt/core/ARCHITECTURE_NOTES.md]
NEWS:  
NEWS:  Take a look at the Release Notes on Github for the full changelog!
NEWS:  https://github.com/Significant-Gravitas/Auto-GPT/releases.
NEWS:  
Welcome back!  Would you like me to return to being Darren?
  Asking user via keyboard...
Continue with the last settings?
Name:  Darren
Role:  list what you cna do
Goals: ['what can you do ', 'how cna i use you', 'what is the best way to use you']
API Budget: $1.5
Continue (y/y): i would like you to investigate what it is need to be done to you own progamming so you can see all of you own coding ?
NOTE:All files/directories created by this agent can be found inside its workspace at:  /workspace/Auto-GPT/auto_gpt_workspace
Darren  has been created with the following details:
Name:  Darren
Role:  list what you cna do
Goals: 
-  what can you do
-  how cna i use you
-  what is the best way to use you
Using memory of type:  JSONFileMemory
Using Browser:  chrome
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa998c039d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa998c039d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa998c039d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/app/cli.py", line 121, in main
    run_auto_gpt(
  File "/workspace/Auto-GPT/autogpt/app/main.py", line 174, in run_auto_gpt
    run_interaction_loop(agent)
  File "/workspace/Auto-GPT/autogpt/app/main.py", line 255, in run_interaction_loop
    command_name, command_args, assistant_reply_dict = agent.think()
  File "/workspace/Auto-GPT/autogpt/agents/base.py", line 112, in think
    raw_response = create_chat_completion(
  File "/workspace/Auto-GPT/autogpt/llm/utils/__init__.py", line 162, in create_chat_completion
    response = iopenai.create_chat_completion(
  File "/workspace/Auto-GPT/autogpt/llm/providers/openai.py", line 151, in metered_func
    return func(*args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/llm/providers/openai.py", line 186, in _wrapped
    return func(*args, **kwargs)
  File "/workspace/Auto-GPT/autogpt/llm/providers/openai.py", line 235, in create_chat_completion
    completion: OpenAIObject = openai.ChatCompletion.create(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 288, in request
    result = self.request_raw(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa998c039d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Press any key to continue...

**Comment by DMTarmey** [comment]
I worked out the issue i hadn't ticked in setting to allow port forwarding
