### ISSUE TITLE
no module named 'ftfy'

### ISSUE THREAD

**Issue by swchu0922** [Significant-Gravitas/Auto-GPT#5124]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

I executed auto-get successfully many times. Today I use git pull to upgrade it to v0.4.7. After running "docker compose run --rm auto-gpt", I got below traceback message in cmd:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/app/cli.py", line 118, in main
    from autogpt.app.main import run_auto_gpt
  File "/app/autogpt/app/main.py", line 14, in <module>
    from autogpt.app.configurator import create_config
  File "/app/autogpt/app/configurator.py", line 14, in <module>
    from autogpt.memory.vector import get_supported_memory_backends
  File "/app/autogpt/memory/vector/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
  File "/app/autogpt/memory/vector/memory_item.py", line 7, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

**Comment by petertadrous** [comment]
Please run 

```
docker image list
```

And then copy the `IMAGE ID` for the auto-gpt docker image, and run

```
docker image rm <image id>
```

This should remove the outdated docker image. Running `docker compose run --rm auto-gpt` will now create a new image using the new Dockerfile.
