### ISSUE TITLE
Error when running python scripts/main.py

### ISSUE THREAD

**Issue by 1zzyDeadYet** [Significant-Gravitas/Auto-GPT#554]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

C:\Users\ismit\OneDrive\Desktop\Auto-GPT-master>python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to increase revenue starting with 100$. All final say has to be run through me but you will come up with all the ideas and work. Our Goal is to increase our net worth and financial stability.
Goals: ['Increase net worth', 'increase revenue', 'Gain financial stability', 'invest', 'sell services online that can be competed with free AI tools']
Continue (y/n): y

### Current behavior 😯

C:\Users\ismit\OneDrive\Desktop\Auto-GPT-master>python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to increase revenue starting with 100$. All final say has to be run through me but you will come up with all the ideas and work. Our Goal is to increase our net worth and financial stability.
Goals: ['Increase net worth', 'increase revenue', 'Gain financial stability', 'invest', 'sell services online that can be competed with free AI tools']
Continue (y/n): y
Traceback (most recent call last):
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Program Files\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\index.py", line 329, in delete
    return self._vector_api.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api\vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\client\rest.py", line 157, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Program Files\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ismit\OneDrive\Desktop\Auto-GPT-master\scripts\main.py", line 289, in <module>
    memory.clear()
  File "C:\Users\ismit\OneDrive\Desktop\Auto-GPT-master\scripts\memory.py", line 46, in clear
    self.index.delete(deleteAll=True)
  File "C:\Users\ismit\AppData\Roaming\Python\Python311\site-packages\pinecone\core\utils\error_handling.py", line 25, in inner_func
    raise PineconeProtocolError(f'Failed to connect; did you specify the correct index name?') from e
pinecone.core.exceptions.PineconeProtocolError: Failed to connect; did you specify the correct index name?

### Expected behavior 🤔

Should run as expected

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
Try getting latest (git pull).  I know Pinecone are having issues at the moment and the latest AutoGPT defaults back to a local memory store.

**Comment by scriptogre** [comment]
Hello!

The error implies that the index was not found. Is it possible you might have changed the index/table name in pinecone? 

It normally defaults to auto-gpt. You can try deleting the Pinecone index and letting the scrip recreate it. Also, definitely pull the latest changes to your local repository. :)

**Comment by hughperkins** [comment]
random bystander comments: looks like some issue with pinecone. Is your internet connection working otherwise? Did you provide a valid pinecone api key and pinecone env name?

**Comment by rishi-ratan** [comment]
I am getting this error when I run following command:
(base) XXX@XXX-MacBook-Air Auto-GPT % python scripts/main.py

**Output:** 
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y

Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/rishiratan/Library/CloudStorage/OneDrive-Personal/Learning/CodingPrep/Python/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/Users/rishiratan/Library/CloudStorage/OneDrive-Personal/Learning/CodingPrep/Python/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

**Comment by hannesvienna9000** [comment]
Above config debug error is solved here: https://github.com/Torantulino/Auto-GPT/issues/803#issuecomment-1503345517

**Comment by elviskojo** [comment]
python: can't open file 'C:\\AI\\autogpt\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory
whats the meaning?
