### ISSUE TITLE
function() argument 'code' must be code, not str

### ISSUE THREAD

**Issue by Tikusarma** [Significant-Gravitas/Auto-GPT#703]
Traceback (most recent call last):
  File "/root/Desktop/hacking techniques/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/root/Desktop/hacking techniques/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/root/Desktop/hacking techniques/Auto-GPT/scripts/browse.py", line 3, in <module>
    from config import Config
  File "/root/Desktop/hacking techniques/Auto-GPT/scripts/config.py", line 3, in <module>
    import openai
  File "/usr/local/lib/python3.9/dist-packages/openai/__init__.py", line 9, in <module>
    from openai.api_resources import (
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/__init__.py", line 1, in <module>
    from openai.api_resources.audio import Audio  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/audio.py", line 4, in <module>
    from openai import api_requestor, util
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 21, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by caranicas** [comment]
ran into the same issue. not sure how to solve it.

**Comment by caranicas** [comment]
@Tikusarma I pasted the error in gpt4 and it told me to try updating `aoihttp`, so I ran  `pip install --upgrade aiohttp`, and now it is working.
