### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by dudelama** [Significant-Gravitas/Auto-GPT#71]
I get the following error:

  File "C:\Users\PranavTej\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by engma-linguistics** [comment]
You have to have API access to it specifically, otherwise you probably ought replace any gpt-4 call with gpt-3.5-turbo. It's way cheaper anyways!

**Comment by Torantulino** [comment]
Give me 5 mins.

**Comment by Torantulino** [comment]
Fixed! https://github.com/Torantulino/Auto-GPT/commit/51e293f64cf17efbbba18965037a8004387945a6

Now use the argument
```
--gpt3only
```
To run AutoGPT without GPT4 access!

**Comment by n2nco** [comment]
If you're not an insider or openai sycophant, you've got to pay for early openai api access (plugins or gpt-4)

**Comment by rogeriosmorais** [comment]
I have the API key, have inserted it into my .env file and I still get this error. I tried both with and without quotes surrounding it. "Last used" on my OpenAI keys page says "Never".

**Comment by professorpalmer** [comment]
> I'm also seeing the same error, despite the new "GPT3.5 Only Mode".
> 
> Note, `scripts/token_counter.py` uses hard-coded values for `model`. Maybe update all `model` mentions using environment variables: `SMART_LLM_MODEL` and `FAST_LLM_MODEL`?

Getting this issue as well, despite --gpt3only 

```
SYSTEM:  Command write_tests returned: Error: The model: `gpt-4` does not exist
Traceback (most recent call last):
  File "C:\Users\snyone\Auto-GPT\scripts\main.py", line 295, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\snyone\Auto-GPT\scripts\chat.py", line 125, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\snyone\Auto-GPT\scripts\llm_utils.py", line 18, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\snyone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
    ```

**Comment by sjnt1** [comment]
Im having this issue alot. Every time it tries to evaluate code it tries to use gpt 4 and the error message. 

Does updating the model mentions those enviroment variables fix the issue?

**Comment by claytondukes** [comment]
I'm having this issue but have a paid gpt-4 account. I *want* it to use gpt-4.

**Comment by Slowly-Grokking** [comment]
> I'm having this issue but have a paid gpt-4 account. I _want_ it to use gpt-4.

you have beta access to GPT4 API?  ChatGPT Plus for $20/month doesn't work for this right now.

**Comment by claytondukes** [comment]
> > I'm having this issue but have a paid gpt-4 account. I _want_ it to use gpt-4.
> 
> you have beta access to GPT4 API? ChatGPT Plus for $20/month doesn't work for this right now.

Not the beta, I have the $20/month one. So I should only use gpt-3 then?

**Comment by Slowly-Grokking** [comment]
> So I should only use gpt-3 then?

yeah, use the --gpt3only

**Comment by charltonh** [comment]
I'd rather just use a local copy of gpt4all

**Comment by sjnt1** [comment]
What is your experience with gpt4all?

**Comment by richbeales** [comment]
closing this
