### ISSUE TITLE
Connection issues, TimeoutError - WinError 10060

### ISSUE THREAD

**Issue by JimiVex** [Significant-Gravitas/Auto-GPT#799]
On start, it asks the default question of whether you want it to continue as Entrepenuer-GPT, on hitting y, this is the first block of tracebacks. I think the rest may be redundant, as they are in python failing to cope with this root issue.

Traceback (most recent call last):
  File "C:\Users\CENSORED\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\CENSORED\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\CENSORED\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by Qoyyuum** [comment]
Hi @JimiVex try using the latest stable release and try again. If it is still an issue, please raise a new issue under bug report template. Thanks!
