### ISSUE TITLE
OSError: Unable to load sound

### ISSUE THREAD

**Issue by AHorihuela** [Significant-Gravitas/Auto-GPT#856]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Running `python3 scripts/main.py --speak`

### Current behavior 😯

Getting the following error:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Alberto/Dropbox (Personal)/Programming/Auto-GPT/scripts/speak.py", line 61, in speak
    success = eleven_labs_speech(text, voice_index)
  File "/Users/Alberto/Dropbox (Personal)/Programming/Auto-GPT/scripts/speak.py", line 34, in eleven_labs_speech
    playsound("speech.mpeg", True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playsound.py", line 67, in _playsoundOSX
    raise IOError('Unable to load sound named: ' + sound)
OSError: Unable to load sound named: file:///Users/Alberto/Dropbox (Personal)/Programming/Auto-GPT/speech.mpeg`

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by AHorihuela** [comment]
> 

Just did that, but no luck!

**Comment by keyserfaty** [comment]
Did 2 things to fix this error:
1. Completed these 2 env variables:
```
ELEVENLABS_VOICE_1_ID=
ELEVENLABS_VOICE_2_ID=
```
You can find Elevenlabs voice ids here: https://api.elevenlabs.io/v1/voices

2. There's a bug on `playsound.py` where file or folder names with spaces in it break. I renamed the folder where I'm storing the repo and removed a space in the name (i.e. 'folder name' to 'folder-name') and it worked 🙃

**Comment by daveebbelaar** [comment]
I was running into the same issue due to spaces in the full path on macOS. Here's how I fixed it:

1. Change playsound.py line 63 from: `sound = 'file://' + sound` to `sound = 'file://' + quote(sound)` 
2. Add the `from urllib.parse import quote` import statement.

**Comment by jimprince** [comment]
Also worked for me.
