### ISSUE TITLE
This type of issues faced

### ISSUE THREAD

**Issue by anantha624gmail** [Significant-Gravitas/Auto-GPT#91]
~/Auto-GPT $ python scripts/main.py --gpt3only
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/data/data/com.termux/files/home/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/data/data/com.termux/files/home/Auto-GPT/scripts/browse.py", line 3, in <module>
    from config import Config
  File "/data/data/com.termux/files/home/Auto-GPT/scripts/config.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by AnkurSalunkhe11** [comment]
The error message is telling you that the dotenv module cannot be found, which is needed by the config.py script in order to run.

To solve this issue, you need to install the dotenv module. You can install it by running the following command in your terminal:

Copy code= 

                          `pip install python-dotenv`
If you have already installed the dotenv module, make sure that it is installed in the correct environment or virtual environment that you are using to run your code.

**Comment by SUBRATNAYAK7504** [comment]
it's already installed but still getting the error

**Comment by richbeales** [comment]
closing, please re-open if still an issue.
