### ISSUE TITLE
Does not ignore errors from the side of open.ai  api and turns off

### ISSUE THREAD

**Issue by amsator** [Significant-Gravitas/Auto-GPT#930]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python scripts/main.py --gpt3only 
 Input:y -20

### Current behavior 😯

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/home/m/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/m/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/m/.local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/home/m/Auto-GPT/scripts/chat.py", line 128, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/home/m/Auto-GPT/scripts/llm_utils.py", line 19, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/home/m/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/m/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/m/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/m/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Expected behavior 🤔

RemoteDisconnected error means that the remote server closed the connection without sending any response. This could be due to various reasons, such as network issues, server overload, or invalid requests.
Use a try-except block to catch the RemoteDisconnected exception and skip or log the error.
Here is an example of how you can use a try-except block in Python:

import requests
import random
import time

url = "https://example.com/api"
params = {"query": "some value"}

try:
    response = requests.get(url, params=params)
    # do something with response
except requests.exceptions.ConnectionError as e:
    # handle connection error
    print(e)
except requests.exceptions.RemoteDisconnected as e:
    # handle remote disconnected error
    print(e)
    # skip or log the error
except Exception as e:
    # handle other exceptions
    print(e)
    # retry with a random delay
    randomtime = random.randint(1,5)
    print(f"Retrying in {randomtime} seconds")
    time.sleep(randomtime)

### Your prompt 📝

```yaml
# Paste your prompt here
```ai_goals:
- 'find new neural networks that have appeared today compile a catalog of these neural
  networks with links to their sites and a brief description of what they do update
  this plan update daily: look only for new directories with neural networks and create
  a copy of them look for new solutions for this task and offer them'
ai_name: Aibest
ai_role: you are an experienced analyst and systems thinker using the methods of triz
  and Goldratt and de bono

**Comment by Qoyyuum** [comment]
Please use the latest stable release and try again. `python scripts/main.py` is no longer available. In the stable release, please use `python -m autogpt`. Use `python -m autogpt --help` for extra help options. Thanks. Closing issue.
